#!/bin/sh

# $Id$
# Skriver ut volume label på CDROM’en som står i.

device=/dev/cdrom

if [ "$1" != "" ]; then
	device=$1
fi

if [ ! -r $device ]; then
	echo "$0: $device: Not readable" >&2
	exit 1
fi

# Først tar vi en fake read for å unngå error
until head -c 1 $device >/dev/null; do
	:
done

head -c 32840 $device | tail -c 32 | rmspcbak
