#!/usr/bin/perl -w

# $Id$

use strict;

$| = 1;

open(PipeFP, "| uudecode | gzip -d") or die("$0: Can't open pipe: $!\n");
while (<>) {
	s/[#%";!{}]//g;
	s/^\s+(.*)/$1/;
	print PipeFP $_;
}

close(PipeFP);
