# Makefile
# File ID: f146dfb2-4aee-11e6-ad43-02010e0a6634
# Author: Øyvind A. Holm <sunny@sunbase.org>

.PHONY: default
default:

.PHONY: clean
clean:
	cd tests && $(MAKE) clean

.PHONY: test
test:
	cd tests && $(MAKE)
