# sunny256/utils.git/Git/Makefile
# File ID: 83bbcb90-4aeb-11e6-b612-02010e0a6634

.PHONY: default
default:
	cd gpstools && $(MAKE)
	cd spar && $(MAKE)
	cd suuid && $(MAKE)

.PHONY: clean
clean:
	cd gpstools && $(MAKE) clean
	cd spar && $(MAKE) clean
	cd suuid && $(MAKE) clean

.PHONY: test
test:
	cd gpstools && $(MAKE) test
	cd spar && $(MAKE) test
	cd suuid && $(MAKE) test
