#!/bin/bash

#=======================================================================
# update
# File ID: f6345be0-abd5-11de-9791-00248cd5cf1e
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

if [ ! -d gpstools/. ]; then
    git clone -o sunbase sunny@git.sunbase.org:/home/sunny/Git/gpstools
    cd gpstools
    make remotes
    cd ..
fi
(cd gpstools && git fetch --all && git checkout master && git merge --ff-only sunbase/master)
