#!/bin/bash

#=======================================================================
# update
# File ID: f6345be0-abd5-11de-9791-00248cd5cf1e
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

if [ ! -d gpstools/. ]; then
    git clone sunny@git.sunbase.org:/home/sunny/Git/gpstools
    cd gpstools
    git remote add github git@github.com:sunny256/gpstools.git
    git remote add gitorious git@gitorious.org:sunny256/gpstools.git
    cd ..
fi
(cd gpstools && git fetch && git merge origin/master)
