#!/bin/bash

#=======================================================================
# update
# File ID: f6345be0-abd5-11de-9791-00248cd5cf1e
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

if [ ! -d build-git/. ]; then
    git clone sunny@git.sunbase.org:/home/sunny/Git/build-git
    cd build-git
    git branch --track commit_symlink origin/commit_symlink
    git remote add ww sunny@git.sunbase.org:/home/sunny/Git/build-git
    git remote add github git@github.com:sunny256/build-git.git
    git remote add gitorious git@gitorious.org:build-git/build-git.git
    cd ..
fi
(cd build-git && git fetch && git checkout commit_symlink && git fetch && git merge origin/commit_symlink)

# Until the gpstools stuff is extracted to its own repo.
exit 0

if [ ! -d gpstools/. ]; then
    git clone sunny@git.sunbase.org:/home/sunny/Git/gpstools
    cd build-git
    git remote add ww sunny@git.sunbase.org:/home/sunny/Git/gpstools
    cd ..
fi
(cd gpstools && git fetch && git merge origin/master)
