# oyvholm/utils/.gitlab-ci.yml
# File ID: be09508c-8383-11e9-bed5-4f45262dc9b5

image: gcc

utils:linux:
  stage: test
  before_script:
    - test "$CI_COMMIT_REF_NAME" = "synced/master" && exit 0 || true
    - apt-get update -qq
    - apt-get install -y -qq
        bc
        cmark
        exiftool
        git-annex
        groff
        libnumber-bytes-human-perl
        libxml2-utils
        sqlite3
        texlive-base
        tzdata
    - echo "Environment variables:"
    - env | grep -E 'TZ|LC|LANG|PATH'
    - echo "Timezone files:"
    - ls -l /usr/share/zoneinfo/CET /usr/share/zoneinfo/EST /usr/share/zoneinfo/UTC || true
    - echo "Testing TZ=CET:"
    - TZ=CET date --date="2009-07-06 21:36:04" +%Y%m%dT%H%M%SZ
    - echo "Testing TZ=EST:"
    - TZ=EST date --date="2009-07-06 21:36:04" +%Y%m%dT%H%M%SZ
    - echo "Testing TZ=UTC:"
    - TZ=UTC date --date="2009-07-06 21:36:04" +%Y%m%dT%H%M%SZ
    - git config --global user.name "Firstname Lastname"
    - git config --global user.email "ci@example.com"
    - git config --global safe.directory "*"
    - git clone https://gitlab.com/oyvholm/suuid.git
    - cd suuid
    - script -e -q -c "make test install"
    - cd ..
    - rm -rf suuid
  script:
    - export PATH=$(pwd):$PATH
    - make
    - make test
    - make test-clean
