#!/usr/bin/perl -w

#====================================================================
# $Id: access_log2epstat,v 1.3 2002/10/01 12:24:30 sunny Exp $
# Konverterer access_log fra Apache til fil som passer til epstat(1).
# Langt og trasig navn, men nøye då.
#====================================================================

use strict;
use Time::Local;

# 194.248.216.3 - - [13/Aug/2001:16:04:37 +0200] "GET

my %mnd_hash = (
	'Jan'=>0, 'Feb'=>1, 'Mar'=>2, 'Apr'=>3, 'May'=>4,  'Jun'=>5,
	'Jul'=>6, 'Aug'=>7, 'Sep'=>8, 'Oct'=>9, 'Nov'=>10, 'Dec'=>11
);

while (<>) {
	if (m!
			\S+ # IP
			\s+
			\S+
			\s+
			\S+
			\s+
			\[
			(\d+) # Dato
			/
			(\S+) # Mnd
			/
			(\d{4}) # År
			:(\d\d):(\d\d):(\d\d) # Klokka
			\s+
		!x
		) {
			my $Mnd = $mnd_hash{$2};
			my $Secs = timelocal($6, $5, $4, $1, $Mnd, $3);
			print("$Secs\n");
		} else {
			print(STDERR "Ukjent linje $.\n");
		}
}

__END__

#### End of file $Id: access_log2epstat,v 1.3 2002/10/01 12:24:30 sunny Exp $ ####
