#!/bin/bash

#=======================================================================
# Add_test
# File ID: 948f70c2-f989-11dd-be4a-000475e441b9
#
# Create new *.t file in the current directory. Specify a name without 
# the .t extension and a file with some common option tests will be 
# created.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=Add_test
VERSION=0.1.0

if test "$1" = "--version"; then
    echo $progname $VERSION
    exit 0
fi

if test -z "$1" -o "$1" = "-h" -o "$1" = "--help"; then
    cat <<END

Create new *.t file in the current directory. Specify a name without the 
.t extension and a file with some common option tests will be created.

Usage: $progname [options] testname

Options:

  -h, --help
    Show this help.
  --version
    Print version information.

END
    exit 0
fi

name=$1
std perl-tests $name.t -t progname=$name -t exec=../$name -t testcmd=$name.t
chmod +x $name.t
