#!/bin/bash

#=======================================================================
# all-lpar
# File ID: d96bacfe-6dda-11e3-8559-001f3b596ec9
# Execute "lpar" in all subdirs
# License: GNU General Public License version 3 or later.
#=======================================================================

if [ "$1" = "-f" ]; then
    find -name '*.git' -print0 | sort -z | xargs -0 git update-dirs -E "lpar" -F -e "lpar"
else
    find -name '*.git' -print0 | sort -z | xargs -0 git update-dirs -E "lpar"
fi
