#!/bin/bash

#=======================================================================
# annex-cmd
# File ID: f1ca60b4-d33a-11e2-a3c0-0800274013ad
# Execute command in all local git-annex repositories
# License: GNU General Public License version 3 or later.
#=======================================================================

wildc='*'

if [ "$1" = "-D" ]; then
    test -z "$2" && { echo annex-cmd: Missing argument for -D >&2; exit 1; }
    wildc="$2"
    shift 2
fi
git update-dirs $HOME/annex/$wildc /media/*/annex/$wildc "$@"
