#!/usr/bin/env perl

# ascii
# File ID: 1c7b6196-5d37-11df-b1f7-90e6ba3022ac
# Avansert esse

use strict;
use warnings;

binmode(STDOUT, ":utf8");

for (32..255) {
	printf("%03u 0x%02x %c\n", $_, $_, $_);
}
