#!/bin/bash

#=======================================================================
# audacity
# File ID: 2c780c66-e36e-11e5-a57a-02010e0a6634
#
# Audacity wrapper
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=audacity
VERSION=0.1.0

if test -e /usr/bin/audacity; then
    /usr/bin/audacity "$@" 2>/dev/null
else
    echo $progname: Audacity isn\'t installed here
fi
