#!/bin/sh

# $Id$

if [ -e /ww.mrk ]; then
  tethereal -t ad -l -q -f '(not port 80)' | \
  egrep -v \
    -e '194.248.216.3 .*TCP .*ssh' \
    -e 'Intel_22:.*Ethernet II' \
    -e 'Cisco_[1-9].* -> ' \
    -e '(radio1.hiof.no|nett.ba.no) -> (radio1.hiof.no|nett.ba.no)' \
    -e '(ns.online.no|nett.ba.no) -> (ns.online.no|nett.ba.no)'
fi

# vim: set ts=2 sw=2 sts=2 et :
