#!/bin/sh

# $Id$

# [ -e /ba0614-woody.mrk ] || { echo "For enkelhets skyld kjøres den bare fra ba0614." >&2; exit 1; }

cd ~/src/cvs/ba/txt
cvs upd -A timeliste.txt
vim timeliste.txt
echo -n Enter for checkin, CTRL-C for å drite i det...
read
cvs ci -m "Lagt inn med ~/bin/bajobb-scriptet." timeliste.txt
