#!/bin/bash

#=======================================================================
# $Id$
# [Description]
# License: GNU General Public License version 2 or later.
#=======================================================================

if [ -z "$1" ]; then
    echo -e "$(utc -L)\t$(cat)" >>~/bom.log
else
    echo -e "$(utc -L)\t$1" >>~/bom.log
fi

