#!/bin/bash

#=======================================================================
# $Id$
# File ID: 3a4bea44-f742-11dd-8c5e-000475e441b9
# [Description]
# License: GNU General Public License version 2 or later.
#=======================================================================

if [ -z "$1" ]; then
    echo -e "$(utc -L)\t$(cat)" >>~/bom.log
else
    echo -e "$(utc -L)\t$1" >>~/bom.log
fi

