#!/bin/bash

#=======================================================================
# build-git
# File ID: 7075da30-98d2-11de-b3de-00248cd5cf1e
#=======================================================================

builddir=$HOME/src/git/other/build-git
pref=/usr/local
sudo=sudo

rmdir $builddir 2>/dev/null
if [ ! -d $builddir/. ]; then
    mkdir -p $builddir || { echo build-git: $builddir: Cannot create directory; exit 1; }
    rmdir $builddir
    echo ================= git clone =================
    git clone git://git.kernel.org/pub/scm/git/git.git $builddir
fi
cd $builddir || { echo build-git: $builddir: Cannot chdir >&2; exit 1; }
if [ ! -e GIT-VERSION-GEN ]; then
    # Paranoia check
    echo build-git: Didn’t find GIT-VERSION-GEN. That’s incredibly strange, aborting.
    exit 1
fi
echo ================= git clean =================
git clean -fxd
git checkout -f master
echo ================= git fetch =================
git fetch
echo ================= git merge origin/master =================
git merge origin/master
vername=git.master-`git describe --abbrev=20`
dest=$pref/varprg/$vername
[ -d $dest/. ] && { echo; echo "Sorry, no new git(1) for you this time."; echo You’ll have to stick with `git describe` for now.; exit 0; }
echo Compiling $vername
echo ================= make =================
make prefix=$pref/varprg/$vername all doc info || exit
echo ================= make test =================
make test
echo
echo -n If all tests succeeded, press y to continue...
read choice
[ "$choice" = "y" ] || { echo build-git: Aborted; exit 1; }
echo ================= $sudo make install =================
$sudo make prefix=$pref/varprg/$vername install install-doc install-html install-info
echo ================= make install finished =================
$sudo mkdir -p $pref/{prg,varprg,bin}
$sudo rm $pref/prg/git
$sudo ln -svf ../varprg/$vername $pref/prg/git
cd $pref/bin || { echo build-git: $pref/bin: Cannot chdir, aborting >&2; exit 1; }
$sudo ln -svf ../prg/git/bin/* .
echo ================= Check that the thing works =================
hash -r
localgit=`./git --version`
globalgit=`git --version`
if [ "$localgit" = "$globalgit" ]; then
    echo Congratulations with your shiny new $globalgit
else
    echo Uhm, something went wrong.
    echo Current version of git : $globalgit
    echo Expected version of git: $localgit
    exit 1
fi
echo ================= symlink manpages =================
cd $pref/prg/git/share/man
mansects=`ls`
for f in $mansects; do
    $sudo mkdir -p $pref/share/man/$f
    cd $pref/share/man/$f || { echo build-git: $pref/share/man/$f: Could not chdir, aborting >&2; exit 1; }
    pwd
    $sudo rm *
    $sudo ln -s ../../../prg/git/share/man/$f/* .
done
echo ================= svn commit the symlink =================
commitmsg=`echo build-git installed $globalgit on $(hostname); echo; suuid -t commit,build-git`
cd $pref/prg
echo -n Press Enter to commit the symlink...
read
$sudo svn ci -m "$commitmsg" git
