#!/bin/bash

#=======================================================================
# build-git
# File ID: 7075da30-98d2-11de-b3de-00248cd5cf1e
# (C)opyleft 2009 Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 3 or later
#=======================================================================

progname=build-git
lockdir=$HOME/.Build-git.LOCK

myexit() {
    rmdir $lockdir || echo $progname: $lockdir: Cannot remove lockdir >&2
    exit $1
}

trap "myexit 1" INT TERM
mkdir $lockdir || { echo $progname: $lockdir: Cannot create lockdir >&2; exit 1; }

rcfile=$HOME/.build-gitrc
# Directory where the git build happens
builddir=$HOME/src/other/git/build-git

# Prefix to directory tree where git will be installed. You can change it to 
# for example $HOME/local if you don’t have root access.
pref=/usr/local

# If you don’t have sudo rights or you don’t need it at the location in the 
# file system, clear the value of the $sudo variable
sudo=sudo

# Local name of remote master
local_master=master

# Name of remote master
remote_master=origin/master

# Set to 0 to skip ./configure and use Makefile in git.git instead
use_configure=1
configure_opts=

makeflags=
make_doc=1
make_info=1
hname=$(hostname)

[ -e $rcfile ] && . $rcfile
curr_git_ver=$(cd $builddir && (git tag | grep compiled-$hname-2 | tail -1) || echo UNKNOWN)

if [ -n "$1" ]; then
    local_master=$1
fi

echo
echo Variables:
echo
echo "curr_git_ver   = \"$curr_git_ver\""
echo "rcfile         = \"$rcfile\" ($([ -e $rcfile ] || echo -n "not ")found)"
echo "builddir       = \"$builddir\""
echo "pref           = \"$pref\""
echo "sudo           = \"$sudo\""
echo "local_master   = \"$local_master\""
echo "remote_master  = \"$remote_master\""
echo "makeflags      = \"$makeflags\""
echo "make_doc       = \"$make_doc\""
echo "make_info      = \"$make_info\""
echo "hname          = \"$hname\""
echo "use_configure  = \"$use_configure\""
echo "configure_opts = \"$configure_opts\""
echo

is_official_branch() {
    echo -n $1 | grep -Eq '^(master|maint|next|pu|todo)$' && return 0 || return 1
}

fetch_remotes() {
    git remote | grep -q '^origin$' || {
        echo $progname: The \"origin\" remote doesn\'t exist. Something is wrong here. >&2;
        myexit 1;
    }
    git remote | grep -q '^Spread$' || git remote add Spread sunny@git.sunbase.org:/home/sunny/Git-spread/git.git
    git remote | grep -q '^gitster$' || git remote add gitster git://github.com/gitster/git.git
    git remote | grep -q '^github$' || git remote add github git@github.com:sunny256/git.git
    git remote | grep -q '^sunbase$' || git remote add sunbase sunny@git.sunbase.org:/home/sunny/Git/git.git
    echo ================= git fetch =================
    echo ===== origin =====
    until git fetch origin; do
        echo $progname: Fetch error from origin, retrying >&2
        sleep 2
    done
    # git fetch --all arrived in v1.6.6, and that’s too recent to use.
    for f in $(git remote | grep -v '^origin$'); do
        echo ===== $f =====
        git fetch $f
    done
}

commit_tree() {
    git log --color --graph --pretty=format:'%Cred%h %Cblue%p%Creset -%C(yellow)%d%Creset %s %Cgreen(%cd %Cblue%an%Cgreen)%Creset' --abbrev-commit $1
}

push_changes() {
    is_official_branch $local_master && push_local= || push_local=$local_master
    echo ==== push changes to Spread ====
    git push -f Spread $push_local master maint next pu todo
    echo ==== push changes to github ====
    git push -f github $push_local master maint next pu todo
    echo ==== push changes to sunbase ====
    git push -f sunbase $push_local master maint next pu todo
    git push --tags sunbase
    echo ==== push finished ====
}

print_timestamp() {
    date +"%Y-%m-%d %H:%M:%S%z"
}

[ -z "`git --version | grep '^git version '`" ] && {
    echo $progname: You need to have git installed to use this script. >&2;
    myexit 1;
}

rmdir $builddir 2>/dev/null
if [ ! -d $builddir/. ]; then
    mkdir -p $builddir || {
        echo $progname: $builddir: Cannot create directory;
        myexit 1;
    }
    rmdir $builddir
    echo ================= git clone =================
    git clone git://git.kernel.org/pub/scm/git/git.git $builddir
    cd $builddir || { echo $progname: $builddir: Cannot chdir >&2; myexit 1; }
    fetch_remotes
fi
cd $builddir || { echo $progname: $builddir: Cannot chdir >&2; myexit 1; }
git checkout $local_master || { echo Cannot check out branch >&2; myexit 1; }
if [ ! -e GIT-VERSION-GEN ]; then
    # Paranoia check
    echo $progname: Didn’t find GIT-VERSION-GEN. That’s strange, aborting.
    myexit 1
fi
fetch_remotes
is_official_branch $local_master && destbranch=origin/$local_master || destbranch=$local_master
echo ================= New changes: $curr_git_ver..$destbranch =================
commit_tree $curr_git_ver..$destbranch | cat
echo
echo ================= git status in `pwd` =================
git status
echo
print_timestamp
unset choice
until [ "$choice" = "y" ]; do
    unset choice
    echo If that looks okay to you, press \'y\' to fetch newest git version
    echo and start the build, or:
    echo \'d\' to diff
    echo \'dw\' to word-diff
    echo \'l\' to list log
    echo \'n\' to abort
    echo \'t\' to show commit tree
    read choice
    [ "$choice" = "d" ] && git diff $curr_git_ver $destbranch
    [ "$choice" = "dw" ] && git diff --word-diff $curr_git_ver $destbranch
    [ "$choice" = "l" ] && git log --stat $curr_git_ver..$destbranch
    [ "$choice" = "n" ] && myexit 0
    [ "$choice" = "t" ] && commit_tree $curr_git_ver..$destbranch
done
echo ================= git clean =================
git clean -fxd
echo ================= Update all branches =================
git checkout $(git log -1 --format=%H) 2>/dev/null
for f in master maint next pu todo; do
    git branch -D $f
    git branch -t $f origin/$f
done
git checkout -f $local_master
vername=git.$local_master.`git describe --match 'v1*'`
dest=$pref/varprg/$vername
[ -d $dest/. ] && {
    echo; echo "Sorry, no new git(1) for you this time.";
    echo You’ll have to stick with `git --version` for now.;
    push_changes
    myexit 0;
}
push_changes
if [ "$use_configure" = "1" ]; then
    echo $progname: Creating ./configure
    make configure
    ./configure --prefix=$dest $configure_opts
fi
if [ "$make_doc" = "1" ]; then
    make_doc_str=doc
    inst_doc_str="install-doc install-html"
else
    make_doc_str=
    inst_doc_str=
fi
if [ "$make_info" = "1" ]; then
    make_info_str=info
    inst_info_str=install-info
else
    make_info_str=
    inst_info_str=
fi
echo Compiling $vername
echo ================= make $makeflags =================
make prefix=$dest $makeflags all $make_doc_str $make_info_str || myexit
echo ================= make test =================
make $makeflags test
echo
echo Ready to install $(./git --version) from branch \"$local_master\"
until test "$choice" = "y"; do
    echo
    print_timestamp
    echo -n If all tests succeeded, press y to continue...
    read choice
done
until $sudo echo Password OK | grep -q "Password OK"; do
    :
done
echo ================= $sudo make install =================
$sudo make prefix=$dest $makeflags install $inst_doc_str $inst_info_str
echo ================= make install finished =================
$sudo mkdir -p $pref/{bin,prg,varprg}
$sudo rm $pref/prg/git
$sudo ln -svf ../varprg/$vername $pref/prg/git
$sudo ln -sv /etc $pref/prg/git/etc
cd $pref/bin || {
    echo $progname: $pref/bin: Cannot chdir, aborting >&2;
    myexit 1;
}
$sudo ln -svf ../prg/git/bin/* .
echo ================= Check that the thing works =================
hash -r
localgit=`./git --version`
globalgit=`git --version`
if [ "$localgit" = "$globalgit" ]; then
    echo Congratulations with your shiny new $globalgit
    cd $builddir || { echo $progname: $builddir: Cannot chdir >&2; myexit 1; }
    git tag compiled-$hname-$(date -u +"%Y%m%dT%H%M%SZ")
    push_changes
else
    echo Uhm, something went wrong.
    echo Current version of git : $globalgit
    echo Expected version of git: $localgit
    myexit 1
fi
echo ================= symlink manpages =================
cd $pref/prg/git/share/man
mansects=`ls`
for f in $mansects; do
    $sudo mkdir -p $pref/share/man/$f
    cd $pref/share/man/$f || {
        echo $progname: $pref/share/man/$f: Could not chdir, aborting >&2;
        myexit 1;
    }
    pwd
    $sudo ln -sf ../../../prg/git/share/man/$f/* .
done
if [ -d $pref/.git/. ]; then
    echo ================= git commit the symlink =================
    commitmsg=`echo $progname installed $globalgit on $(hostname); echo; suuid -t commit,$progname`
    cd $pref/prg
    git add git
    echo Commit message:
    echo $commitmsg
    git commit -m "$commitmsg"
    git pa
fi

myexit 0
