#!/bin/bash

#=======================================================================
# build-perl
# File ID: e11bba20-382d-11e4-a75c-c80aa9e67bbd
#
# Compile and install Perl.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=build-perl
VERSION=0.1.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Compile and install Perl.

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

# FIXME: Get rid of hardcoded directories and username
# FIXME: Set up a common sync source for the build-* scripts

cd /home/sunny/src/other/perl || exit 1
export perldir="perl-$(git desc --long)"
export destdir="/usr/local/varprg/$perldir"
sudo rmdir $destdir 2>/dev/null
sudo mkdir $destdir &&
sudo chown sunny.sunny $destdir &&
git clean -fxd &&
git co -f &&
./Configure -de -Dusedevel -Dprefix=$destdir &&
make &&
make test &&
make install &&
cd /usr/local/prg &&
(test -L perl && sudo rm perl || true) &&
sudo ln -sv ../varprg/$perldir perl &&
cd ../varprg/$perldir/bin &&
(test -x perl || ln -sv perl5.* perl) &&
/usr/local/prg/perl/bin/perl --version ||
sudo rmdir $destdir
