#!/bin/bash

#=======================================================================
# build-git
# File ID: 7075da30-98d2-11de-b3de-00248cd5cf1e
#=======================================================================

builddir=$HOME/src/git/other/build-git

if [ ! -d $builddir/. ]; then
    mkdir -p $builddir || { echo build-git: $builddir: Cannot create directory; exit 1; }
    echo ================= git clone =================
    git clone git://git.kernel.org/pub/scm/git/git.git $builddir
fi
cd $builddir || { echo build-git: $builddir: Cannot chdir >&2; exit 1; }
if [ ! -e GIT-VERSION-GEN ]; then
    # Paranoia check
    echo build-git: Didn’t find GIT-VERSION-GEN. That’s incredibly strange, aborting.
    exit 1
fi
echo ================= git clean =================
git clean -fxd
git checkout -f master
echo ================= git fetch =================
git fetch
echo ================= git merge origin/master =================
git merge origin/master
vername=git.master-`git describe --abbrev=20`
dest=/usr/local/varprg/$vername
[ -d $dest/. ] && { echo $vername is already installed, you lucky bastard.; exit 0; }
echo Compiling $vername
echo ================= make =================
make prefix=/usr/local/varprg/$vername all doc info || exit
echo ================= sudo make install =================
sudo make prefix=/usr/local/varprg/$vername install install-doc install-html install-info
echo ================= make install finished =================
sudo rm /usr/local/prg/git
sudo ln -svf ../varprg/$vername /usr/local/prg/git
echo ================= Check that the thing works =================
localgit=`./git --version`
globalgit=`git --version`
if [ "$localgit" = "$globalgit" ]; then
    echo Congratulations with your shiny new $globalgit
else
    echo Uhm, something went wrong.
    echo Current version of git : $globalgit
    echo Expected version of git: $localgit
    exit 1
fi
echo ================= svn commit the symlink =================
commitmsg=`echo build-git installed $globalgit on $(hostname); echo; suuid -t commit,build-git`
cd /usr/local/prg
sudo svn ci -m "$commitmsg" git
