#!/bin/sh

#==============================================================================
# capsoff
# File ID: 169c2dd8-deaa-11e9-8bde-4f45262dc9b5
# Author: Øyvind A. Holm <sunny@sunbase.org>
#==============================================================================

progname=capsoff
VERSION=0.1.0

if test "$1" = "-h" -o "$1" = "--help"; then
	cat <<END

Disable Caps Lock and Num Lock in X.

Usage: $progname [-h|--help]

Options:

  -h, --help
    Show this help.

END
	exit 0
fi

setxkbmap -option caps:none
xmodmap -e "keycode 77 = "

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
