#!/bin/sh

# $Id: cdiff,v 1.5 2003/11/09 17:49:27 sunny Exp $
# Latskapen lenge leve.

if [ "$1" = "-s" ]; then
	cvs -n diff -u $* 2>/dev/null | less -S | egrep '^[+\-]'
else
	cvs -n diff -u $* 2>/dev/null | less -S
fi
