#!/bin/sh

# $Id$
# Latskapen lenge leve. Funker på samme måten som cdiff,
# men driter i whitespace.

if [ -d .svn/. ]; then
	if [ "$1" = "-s" ]; then
		shift
		svn diff --diff-cmd diff -x -ub $* 2>/dev/null | grep -v '^\? ' | egrep '^[+\-]' | less -S
	else
		svn diff --diff-cmd diff -x -ub $* 2>/dev/null | grep -v '^\? ' | less -S
	fi
else
	if [ "$1" = "-s" ]; then
		shift
		cvs -n diff -ub $* 2>/dev/null | grep -v '^\? ' | egrep '^[+\-]' | less -S
	else
		cvs -n diff -ub $* 2>/dev/null | grep -v '^\? ' | less -S
	fi
fi
