#!/bin/bash

# $Id$
# Latskapen lenge leve.

if [ -d .svn/. ]; then
	if [ "$1" = "-s" ]; then
		shift
		svn diff $* 2>/dev/null | egrep '^[+\-]' | less -S
	else
		svn diff $* 2>/dev/null | less -S
	fi
else
	if [ "$1" = "-s" ]; then
		shift
		cvs -n diff -u $* 2>/dev/null | egrep '^[+\-]' | less -S
	else
		cvs -n diff -u $* 2>/dev/null | less -S
	fi
fi
