#!/bin/sh

# cdiffb
# File ID: 8966d5d2-08de-11de-bfaa-000475e441b9
# Latskapen lenge leve. Funker på samme måten som cdiff,
# men driter i whitespace.

if [ -d .svn/. ]; then
	if [ "$1" = "-s" ]; then
		shift
		svn diff -x -uw $* 2>/dev/null | grep -v '^\? ' | egrep '^[+\-]' | less -S
	else
		svn diff -x -uw $* 2>/dev/null | grep -v '^\? ' | less -S
	fi
else
	if [ "$1" = "-s" ]; then
		shift
		cvs -n diff -ub $* 2>/dev/null | grep -v '^\? ' | egrep '^[+\-]' | less -S
	else
		cvs -n diff -ub $* 2>/dev/null | grep -v '^\? ' | less -S
	fi
fi
