#!/bin/sh

# $Id: cdlabel,v 1.3 2002/12/02 09:37:50 sunny Exp $
# Skriver ut volume label på CDROM'en som står i.

# Først tar vi en fake read for å unngå error
until head -c 1 /dev/cdrom >/dev/null; do
	:
done

head -c 32840 /dev/cdrom | tail -c 32 | rmspcbak
