#!/usr/bin/perl -w

# cfold
# File ID: 602c35c8-5d37-11df-a51d-90e6ba3022ac
# Inserts fold marks in C source before and after stdin.
# Select text in visual line mode and filter the block through this script.

use strict;

$| = 1;

my $Line = <STDIN>;
my ($Indent, $Title) = ("", "");

defined($ARGV[0]) && ($Title = join(" ", @ARGV) . " ");
$Line =~ /^(\s+)/ && ($Indent = $1);
print("$Indent/* $Title\x7B\x7B\x7B */\n$Line");

while (<STDIN>) {
	print($_);
}

print("$Indent/* \x7D\x7D\x7D */\n");
