#!/usr/bin/perl -w

# $Id: charconv,v 1.1 2000/12/07 00:40:43 sunny Exp $
# Konverterer fra cp865 til Unicode. Alternativ konverteringsfil
# spesifiseres med "-i"-parameteret, ellers brukes default filnavn.
# -p skriver ut en enkel HTML-header og -slutt.

use strict;
require 'getopts.pl';

my $map_file = "/home/sunny/src/cvs/ibm2ent/cp865.txt";
my %Table;

Getopts('hi:p');
defined($main::opt_i) && ($map_file = $main::opt_i);

open(MapFP, "<$map_file") || die("$map_file: Can't open map file: $!");

while (<MapFP>) {
	/^#/ && next;
	if (/^0x(..)\s+0x(....)/) {
		my ($Cp, $Uni, $Name) = (hex($1), hex($2));
		if ($Cp != $Uni) {
			$Table{chr($Cp)} = "&#$Uni;";
		}
	} else {
		print STDERR "Line $.: Invalid line: \"$_\"\n";
	}
}

print("<html><head></head><body><pre>\n") if $main::opt_p;

while(<>) {
	s/&/&amp;/g;
	s/</&lt;/g;
	s/>/&gt;/g;
	s/([\x80-\xff])/$Table{$1}/g;
	print;
}

print("</pre></body></html>\n") if $main::opt_p;

#### End of file $Id: charconv,v 1.1 2000/12/07 00:40:43 sunny Exp $ ####
