#!/bin/bash

#=======================================================================
# File ID: dd770008-300f-11df-b5fc-90e6ba3022ac
# License: GNU General Public License version 3 or later.
#=======================================================================

test "$1" = "-d" && {
    test "$(git config --get ciall.noemptydirs)" = "true" && { echo ciall: -d option not allowed here >&2; exit 1; }
    shift;
    echo -n ciall: Executing git-store-dirs... >&2
    git store-dirs || {
        echo git-store-dirs error >&2;
        exit 1;
    }
    echo DONE >&2
}
echo ciall: git status 1... >&2
LC_ALL=C git status | grep "^nothing to commit" && { echo ciall: Nothing to do here.; exit 0; }

unset logmsg
[ ! -z "$1" ] && logmsg="$*"

echo ciall: git status 2... >&2
git status
echo
echo "Log message: '$logmsg'"
until test "$besafe" = "y"; do
    echo -n Press \'y\' + Enter to commit all new changes or \'n\' to abort...
    read besafe
    test "$besafe" = "n" && exit 0;
done

if [ "$logmsg" = "--" ]; then
    tmpmsgfile=/tmp/$(date +%s)-$$.tmp
    $EDITOR $tmpmsgfile
    logmsg=$(cat $tmpmsgfile)
    test -z "$logmsg" && { echo ciall: No text entered in editor, aborting.; exit 1; }
fi

echo ciall: git status 3... >&2
LC_ALL=C git status | grep "^nothing to commit" || (git add --all . && git commit -m "$logmsg`echo; echo; suuid -t ciall -c "$logmsg"`")
echo ========== git status ==========
git status
exit 0
