#!/bin/bash

#=======================================================================
# File ID: dd770008-300f-11df-b5fc-90e6ba3022ac
# License: GNU General Public License version 3 or later.
#=======================================================================

test "$1" = "-d" && {
    shift;
    git store-dirs || {
        echo ciall: git-store-dirs error >&2;
        exit 1;
    }
}
LC_ALL=C git status | grep "^nothing to commit" && { echo ciall: Nothing to do here.; exit 0; }

git status
echo
until test "$besafe" = "y"; do
    echo -n Press \'y\' + Enter to commit all new changes or \'n\' to abort...
    read besafe
    test "$besafe" = "n" && exit 0;
done

unset logmsg
[ ! -z "$1" ] && logmsg="$*"

if [ "$logmsg" = "--" ]; then
    tmpmsgfile=/tmp/$(date +%s)-$$.tmp
    $EDITOR $tmpmsgfile
    logmsg=$(cat $tmpmsgfile)
    test -z "$logmsg" && { echo ciall: No text entered in editor, aborting.; exit 1; }
fi

LC_ALL=C git status | grep "^nothing to commit" || (git add . && git commit -a -m "$logmsg`echo; echo; suuid -t ciall -c "$logmsg"`")
echo ========== git status ==========
git status
