#!/usr/bin/perl

# Kommenterer ut linjer. Dødsavansert.
# $Id: commout,v 1.4 1999/07/05 15:00:51 sunny Exp $

if ($#ARGV > -1) {
	$comm_pattern = $ARGV[0];
} else {
	$comm_pattern = '#';
}

while (<STDIN>) {
	s/^(\t*)/$1$comm_pattern /;
	print;
}
