#!/usr/bin/perl -w

#=======================================================================
# $Id$
# Configures, compiles and installs new groovy Subversion from the 
# repository at svn.collab.net .
#
# Character set: UTF-8
# License: GNU General Public License ♡
# ©opyleft 2004 Øyvind A. Holm <sunny@sunbase.org>
#=======================================================================

use strict;

$| = 1;

use Getopt::Std;
our ($opt_h) = (0);
getopts('h') || die("Option error. Use -h for help.\n");

$opt_h && usage(0);

die("Unfinished.\n");

my $svn_base = "$ENV{HOME}/src/other/subversion";
my $svn_clean = "$ENV{HOME}/src/other/subversioni/1.1.x.clean";

unless (chdir($svn_clean)) {
	warn("$svn_clean: Directory not found, installing newest svn-1.x.x .\n");
	mkpath($svn_base, 1);
	unless (chdir($svn_base)) {
		die("chdir($svn_base): $!");
	}
	my_system("svn co http://svn.collab.net/repos/svn/branches/1.1.x 1.1.x.clean");
}

unless (chdir($svn_clean)) {
	die("chdir($svn_clean): $!");
}

my_system("svn up");

my $Revnum = "";

if (open(PipeFP, "svn info|")) {
	while(<PipeFP>) {
		# FIXME: Pussyble i18n stuff fucking up grepping here
		if (/^Revision: (\d+)$/) {
			$Revnum = $1;
			last;
		}
	}
	length($Revnum) || die("$svn_clean: Revision number not found in directory: $!");
}

my $dest_dir = "$svn_base/subversion-1.1.x.r$Revnum";


sub ERR {
	my $Cmd = shift;
	print("== Running \"$Cmd\"...\n");
	return($Cmd || die("$Cmd: $!"));
}

sub my_system {
	my $Cmd = shift;
	print("==== Executing system(\"$Cmd\")...\n");
	return(system($Cmd));
}

sub usage {
	# Send the help message to stdout {{{
	my $Retval = shift;
	print(<<END);

Usage:

END
	exit($Retval);
	# }}}
}

__END__

# Plain Old Documentation (POD) {{{

=pod

=head1 NAME



=head1 REVISION

$Id$

=head1 SYNOPSIS



=head1 DESCRIPTION



=head1 OPTIONS

=over 4

=item B<-h>

Print a brief help summary.

=back

=head1 BUGS



=head1 AUTHOR

Made by Øyvind A. Holm S<E<lt>sunny _AT_ sunbase.orgE<gt>>.

=head1 COPYRIGHT

Copyleft © Øyvind A. Holm &lt;sunny@sunbase.org&gt;
This is free software; see the file F<COPYING> for legalese stuff.

=head1 LICENCE

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

=head1 SEE ALSO

=cut

# }}}

# vim: set fileencoding=UTF-8 filetype=perl foldmethod=marker foldlevel=0 :
# End of file $Id$
