#!/bin/bash

#=======================================================================
# create-git-remotes
# File ID: 39dece1e-dd8b-11e0-a610-e19f4065fc81
# Temporary script to update git.git remotes while kernel.org is down
# License: GNU General Public License version 3 or later.
#=======================================================================

git remote set-url origin    git://repo.or.cz/alt-git.git
git remote add o-github      https://github.com/gitster/git.git
git remote add o-googlecode  https://code.google.com/p/git-core/
git remote add o-repoorcz    git://repo.or.cz/alt-git.git
git remote add o-sfnet       git://git-core.git.sourceforge.net/gitroot/git-core/git-core
git remote add o-sfnet-jp    git://git.sourceforge.jp/gitroot/git-core/git.git
