#!/usr/bin/env bash

#=======================================================================
# create_cproject
# File ID: 0aa2560c-8683-11e0-bc0d-00023faf1383
#
# Create skeleton for new C project
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=create_cproject
VERSION=0.3.1

ARGS="$(getopt -o "\
c\
h\
q\
v\
" -l "\
copying,\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_copying=0
opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        -c|--copying) opt_copying=1; shift ;;
        -h|--help) opt_help=1; shift ;;
        -q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        -v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        --version) echo $progname $VERSION; exit 0 ;;
        --) shift; break ;;
        *) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Create skeleton for a new C project in the current directory where the 
main .c file is called PROJECT_NAME.c.

Usage: $progname [options] PROJECT_NAME

Options:

  -c, --copying
    Also create a COPYING file with the current license.
  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

name=$1
test -z "$name" && { echo $progname: Name not specified as arg 1 >&2; exit 1; }
echo -n "Makefile: "; std -t exec=$name c/Makefile Makefile
echo -n "$name.c: "; std -t exec=$name c/std.c $name.c
echo -n "$name.h: "; std -t exec=$name c/std.h $name.h
if test "$opt_copying" = "1"; then
    echo -n "COPYING: "; std COPYING COPYING && echo OK || echo ERROR
fi
