#!/bin/sh

# cunw
# File ID: d3b3f684-5d37-11df-854d-90e6ba3022ac
# Lister ut alle filer som ikke er registrert i CVS (Cvs-UNWanted)

# BUGS: Avhengig av utskriftsformatet til cvs(1)

(cvs -n stat `find . -type d | grep -v -e 'CVS$' -e '\.AFV'` >/dev/null) 2>&1 | grep -v -e '^cvs status: Examining ' -e '^cvs server: Examining '
(cvs -n stat `find . -type f | grep -v -e '\.AFV' -e 'CVS/Entries' -e 'CVS/Repository$' -e 'CVS/Root$' -e 'CVS/Tag$' ` >/dev/null) 2>&1
