#!/bin/sh

# $Id: cunw,v 1.4 1999/05/28 18:12:53 sunny Exp $
# Lister ut alle filer som ikke er registrert i CVS (Cvs-UNWanted)

# BUGS: Avhengig av utskriftsformatet til cvs(1)

(cvs -n stat `find . -type d | grep -v 'CVS$'` >/dev/null) 2>&1 | grep -v '^cvs status: Examining '
(cvs -n stat `find . -type f | grep -v -e 'CVS/Entries$' -e 'CVS/Repository$' -e 'CVS/Root$' ` >/dev/null) 2>&1
