#!/bin/bash

#=======================================================================
# cvs-rev
# File ID: aae12904-f742-11dd-a971-000475e441b9
# Lister ut alle cvs2svn:cvs-rev fra et element i en svn-repo.
# License: GNU General Public License version 3 or later.
#=======================================================================

dest=$1
rev=$2
if [ -z "$rev" ]; then
    rev=1:HEAD
fi

for f in `svnrevs -r$rev $dest | tr -d r,`; do
    echo r$f `svn pl -v -r$f $dest | grep cvs2svn`
done
