#!/bin/sh

# cvs-editor
# File ID: dcfd2742-5d37-11df-ba3d-90e6ba3022ac

if [ "`whoami`" = "root" -o ! -e /usr/local/bin/gvim ]; then
	vim -X -f -c "set ft=svncommit" $*
else
	vim -X -f -c "set ft=svncommit" $*
fi
