#!/bin/bash

# cvscat
# File ID: e1b60c7c-5d37-11df-b6cd-90e6ba3022ac

if [ $# -le 1 ]; then
	cat <<END

Syntax: cvscat file revision [cvs options]

END
	exit 1
fi

cvsfile=$1
shift
revision=$1
shift

cvs -d $(cat CVS/Root) co -p -r $revision $* $(cat CVS/Repository)/$cvsfile
