#!/bin/sh

# $Id: cvsrootmd5,v 1.1 2001/05/07 01:11:10 sunny Exp $
# Lagrer md5sum o.l. av cvsroot. Paranoia.

cfil=/home/sunny/src/cvs/p/cvsroot.md5
[ -d /home/sunny/cvsroot ] || { echo $0: Fant ikke cvsroot >&2; exit 1; }
pushd /home/sunny/cvsroot >/dev/null
datestr="$(date +"%Y-%m-%d %H:%M:%S %s") $(hostname)"
echo $datestr >$cfil
echo >>$cfil
find -printf "%TY-%Tm-%Td %TH:%TM:%TS %8s %p\n" | sort -k4 >>$cfil
echo >>$cfil
find -type f -print0 | sort -z | xargs -0 md5sum >>$cfil
echo '$Id: cvsrootmd5,v 1.1 2001/05/07 01:11:10 sunny Exp $' >$cfil.tmp
gpg --clearsign <$cfil >>$cfil.tmp || { echo $0: Feil under signering >&2; exit 1; }
mv $cfil.tmp $cfil
cd /home/sunny/src/cvs/p
cvs ci -m "$datestr" cvsroot.md5
popd >/dev/null
