#!/bin/bash

#==================================================
# $Id: cvsssh,v 1.5 2003/07/25 03:29:22 sunny Exp $
# Bestemmer hvilken ssh som skal kjøres med CVS.
# Beregnet for bruk på ww først og fremst.
# Ihvertfall foreløpig.
#==================================================

# cmd=ssh

# /bin/pwd | grep -e ^/home/badata/src/cvs -e ^/home/sunny/dbk -e /home/badata/Stable >/dev/null && cmd=sunbassh
# /bin/pwd | grep -e ^/home/badata/Stable/net >/dev/null && cmd=ssh

# /bin/pwd | grep -e ^/home/sunny/p/dbk >/dev/null && cmd=sunbassh

cmd=sunbassh

$cmd $*
