#!/bin/bash

#=======================================================================
# $Id$
# [Description]
#=======================================================================

echo -e ==================== `utc -L` - START DOWNLOAD \{\{\{ ====================
cd ~/dl/beatles/
rm -f beatles_komplett.rss
wget http://podkast.nrk.no/program/beatles_komplett.rss
for f in `urlstrip beatles_komplett.rss | grep -i 'mp3$'`; do
    wget -nc $f
done
echo -e ==================== `utc -L` - END DOWNLOAD \}\}\} ====================
