#!/bin/bash

#=======================================================================
# dass
# File ID: e71b5fc8-31d0-11e5-a8b5-fefdb24f8e10
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

