#!/usr/bin/perl

# Ny versjon av DBK-systemet.
# $Id: dbk,v 1.4 1999/05/05 00:39:46 sunny Exp $

use Time::Local;

$Debug = 0;

print("\$#ARGV = $#ARGV\n") if $Debug;

$Editor = "joe -wordwrap +9999";
$Editor_t = "joe -wordwrap +9999";
$Viewer = "lynx";
$dbk_dir = "$ENV{HOME}/dbk";
$dbk_ext = ".html";
$dir_mode = 0770;

$curr_time = time;
$opt_t = 0; # Legger til klokkeslettet på en egen linje
$opt_h = 0; # Skriver ut hjelpen
$opt_v = 0; # Viser dokumentet i lynx(1) eller hva man nå måtte bruke
@day_name = ("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat");

require 'getopts.pl';
&Getopts('htv');

&print_help if $opt_h;

print("$0: \$opt_t = $opt_t\n") if $Debug;

($Sec, $Min, $Hour, $Day, $Mon, $Year, $Wday, $Yday, $is_dst) = localtime($curr_time);

$Year += 1900;
$Mon += 1;

print("\$curr_time: $Year-$Mon-$Day $Hour:$Min:$Sec, \$Wday = $Wday, \$Yday = $Yday, \$is_dst = $is_dst\n") if $Debug;

$Year = $ARGV[2] if $#ARGV >= 2;
$Mon = sprintf("%02u", $ARGV[1]) if $#ARGV >= 1;
$Day = sprintf("%02u", $ARGV[0]) if $#ARGV >= 0;

$Year += 1900 if ($Year < 100); # Heia år 2000, vi gleder oss.
$Mon =~ s/^(\d)$/0$1/;
$Day =~ s/^(\d)$/0$1/;
$Hour =~ s/^(\d)$/0$1/;
$Min =~ s/^(\d)$/0$1/;
$Sec =~ s/^(\d)$/0$1/;

die("$0: $Day: Feil format på datoen\n") unless ($Day =~ /^\d\d$/);
die("$0: $Mon: Feil format på måneden\n") unless ($Mon =~ /^\d\d$/);
die("$0: $Year: Feil format på året\n") unless ($Year =~ /^\d\d\d\d$/);

$time_utc = timegm($Sec, $Min, $Hour, $Day, $Mon-1, $Year);
$time_sec = timelocal($Sec, $Min, $Hour, $Day, $Mon-1, $Year);
@time_arr = localtime($time_sec);
$week_day = $time_arr[6];
$utc_diff = ($time_utc-$time_sec)/3600;

print("Etter ARGV: $Year-$Mon-$Day\n") if $Debug;
print("\$dbk_dir = $dbk_dir\n") if $Debug;

# Sjekk at alle directories er på plass

$year_dir = "$dbk_dir/$Year";
$dbk_file = "$year_dir/${Year}${Mon}${Day}${dbk_ext}";

umask(0);
unless (-d $dbk_dir) {
	mkdir($dbk_dir, $dir_mode) || die("$0: $dbk_dir: Kan ikke lage directoryen: $!\n");
}
unless (-d $year_dir) {
	mkdir($year_dir, $dir_mode) || die("$0: $year_dir: Kan ikke lage directoryen: $!\n");
}

print("\$dbk_file = $dbk_file\n") if $Debug;

unless (-f $dbk_file) {
	open(FP, ">$dbk_file") || die("$0: $dbk_file: Kan ikke åpne fila for skriving: $!\n");
	print(FP "<h1>$day_name[$week_day] $Year-$Mon-$Day</h1>\n") || die("$0: $dbk_file: Kan ikke skrive header til fila: $!\n");
	close(FP);
}

if ($opt_t) {
	$utc_str = sprintf("%s%02u00", $utc_diff < 0 ? "-" : "+", $utc_diff);
	open(FP, ">>$dbk_file") || die("$0: $dbk_file: Kan ikke åpne fila for append: $!\n");
	print(FP "\n<p><b>$Hour:$Min:$Sec$utc_str</b> - ") || die("$0: $dbk_file: Klarte ikke å skrive til fila: $!\n");
	close(FP);
	system("$Editor_t $dbk_file");
	$min_size = 50;
} else {
	system("$Editor $dbk_file");
	$min_size = 25;
}

@stat_info = stat($dbk_file);
$file_size = $stat_info[7];
if ($file_size < $min_size) {
	print("Ingenting ble skrevet, så jeg sletter driten.\n");
	unlink($dbk_file) || die("$0: $dbk_file: Klarte ikke å slette fila: $!\n");
} else {
	system("$Viewer $dbk_file") if $opt_v;
}

exit(0);

#### SUBRUTINER ####

sub print_help {
	print <<END;

Syntax: $0 [valg] [dag [måned [år]]]

Disse valgene (options) kan brukes:

-h  Skriv denne hjelpen
-t  Legg til klokkeslett i fila
-v  Vis dokumentet i en browser etter editering

END
	exit(0);
}

__END__

#### End of file $Id: dbk,v 1.4 1999/05/05 00:39:46 sunny Exp $ ####
