#!/usr/bin/perl

# Ny versjon av DBK-systemet.
# $Id: dbk,v 1.10 2000/04/22 15:55:38 sunny Exp $
#
# (C)opyleft Øyvind A. Holm <sunny256@mail.com>
# GNU-lisens.

use Time::Local;
use Fcntl ':flock';

$Debug = 0;

print("\$#ARGV = $#ARGV\n") if $Debug;

$Editor = "joe";
$dbk_dir = "$ENV{HOME}/dbk";
$Viewer = "lynx -homepage=file://$dbk_dir";
$dbk_ext = ".html";
$dir_mode = 0770;

$curr_time = time;
$opt_t = 0; # Legger til klokkeslettet på en egen linje
$opt_h = 0; # Skriver ut hjelpen
$time_not_found = 0;
@day_name = ("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat");

require 'getopts.pl';
&Getopts('bhi:t');

&print_help(0) if $opt_h;

print("$0: \$opt_t = $opt_t\n") if $Debug;

($Sec, $Min, $Hour, $Day, $Mon, $Year, $Wday, $Yday, $is_dst) = localtime($curr_time);

$Year += 1900;
$Mon += 1;

print("\$curr_time: $Year-$Mon-$Day $Hour:$Min:$Sec, \$Wday = $Wday, \$Yday = $Yday, \$is_dst = $is_dst\n") if $Debug;

my $arg_count;

# Begynnelse på parameterparsing.
# begin-base64 664 -
# H4sIAKCL/DgCA1MrSCwqTo1PLEov1nBwDHIP07Tm4iouTVJAiCtUc3HmVio4
# OILYtgoO8dZgvkpKfFp+aV4KUMgAKMLFmZZflJqYnKEBVqgJ0pWZpqChH6db
# oqIP5nKCRIACMSkxKVZQIZWSzNzU+OKSIqAxKiCTaxVSc4pBGkFGAlEtV62C
# MpJrNDS5AP7tzhO0AAAA
# ====

foreach(@ARGV) {
	/^\d\d:/ && (splice(@ARGV, $arg_count, 1), $time_str = $_, $opt_t = 1);
	$arg_count++;
}

$Year = $ARGV[2] if $#ARGV >= 2;
$Mon = sprintf("%02u", $ARGV[1]) if $#ARGV >= 1;
$Day = sprintf("%02u", $ARGV[0]) if $#ARGV >= 0;

# Når vi nærmer oss 2030 begynner dette å bli en fixme. :)
if ($Year < 30) {
	$Year += 2000;
} elsif ($Year < 100) {
	$Year += 1900;
}

$Mon =~ s/^(\d)$/0$1/;
$Day =~ s/^(\d)$/0$1/;
$Hour =~ s/^(\d)$/0$1/;
$Min =~ s/^(\d)$/0$1/;
$Sec =~ s/^(\d)$/0$1/;

die("$0: $Day: Feil format på datoen\n") unless ($Day =~ /^\d\d$/);
die("$0: $Mon: Feil format på måneden\n") unless ($Mon =~ /^\d\d$/);
die("$0: $Year: Feil format på året\n") unless ($Year =~ /^\d\d\d\d$/);

$time_utc = timegm($Sec, $Min, $Hour, $Day, $Mon-1, $Year);
$time_sec = timelocal($Sec, $Min, $Hour, $Day, $Mon-1, $Year);
@time_arr = localtime($time_sec);
$week_day = $time_arr[6];
$utc_diff = ($time_utc-$time_sec)/3600;

print("Etter ARGV: $Year-$Mon-$Day\n") if $Debug;
print("\$dbk_dir = $dbk_dir\n") if $Debug;
print("\$opt_i = \"$opt_i\"\n") if $Debug;;

# Sjekk at alle directories er på plass

$year_dir = "$dbk_dir/$Year";
$dbk_file = "$year_dir/${Year}${Mon}${Day}${dbk_ext}";

umask(0);
unless (-d $dbk_dir) {
	mkdir($dbk_dir, $dir_mode) || die("$0: $dbk_dir: Kan ikke lage directoryen: $!\n");
}
unless (-d $year_dir) {
	mkdir($year_dir, $dir_mode) || die("$0: $year_dir: Kan ikke lage directoryen: $!\n");
}

print("\$dbk_file = $dbk_file\n") if $Debug;

unless (-f $dbk_file) {
	open(FP, ">$dbk_file") || die("$0: $dbk_file: Kan ikke åpne fila for skriving: $!\n");
	print(FP "<h1>$day_name[$week_day] $Year-$Mon-$Day</h1>\n") || die("$0: $dbk_file: Kan ikke skrive header til fila: $!\n");
	close(FP);
}

if ($opt_t) {
	$utc_str = sprintf("%s%02u00", $utc_diff < 0 ? "-" : "+", $utc_diff);
	if (length($time_str)) {
		$time_str .= $utc_str;
	} else {
		$time_str = "$Hour:$Min:$Sec$utc_str";
	}
	open(dbkFP, "+<$dbk_file") || die("$0: $dbk_file: Kan ikke åpne fila for lesing+skriving+flock: $!\n");
	flock(dbkFP, LOCK_EX) || die("$0: $dbk_file: Klarte ikke flock(): $!\n");
	$which_line = &find_line($time_str);
	if ($time_not_found) {
		seek(dbkFP, 0, 2) || die("$dbk_file: Klarte ikke å seeke til slutten for å legge til LF: $!\n");
		print(dbkFP "\n");
		$which_line++;
	}
	length($opt_i) ? &insert_file($opt_i, $which_line) : &insert_time($time_str, $which_line);
	close(dbkFP);
	$which_line++;
	# $which_line++ if $time_not_found;
	system("$Editor +$which_line $dbk_file") unless (length($opt_i) || length($opt_b));
	$min_size = 49;
} else {
	$min_size = 25;
}

unless ($opt_b) {
	system("$Viewer $dbk_file");
	system("clear");
}

@stat_info = stat($dbk_file);
$file_size = $stat_info[7];
if ($file_size < $min_size) {
	print("Ingenting ble skrevet, så jeg sletter driten.\n");
	unlink($dbk_file) || die("$0: $dbk_file: Klarte ikke å slette fila: $!\n");
	rmdir($year_dir);
}

exit(0);

#### SUBRUTINER ####

sub find_line {
	my $srch_time = shift;
	my $last_line = 0;
	my $Found = 0;
	seek(dbkFP, 0, 0) || die("$dbk_file: Klarte ikke å gå til begynnelsen av fila: $!\n");
	while (<dbkFP>) {
		if (/^<p><b>(\d\d:\d\d:\d\d)/i || /^<p><b>(\d\d:\d\d)/i) {
			my $found_time = $1;
			return($.) if ($srch_time lt $found_time);
		}
	}
	$time_not_found = 1;
	return($.+1);
} # find_line()

sub insert_time {
	my ($time_str, $line_num) = @_;
	seek(dbkFP, 0, 0) || die("$dbk_file: Klarte ikke å gå til begynnelsen av fila i insert_time(): $!\n");
	my @Linjer = <dbkFP>;
	splice(@Linjer, $line_num-1, 0, sprintf("<p><b>$time_str</b> -\n%s", $time_not_found ? "" : "\n"));
	seek(dbkFP, 0, 0) || die("$dbk_file: Klarte ikke å seeke til starten i insert_time(): $!\n");
	truncate(dbkFP, 0) || die("$dbk_file: Klarte ikke å trunce fila til 0: $!\n");
	foreach(@Linjer) {
		print(dbkFP $_);
	}
} # insert_time()

sub insert_file {
	my ($file_name, $line_num) = @_;
	local *LocFP;
	seek(dbkFP, 0, 0) || die("$dbk_file: Klarte ikke å gå til begynnelsen av fila i insert_file(): $!\n");
	my @Linjer = <dbkFP>;
	my @InsLinj = "<p><b>$time_str</b> -\n";
	open(LocFP, "<$file_name") || die("$file_name: Kan ikke åpne fila for lesing: $!\n");
	push(@InsLinj, <LocFP>);
	push(@InsLinj, "\n") unless $time_not_found; # Denne likte jeg egentlig fantastisk dårlig, men hvem bruker vel å ha to LF'er på slutten av fila?
	splice(@Linjer, $line_num-1, 0, @InsLinj);
	close(LocFP);
	seek(dbkFP, 0, 0) || die("$dbk_file: Klarte ikke å seeke til starten i insert_file(): $!\n");
	truncate(dbkFP, 0) || die("$dbk_file: Klarte ikke å trunce fila til 0: $!\n");
	foreach(@Linjer) {
		print(dbkFP $_);
	}
} # insert_file()

sub print_help {
	my $Retval = shift;
	print <<END;

Syntax: $0 [valg] [dag [måned [år]]] [HH:MM]

Disse valgene (options) kan brukes:

-b      Batch mode, ikke start editor eller viewer.
-h      Skriv denne hjelpen
-i x  - Sett inn filen x istedenfor å bruke tastatur.
        Forventer -t eller klokkeslett.
-t      Legg til klokkeslettet akkurat i fila og går inn i editoren

Klokkeslettet kan spesifiseres hvor som helst, men må starte med formatet
"HH:" der HH er to siffer.

END
	exit($Retval);
} # print_help()

__END__

#### End of file $Id: dbk,v 1.10 2000/04/22 15:55:38 sunny Exp $ ####
