#!/usr/bin/perl -w

#==================================================
# dbllf
# File ID: 3c283716-5d38-11df-b62c-90e6ba3022ac
# Dobler LF så enkelte ting blir mer oversiktlig
#==================================================

use strict;

$| = 1;

while (<>) {
	s/\n/\n\n/g;
	print;
}

__END__

# End of file dbllf
