#!/usr/bin/perl -w

#==================================================
# $Id: dbllf,v 1.2 2004/04/19 12:55:08 sunny Exp $
# Dobler LF så enkelte ting blir mer oversiktlig
#==================================================

use strict;

$| = 1;

while (<>) {
	s/\n/\n\n/g;
	print;
}

__END__

# End of file $Id: dbllf,v 1.2 2004/04/19 12:55:08 sunny Exp $
