#!/usr/bin/perl -w

#==================================================
# $Id$
# Dobler LF så enkelte ting blir mer oversiktlig
#==================================================

use strict;

$| = 1;

while (<>) {
	s/\n/\n\n/g;
	print;
}

__END__

# End of file $Id$
