#!/usr/bin/perl -w

# deep
# File ID: 48bdd3dc-5d38-11df-9f9a-90e6ba3022ac
# Omvendt av ep(1).

use strict;
use Time::Local;

while(<>) {
	s/(\d\d\d\d)[\-\/]?(\d\d)[\-\/]?(\d\d)[T ](\d\d):?(\d\d):?(\d\d)Z/sprintf("%s", timegm($6, $5, $4, $3, $2-1, $1))/ge;
	s/(\d\d\d\d)[\-\/]?(\d\d)[\-\/]?(\d\d)[T ](\d\d):?(\d\d):?(\d\d)/sprintf("%s", timelocal($6, $5, $4, $3, $2-1, $1))/ge;
	print;
}
