#!/usr/bin/perl -w

# $Id: deep,v 1.2 2003/09/26 02:08:08 sunny Exp $
# Omvendt av ep(1).

use strict;
use Time::Local;

while(<>) {
	s/(\d\d\d\d)[\-\/]?(\d\d)[\-\/]?(\d\d)[T ](\d\d):?(\d\d):?(\d\d)Z/sprintf("%s", timegm($6, $5, $4, $3, $2-1, $1))/ge;
	s/(\d\d\d\d)[\-\/]?(\d\d)[\-\/]?(\d\d)[T ](\d\d):?(\d\d):?(\d\d)/sprintf("%s", timelocal($6, $5, $4, $3, $2-1, $1))/ge;
	print;
}
