#!/bin/bash

#=======================================================================
# dir-elems
# File ID: 6a061bba-0014-11e5-8931-0d8802d731e4
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

