#!/bin/sh

# File ID: 1fcb061a-fa4e-11e6-8927-f74d993421b0

progname=disable_ipv6
rcfile="$HOME/.${progname}rc"

test -e "$rcfile" || {
	echo $progname: $rcfile: File not found >&2
	echo $progname: Create it to enable the script here >&2
	exit 1
}

for f in $(find /proc/sys/net | grep /disable_ipv6\$); do
	echo $progname: Old value in $f: $(cat $f)
	echo 1 >$f
done

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
