#!/bin/sh

# $Id: dumptrack,v 1.2 2002/10/08 20:44:47 sunny Exp $
# Dumper rådata fra GPS'en.

dir=/home/sunny/src/cvs/gps/tracks/raw/`date +%Y/%m`
fil=$dir/`u`.track.mayko

echo Dumper trackdata til "$fil".
[ -d $dir ] || mkdir -p $dir || { echo mkdir $dir: Hm.; exit 1; }
gpstrans -p/dev/modem -dt -m >$fil
