#!/bin/sh

# $Id: dumptrack,v 1.3 2003/06/19 10:28:13 sunny Exp $
# Dumper rådata fra GPS’en.

dir=/home/sunny/src/cvs/gps/tracks/raw/`date +%Y/%m`
fil=$dir/`u`.track.mayko

echo Dumper trackdata til "$fil".
[ -d $dir ] || mkdir -p $dir || { echo mkdir $dir: Hm.; exit 1; }
gpstrans -p/dev/modem -dt -m >$fil
chown -v sunny.sunny $fil
