#!/bin/bash

#=======================================================================
# edit-sqlite3
# File ID: d6a111fc-6a8c-11e5-b795-fefdb24f8e10
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=edit-sqlite3
VERSION=0.0.0

if test "$1" = "--version"; then
    echo $progname $VERSION
    exit 0
fi

if test "$1" = "-h" -o "$1" = "--help"; then
    cat <<END

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  --version
    Print version information.

END
    exit 0
fi

