#!/bin/bash

#=======================================================================
# File ID: 4a7f552e-875f-11de-97e4-00248cd5cf1e
# Lists empty directories in a subtree
# License: GNU General Public License version 2 or later.
#=======================================================================

for f in `find -type d | sort`; do
    grep -qr . "$f"/* 2>/dev/null || echo $f;
done
