#!/bin/bash

#=======================================================================
# File ID: 4a7f552e-875f-11de-97e4-00248cd5cf1e
# Lists empty directories in a subtree
# License: GNU General Public License version 2 or later.
#=======================================================================

find -type d -empty
