#!/bin/sh

#==============================================================================
# emptydirs
# File ID: 4a7f552e-875f-11de-97e4-00248cd5cf1e
#
# Lists empty directories in a subtree
#==============================================================================

progname=emptydirs
VERSION=0.1.0

find . "$@" -type d -empty | LC_ALL=C sort

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
