#!/usr/bin/perl -w

#=======================================================================
# $Id$
# Encapsulate stdin in XML tags.
#=======================================================================

use strict;

defined($ARGV[0]) || ($ARGV[0] = "l");
for my $Elem (@ARGV) {
    print("<$Elem>");
}
print(join("", <STDIN>));
for my $Elem (reverse @ARGV) {
    print("</$Elem>");
}
