#!/usr/bin/perl -w

#=======================================================================
# $Id$
# Encapsulate stdin in XML tags.
#=======================================================================

use strict;

my $Elem = defined($ARGV[0]) ? $ARGV[0] : "l";
printf("<%s>%s</%s>\n", $Elem, join("", <STDIN>), $Elem);
