#!/bin/sh

#=======================================================
# $Id: epstat,v 1.3 2001/06/05 05:18:47 sunny Exp $
# Lager enkel statistikk over hits osv i en loggfil.
# Forventer antall sekunder siden 1970 etterfulgt av TAB
# i begynnelsen av hver linje.
#=======================================================

tmp_file=/tmp/epstat.$RANDOM.tmp

cut -c 1-10 $* | sort -n | ep -l >$tmp_file

echo Antall hits pr. døgn:
echo
uniq -cw 10 $tmp_file | tr T ' ' | cut -c 1-18
echo

echo Antall hits pr. time:
echo
uniq -cw 13 $tmp_file | tr [T:] ' ' | cut -c 1-21

echo
echo Totalt $(wc -l $tmp_file | rmspcall | cut -d ' ' -f 1) hits.

rm $tmp_file
