#!/bin/bash

#==============================================================================
# exifdiff
# File ID: 9c91422a-08e1-11e8-abe0-f74d993421b0
#==============================================================================

progname=exifdiff
VERSION=0.1.1

vimdiff <(exiftool -api LargeFileSupport=1 "$1") \
        <(exiftool -api LargeFileSupport=1 "$2")

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
