#!/usr/bin/perl -w

#=======================================================================
# fibonacci
# File ID: ad60b6b4-5d39-11df-9c8b-90e6ba3022ac
# Skriver ut Fibonacci-rekka.
#=======================================================================

use strict;
use bigint;

my $Curr = 1;
my $Prev = 1;
my $Sum = 0;

for (;;) {
    $Sum = $Curr+$Prev;
    print("$Curr\n");
    $Curr = $Prev;
    $Prev = $Sum;
}
