#!/bin/bash

#=======================================================================
# $Id$
# Syntax: programnavn `filmer`
# Hehe, latterlig enkelt.
#=======================================================================

find "$@" | egrep -i '\.(3gp|asx|avi|flv|mng|mov|mp4|mpeg|mpg|ogv|wmv)$' | LC_COLLATE=C sort
