#!/bin/bash

#=======================================================================
# filmer
# File ID: b27679f4-5d39-11df-80fb-90e6ba3022ac
# Syntax: programnavn `filmer`
# Hehe, latterlig enkelt.
#=======================================================================

find "$@" | egrep -i '\.(3gp|asx|avi|flv|m4v|mng|mov|mp4|mpeg|mpg|ogv|vob|webm|wmv)$' | LC_COLLATE=C sort
