#!/usr/bin/perl -w

#===============================================================
# $Id: filter_ep,v 1.1 2003/09/27 05:42:40 sunny Exp $
# Slipper bare ting som ser ut som en gyldig ep igjennom.
# For å ta så mye drit som mulig, slipper den bare gjennom
# 9-sifrede nummer som begynner på 9, og 10-sifrede nummer som
# begynner på 1.
#
# Character set: UTF-8
# License: GNU General Public License
# ©opyleft 2003 Øyvind A. Holm <sunny@sunbase.org>
#===============================================================

use strict;

$| = 1;

while (<>) {
	chomp;
	if (/^(9\d{8})$/ || /^(1\d{9})$/) {
		print("$_\n");
	} else {
		print(STDERR "Linje $.: Ulovlig: \"$_\"\n");
	}
}

__END__

# vim: set fileencoding=UTF-8 filetype=perl foldmethod=marker foldlevel=0 :
# End of file $Id: filter_ep,v 1.1 2003/09/27 05:42:40 sunny Exp $
