#!/bin/bash

#=======================================================================
# $Id$
# File ID: aad4fde6-02e6-11de-acfb-000475e441b9
# Kjører ei fil ($2 osv) gjennom et filter som spesifiseres som $1.
# License: GNU General Public License version 2 or later.
#=======================================================================

cmd=$1
shift
for ff in "$@"; do
    cp -p $ff $ff.filt-bck
    cat "$ff" | $cmd >filt.tmp
    mv -v filt.tmp "$ff"
done
