#!/usr/bin/perl -w

#=======================================================================
# $Id$
# Slipper bare ting som ser ut som en gyldig ep igjennom. For å ta så 
# mye drit som mulig, slipper den bare gjennom 9-sifrede nummer som 
# begynner på 9, og 10-sifrede nummer som begynner på 1. -v skriver ut 
# ulovlige linjer.
#
# Character set: UTF-8
# License: GNU General Public License versjon 2 eller nyere.
# ©opyleft 2003–2004 Øyvind A. Holm <sunny@sunbase.org>
#=======================================================================

use strict;

$| = 1;

while (<>) {
    chomp;
    if (/\b(9\d{8})\b/ || /\b(1\d{9})\b/) {
        print("$1\n");
    }
}

__END__

=pod

=head1 LICENCE

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2 of the License, or (at your 
option) any later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

=cut

# vim: set fileencoding=UTF-8 filetype=perl foldmethod=marker foldlevel=0 :
# End of file $Id$
