#!/bin/bash

#=======================================================================
# finddup
# File ID: e5069ae2-f742-11dd-8012-000475e441b9
# Find duplicated files.
# License: GNU General Public License version 3 or later.
#=======================================================================

myf "$@" -type f | \
ns | \
cut -f2- | \
sort -rn | \
sumdup | \
grep . | \
cut -f4 | \
tr '\n' '\0' | \
xargs -0 sha1sum | \
sed s/\\\\// | \
sort | \
sumdup | \
cut -c43-
