#!/bin/bash

#=======================================================================
# firefox
# File ID: 14cc7a8c-3746-11e4-9e92-c80aa9e67bbd
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

sess -t c_firefox /usr/bin/firefox
