#!/usr/bin/env bash

#=======================================================================
# fix-agdate
# File ID: 3a208946-50bb-11e6-8515-02010e0a6634
#
# Fix timestamp difference between .mp4 and .srt in AutoGuard
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=fix-agdate
VERSION=0.1.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Fix timestamp difference between .mp4 and .srt in AutoGuard (dash camera 
app for Android). Sometimes there is a difference of 1 second between 
the .mp4 and .srt file, and when they've been processed with datefn(1), 
the subtitles (GPS coordinates and timestamp) disappear.

Usage: $progname [options] AG_FILES [...]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

for f in "$@"; do
    echo "$f" | grep -q 20.._.._.._.._.._..\\.mp4\$ || continue
    base="$(basename "$f" .mp4)"
    if test -e "$base.srt"; then
        echo touch -r "$base.mp4" "$base.srt"
        touch -r "$base.mp4" "$base.srt"
    fi
done
