#!/usr/bin/perl -w

# fixtext
# File ID: 43fdfa28-5d3a-11df-ab1a-90e6ba3022ac
# Enkel konvertering av tekst til entities og denslags.

use strict;

$_ = join("", <>);
s/'/&#x2019;/g;
s/"(.*?)"/&#x201C;$1&#x201D;/gs;
s/ -- / &#x2014; /g;
print;
