#!/bin/bash

#=======================================================================
# fjern-gamle-annex-remoter
# File ID: 8b521aa8-e3db-11e4-854a-7bc45393da5f
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

annex-cmd -D innsp -e "git remote rm pavi"

annex-cmd -D asfaltlappen -e "git remote rm usb32g-1"
annex-cmd -D test -e "git remote rm usb32g-1"
annex-cmd -D usortert -e "git remote rm usb32g-1"

annex-cmd -D asfaltlappen -e "git remote rm usb32g-2"
annex-cmd -D garage-side -e "git remote rm usb32g-2"
annex-cmd -D log -e "git remote rm usb32g-2"
annex-cmd -D test -e "git remote rm usb32g-2"

annex-cmd -D asfaltlappen -e "git remote rm exthd"
annex-cmd -D asfaltlappen -e "git remote rm passp"

annex-cmd -D mobile -e "git remote rm ubstud"

annex-cmd -D usortert -e "git remote rm pavi"

annex-cmd -e "git remote rm targus-2gb"

annex-cmd -D log -e "git remote rm pavi"
