#!/bin/bash

# flac_to_ogg
# File ID: 5a4e814e-5d3a-11df-a4ca-90e6ba3022ac
# Konverterer alle *.flac-filene til ogg i en egen katalog.

KVAL=6

[ -d "ogg" ] || mkdir ogg || { echo "Klarte ikke mkdir ogg" >&2; exit 1; }
for f in *.flac; do
	if [ -e "$f" ]; then
		echo $f;
		flac -d <"$f" | oggenc -q$KVAL -c "encoding=OggEnc v0.9 (libvorbis rc3) CVS-20020523 -q$KVAL" -o $(echo ogg/$f|perl -pe "s/\\.flac\$//" |tr ' ' _).q$KVAL.ogg -
	else
		echo $f finnes ikke. Driter i den.
	fi
done
