#!/bin/bash

#=======================================================================
# ga-getnew
# File ID: 1fc79a40-015b-11e5-a869-f13c8f9a2603
#
# Fix broken symlinks for new files from the last month (can be 
# overridden) in git-annex. Useful when moving lots of files around and 
# committing with --no-verify (or disabling the automatic symlink fixing 
# in .git/hooks/pre-commit) to properly record file moves in Git.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=ga-getnew
VERSION=0.2.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Fix broken symlinks for new files from the last month (can be 
overridden) in git-annex. Useful when moving lots of files around and 
committing with --no-verify (or disabling the automatic symlink fixing 
in .git/hooks/pre-commit) to properly record file moves in Git.

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

msg() {
    echo
    echo ==== $progname: $*
}

toplevel="$(git rev-parse --show-toplevel)"
cd "$toplevel" || {
    echo $progname: $toplevel: Cannot chdir to top of repo >&2
    exit 1
}

git wait-until-clean -u

msg ga fix
git allfiles --since=1.month "$@" |
    strip-nonexisting |
    xargs -d \\n --no-run-if-empty ga fix
