#!/bin/bash

#=======================================================================
# ga-getnew
# File ID: 8af4d956-f358-11e4-b717-000df06acc56
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

