#!/bin/bash

#=======================================================================
# ga-ignore-remote
# File ID: ff8df730-a2ed-11e5-9f07-fefdb24f8e10
#
# Disable automatic push from git-annex to a Git remote
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=ga-ignore-remote
VERSION=0.2.0

ARGS="$(getopt -o "\
h\
q\
u\
v\
" -l "\
help,\
quiet,\
unignore,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-u|--unignore) opt_unignore=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Disable automatic push from git-annex to a Git remote

Usage: $progname [options] REMOTE

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -u, --unignore
    Don't ignore the remote anymore, remove the ignore settings from Git 
    config.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
    -v: List "remote.\$remote.annex" config values before and after
  --version
    Print version information.

END
    exit 0
fi

remote="$1"
shift
if test -z "$(git remote | grep "^$remote\$")"; then
    echo $progname: $remote: Git remote not found
    exit 1
fi

if test $opt_verbose -gt 0; then
    git config -l | grep ^remote.$remote.annex
    echo
fi

if test "$opt_unignore" = "1"; then
    git config --unset remote.$remote.annex-ignore
    git config --unset remote.$remote.annex-readonly
else
    git config remote.$remote.annex-ignore true
    git config remote.$remote.annex-readonly true
fi

if test $opt_verbose -gt 0; then
    git config -l | grep ^remote.$remote.annex
fi
