#!/usr/bin/env bash

#=======================================================================
# ga-key
# File ID: 027211a6-f115-11e4-9e02-000df06acc56
#
# Calculate SHA256 key used by git-annex.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=ga-key
VERSION=0.1.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        -h|--help) opt_help=1; shift ;;
        -q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        -v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        --version) echo $progname $VERSION; exit 0 ;;
        --) shift; break ;;
        *) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Calculate SHA256 key used by git-annex.

Usage: $progname [options] FILE

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

test -z "$1" && { echo $progname: Missing filename >&2; exit 1; }
test -n "$2" && {
    echo $progname: Takes exactly one argument, and that must be a filename >&2
    exit 1
}

file="$1"

test -f "$file" || {
    test "$opt_quiet" = "1" || echo $progname: $file: File not found or is not a readable file >&2
    exit 1
}

echo SHA256-s$(wc -c "$file" | cut -f 1 -d ' ')--$(sha256sum "$file" | head -c 64)
