#!/usr/bin/env bash

#=======================================================================
# ga-sjekk
# File ID: 4d412868-f13b-11e4-be3f-000df06acc56
#
# Check if the specified files are already archived in git-annex. Files 
# that are already archived are moved to ".ga-found/$dir/".
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=ga-sjekk
VERSION=0.2.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        -h|--help) opt_help=1; shift ;;
        -q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        -v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        --version) echo $progname $VERSION; exit 0 ;;
        --) shift; break ;;
        *) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Check if the specified files are already archived in git-annex. Files 
that are already archived are moved to ".ga-found/".

Usage: $progname [options] FILE [FILE [...]]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

for f in "$@"; do
    key=$(ga-key -q "$f")
    test -n "$key" && {
        echo ======== $f $key
        # FIXME: Hardcoding
        for dir in innsp log musikk opptak s usortert; do
            repodir=''
            for m in /media/*/annex; do
                if test -d "$m/$dir"; then
                    repodir="$m/$dir"
                fi
            done
            if test -d "$HOME/annex/$dir"; then
                repodir="$HOME/annex/$dir"
            fi
            if test -z "$repodir"; then
                echo $progname: $dir: Repo not found >&2
                continue
            fi
            (
                cd "$repodir" && {
                    result="$(
                        ga whereis --key "$key" 2>/dev/null |
                        grep -v '(0 copies) failed$'
                    )"
                    test -n "$result" && {
                        echo
                        echo $dir
                        ga whereis --key "$key"
                        cd -
                        dest=".ga-found/$dir/$(dirname "$f")"
                        mkdir -p "$dest"
                        mv -vi "$f" "$dest"
                    }
                }
            )
        done
    }
done
