#!/bin/bash

#=======================================================================
# ga-sjekk
# File ID: 4d412868-f13b-11e4-be3f-000df06acc56
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

