#!/usr/bin/env bash

#=======================================================================
# ga-tree
# File ID: 9aa77afc-3550-11e2-9816-00c0a8deee11
#
# Tree view of a subdirectory structure, optimised for git-annex.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=ga-tree
VERSION=0.3.0

ARGS="$(getopt -o "\
C\
d\
h\
q\
v\
" -l "\
colour,\
directories,\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_colour=0
opt_directories=0
opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        -C|--colour) opt_colour=1; shift ;;
        -d|--directories) opt_directories=1; shift ;;
        -h|--help) opt_help=1; shift ;;
        -q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        -v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        --version) echo $progname $VERSION; exit 0 ;;
        --) shift; break ;;
        *) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Tree view of a subdirectory structure, optimised for git-annex. 
Arguments and options after " -- " are delivered to tree(1).

Usage: $progname [options] [ -- OPTIONS_TO_tree(1) ]

Options:

  -C, --colour
    Use colours.
  -d, --directories
    Only list directories.
  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

if test "$opt_colour" = "1"; then
    colour_str=' -C'
else
    colour_str=''
fi

if test "$opt_directories" = "1"; then
    directories_str=' -d'
else
    directories_str=''
fi

tree --charset UTF-8$colour_str$directories_str -N "$@" |
    perl -pe 's/^(.*)( -> \.\..*)/$1/' |
    less -r
