#!/bin/bash

# gammelsvn
# File ID: 76456e44-5d3a-11df-862d-90e6ba3022ac

oldurl=`svn info | egrep '^(URL|Nettadresse)' | cut -f2 -d ' '`
newurl=`echo $oldurl | perl -pe 's/^(.*:.*)(:)(.*?)$/$1$3/'`

echo svn sw --relocate $oldurl $newurl
svn sw --relocate $oldurl $newurl
