#!/bin/bash

# $Id$

oldurl=`svn info | grep ^URL | cut -f2 -d ' '`
newurl=`echo $oldurl | perl -pe 's/^(\*:.*)(:)(.*?)$/$1$3/'`

echo svn sw --relocate $oldurl $newurl
svn sw --relocate $oldurl $newurl
