#!/bin/bash

#=======================================================================
# $Id
# Download the newest apr+neon into the current directory.
#=======================================================================

svn co http://svn.apache.org/repos/asf/apr/apr/branches/0.9.x apr
svn co http://svn.apache.org/repos/asf/apr/apr-util/branches/0.9.x apr-util

