#!/bin/bash

#=======================================================================
# git-wait-until-clean
# File ID: 92d46e22-d5a1-11e4-9769-000df06acc56
#
# Wait until the current Git repository is clean before continuing.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

unset u_str
test "$1" = "-u" && { u_str=" --untracked-files=no"; shift; }

while test "$(git status --porcelain$u_str)" != ""; do
    echo Waiting for $(hostname):$(pwd) to be cleaned up... \($(date)\);
    sleep 5;
done;
