#!/bin/sh

# File ID: 9e591bac-4e84-11df-b237-90e6ba3022ac

for f in *; do
    if [ -d "$f/.git/." ]; then
        echo ================ $f ================
        # echo ==== git f ====
        (cd $f && git remote -v update -p)
        # echo ==== git pull ====
        # (cd $f && git pull)
        # echo ==== git pa ====
        # (cd $f && git pa)
        echo
    fi
done
