#!/bin/sh

#==============================================================================
# git-allfiles
# File ID: a51e903a-3457-11e4-a2e4-c80aa9e67bbd
#
# List all tree members (files and symlinks) in the whole Git history. 
# Command line arguments are delivered to "git log".
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=git-allfiles
VERSION=0.2.0

if test "$1" = "--version"; then
echo $progname $VERSION
	exit 0
fi

if test "$1" = "-h" -o "$1" = "--help"; then
	cat <<END

List all tree members (files and symlinks) in the whole Git history. 
Command line arguments are delivered to "git log".

Usage: $progname [options] [ -- arguments_to_git_log ]

Options:

  -h, --help
    Show this help.
  --version
    Print version information.

END
	exit 0
fi

git log --raw --no-renames "$@" | grep ^: | cut -f 2 | sort -u

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
