#!/bin/sh

# git-eb
# File ID: 45c7afa2-434a-11df-8880-90e6ba3022ac
#
# Create new and unconnected branch
# usage: git eb <newbranch>

[ -z "$1" ] && { echo "usage: git eb <newbranch>" >&2; exit 1; }
[ -d ".git/." ] || { echo "git-eb: has to be executed from the top level of the tree" >&2; exit 2; }
git symbolic-ref HEAD refs/heads/"$1"
rm .git/index || { echo "git-eb: cannot remove .git/index" >&2; exit 3; }
git commit --allow-empty -m "Initial commit"
