#!/usr/bin/env bash

#=======================================================================
# git-add-missing-gpg-keys
# File ID: e53738b0-9caa-11e3-a01a-001f3b596ec9
#
# Add missing GPG keys used for signed Git tags and commits.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=git-add-missing-gpg-keys
VERSION=0.1.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Add missing GPG keys used for signed Git tags and commits.

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

LC_ALL=C git log --show-signature "$@" | \
grep "^gpg: Can't check signature: public key not found" -B1 | \
grep "key ID" | \
rev | cut -f 1 -d ' ' | rev | \
sort -u | \
while read f; do
    (
        cd ~/.gnupg || { echo $progname: ~/.gnupg: Cannot chdir >&2; exit 1; }
        gpg --recv-keys $f
        shopt -s nullglob
        files_gone=0
        until test "$files_gone" = "1"; do
            array=('.#lk'*)
            if (( ${#array[@]} > 0 )); then
                echo $progname: Waiting for tmpfiles to disappear...
                sleep 1
            else
                files_gone=1
            fi
        done
        ciall -y "gpg --recv-keys $f"
    )
done
