#!/bin/sh

#==============================================================================
# git-empty
# File ID: 40e83476-57e6-11e7-9426-db5caa6d21d3
#
# Delete all files from Git checkout to save space
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=git-empty
VERSION=0.2.0

opt_force=0
opt_help=0
opt_quiet=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-f|--force) opt_force=1; shift ;;
	-h|--help) opt_help=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Delete all versioned files and directories from a Git checkout to save 
disk space. If any files are modified, it waits until the checkout is 
clean before continuing. All files can be restored with "git checkout 
-f".

Usage: $progname -f [options]

Options:

  -f, --force
    Actually delete the files. This option is mandatory to avoid 
    accidentally deleting the files, even though it's easy to get them 
    back.
  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
	exit 0
fi

if test "$opt_force" != "1"; then
	echo $progname: -f/--force option not specified, aborting >&2
	exit 1
fi

git wait-until-clean -u || exit 1
git ls-files -z | xargs -0 --no-run-if-empty rm -f
find . -depth -type d -print0 | \
  grep -azv -e '/\.git/' | \
  xargs -0 rmdir 2>/dev/null

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
