#!/bin/bash

#=======================================================================
# git-trash
# File ID: 7994342c-a02f-11e3-867b-001f3b596ec9
# Get rid of local changes by committing them to a headless branch
# License: GNU General Public License version 3 or later.
#=======================================================================

git checkout $(git rev-parse HEAD)
git commit -a
git branch commit-$(git rev-parse HEAD)
git checkout -
