#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""git-expand - Unpack Git object

File ID: 76189104-142e-11e3-8ac9-001f3b596ec9
License: GNU General Public License version 3 or later.

"""

import sys
import zlib

sys.stdout.write(zlib.decompress(sys.stdin.read()))
