#!/bin/bash

#=======================================================================
# git-wn
# File ID: 149ce758-8aca-11e0-afed-37ea9f2067e0
#
# "git what's new", show descendants of a specific commit
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=git-wn
VERSION=0.2.0

if test "$1" = "--version"; then
    echo $progname $VERSION
    exit 0
fi

if test "$1" = "-h" -o "$1" = "--help"; then
    cat <<END

"git what's new", show descendants of a specific commit. For example, 
after "git fetch", list all new commits.

Usage: $progname [options] [commit] [git_log_args]

Options:

  -h, --help
    Show this help.
  -p
    Use extended format with patch.
  -w
    Same as -p, but use word diff instead
  --version
    Print version information.

If commit is not specified, use HEAD. To use git_log_args, a 
commit/branch/tag/whatever has to be specified as \$1.

END
    exit 0
fi

unset opt_p
test "$1" = "-p" && { opt_p=1; shift; }
unset opt_w word_diff_str
test "$1" = "-w" && { opt_p=1; opt_w=1; word_diff_str="--word-diff"; shift; }

unset branches
from="$1"
shift
test -z "$from" && from=HEAD
git log -1 $from &>/dev/null || { echo $from: Invalid ref >&2; exit 1; }
log_args="$@"

for f in $(git lc $from); do
    branches="$branches $from..$f"
done

if test "$opt_p" = "1"; then
    git log --date-order --date=iso --decorate=short --format=fuller --graph \
      $word_diff_str -c -p $log_args $branches
else
    git log --abbrev-commit --date-order --decorate=short --graph \
      --pretty=format:'%Cred%h %Cblue%p%Creset -%Creset %s %Cgreen(%cd %Cblue%an%Cgreen)%Creset%C(yellow)%d%Creset' \
      $log_args $branches
fi
