#!/bin/bash

#=======================================================================
# git-wn
# File ID: 149ce758-8aca-11e0-afed-37ea9f2067e0
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

unset branches
from="$*"
test -z "$from" && from=HEAD

for f in $(git lc $from); do
    branches="$branches $from..$f"
done
git lg --date-order $branches
