#!/bin/sh

#==============================================================================
# git-up
# File ID: 96b89f6a-d1eb-11e7-9056-f74d993421b0
#
# Make a full Git update in the current repository
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=git-up
VERSION=0.1.2

T_GREEN=$(tput setaf 2)
T_RED=$(tput setaf 1)
T_RESET=$(tput sgr0)

opt_help=0
opt_quiet=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-h|--help) opt_help=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

runcmd() {
	echo >&2
	echo "$T_GREEN$progname: $*$T_RESET" >&2
	$@
}

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Make a full Git update in the current repository. Fetch everything, 
update all local branches, create commit-* branches from dangling heads 
and push the result to all remotes.

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
	exit 0
fi

currbranch=$(git rev-parse --abbrev-ref HEAD)

safe_checkout() {
	local branch=$1

	if test -n "$currbranch" -a "$currbranch" != "HEAD"; then
		runcmd git checkout "$branch"
	else
		echo -n "$T_RED$progname: " >&2
		echo "No current branch, skip \"git checkout $branch\"$T_RESET" >&2
	fi
}

runcmd git fetch --all --prune
runcmd git merge --ff-only
safe_checkout $(git rev-parse HEAD)
runcmd git allbr -a
safe_checkout -
runcmd git dangling
runcmd git pa

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
