#!/bin/bash

#=======================================================================
# git-rpull
# File ID: 5945bcd0-d1cb-11e4-b20f-000df06acc56
#
# Update remote Git repositories.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

git-rcmd -c "git pull --ff-only" "$@"
