#!/bin/sh

# File ID: 9e591bac-4e84-11df-b237-90e6ba3022ac

pull=0
err_fetch=
err_pull=
test "$1" = "-p" && { pull=1; shift; }
for f in *; do
    if [ -d "$f/.git/." ]; then
        echo ================ $f ================
        # echo ==== git f ====
        (cd $f && git remote -v update -p) || err_fetch="$err_fetch $f"
        test "$pull" = "1" && { echo ==== git pull --ff-only ====; (cd $f && git pull --ff-only) || err_pull="$err_pull $f"; }
        # echo ==== git pa ====
        # (cd $f && git pa)
        echo
    fi
done
test -z "$err_fetch" || echo git-update-dirs: Unable to fetch from: $err_fetch
test -z "$err_pull" || echo git-update-dirs: Unable to pull from: $err_pull
