#!/bin/bash

#=======================================================================
# git-nocom
# File ID: 6553a34c-1194-11e2-97b0-fefdb24f8e10
#
# List all branches except those containing "commit-[0-9a-f]{40}" .
# Can be used for things like this:
#
#   git log `git branch -a | git nocom`
#
# License: GNU General Public License version 3 or later.
#=======================================================================

v_str=
test "$1" = "-r" || v_str=-v
fmt -1 |
tr -d '\t ' |
grep -v -E '^(->|\*)$' |
grep -E $v_str 'commit-[0-9a-f]{40}'
