#!/bin/bash

#=======================================================================
# git-realclean
# File ID: a0e45088-d9f3-11e1-b9d0-00c0a8deee11
# Compress a Git repo really good
# License: GNU General Public License version 3 or later.
#=======================================================================

if [ -d .git/. ]; then
    dudir=.git
else
    dudir=.
fi

tot_before=$(du -bs $dudir | cut -f 1)
echo tot_before: $(echo $tot_before | commify)
echo ==== git reflog expire
git reflog expire --expire=now --expire-unreachable=now --all
echo ==== git gc
git gc --prune=now
tot_after=$(du -bs $dudir | cut -f 1)
saved=$(echo "$tot_before-$tot_after" | bc)
echo -----------
echo tot_before: $(echo $tot_before | commify)
echo tot_after: $(echo $tot_after | commify)
echo "Totally saved: $(echo $saved | commify) ($(echo "scale=2; 100*$saved/$tot_before" | bc -l) %)"
