#!/bin/sh

#==============================================================================
# git-upstream
# File ID: cb907ea4-4d42-11e5-8090-fefdb24f8e10
#
# Set up local branches to track remote branches.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=git-upstream
VERSION=0.4.1

opt_help=0
opt_quiet=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-h|--help) opt_help=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Set up local branches to track remote branches. If no remote is 
specified, 'origin' is used.

Usage: $progname [options] [remote [branches]]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
	exit 0
fi

remote=origin
test -n "$1" && { remote="$1"; shift; }
git remote | grep -q "^$remote\$" || {
	echo $progname: $remote: No local remote with that name found >&2
	exit 1
}

if test -n "$1"; then
	branches="$@"
else
	branches="$(
	    git branch |
	    grep -v HEAD |
	    cut -c 3-
	)"
fi

for f in $branches; do
	git -c "advice.setupstreamfailure=false" branch -u "$remote/$f" "$f"
done

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
