#!/bin/bash

#=======================================================================
# git-fuckit
# File ID: 2a3efbbe-f1a0-11e4-9228-fefdb24f8e10
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

