#!/bin/bash

# File ID: 4dd0ecb6-6354-11df-9f20-000c6ed3978a

test -z "$2" && { echo "Syntax: git dobranch <command> <range or HEAD>" >&2; exit 1; }
echo -n This script will change the history of the branch. Press y to continue...
read cont
test "$cont" = "y" || exit;
git filter-branch --prune-empty --force --tree-filter "$@"
