#!/bin/bash

#=======================================================================
# git-realclean
# File ID: a0e45088-d9f3-11e1-b9d0-00c0a8deee11
# Compress a Git repo really good
# License: GNU General Public License version 3 or later.
#=======================================================================

gitsize() {
    if [ -d .git/. ]; then
        du -hs .git
    else
        du -hs
    fi
}

gitsize
echo ==== git reflog expire
git reflog expire --expire=now --expire-unreachable=now --all
echo ==== git gc
git gc --prune=now --aggressive
gitsize
