#!/bin/sh

# git-eb
# File ID: 45c7afa2-434a-11df-8880-90e6ba3022ac
#
# Create new and unconnected branch
# usage: git eb <newbranch>

git symbolic-ref HEAD refs/heads/"$1"; rm .git/index; git clean -fdx; git commit --allow-empty -m "Initial commit"
