#!/bin/sh

#=======================================================================
# git-dangling
# File ID: 13613774-3334-11e0-bfdc-fefdb24f8e10
# Create branches on every dangling commit
# License: GNU General Public License version 3 or later.
#=======================================================================

bannedfile=$HOME/.git-dangling-banned

if test "$1" = "-c"; then
    # Check if commit-* branches are part of any other branch
    for f in $(git branch | cut -c 3- | grep '^commit-'); do
        echo ============ $f
        git branch -a --contains=$f | grep -v "^  $f\$"
    done
    exit
fi

# Delete all commit-* branches
branches=`git branch | cut -c 3- | grep -E '^commit-[0-9a-f]{40}$' | grep -Ev commit-0{40}`
test -n "$branches" && git branch -D $branches

test "$1" = "-D" && exit

git fsck --no-reflogs >dangling-result.tmp
for f in `grep "dangling commit" dangling-result.tmp | cut -f 3 -d ' '`; do
    skip=0
    if test -e $bannedfile; then
        for ban in $(cut -f1 -d ' ' $bannedfile | grep -E '^[0-9a-f]{40}'); do
            echo $f | grep -q $ban && skip=1
        done
    fi
    test "$skip" = "0" && git branch commit-$f $f && echo commit-$f
done
