#!/usr/bin/perl -w

# $Id: gpsfold,v 1.3 2003/08/30 05:12:14 sunny Exp $
# Inserts fold marks in GPS data files before and after stdin.
# Select text in visual line mode and filter the block through this script.

use strict;

use Getopt::Std;
our ($opt_h, $opt_m) = (0, 0);
getopts('hm');

$| = 1;

if ($opt_h) {
	print(<<END);

Syntax: gpsfold [options]

Options:

-h  Help me, please
-m  Add a "# move" after the fold.

END
	exit(0);
}

my $Title = "";
my @Data = ();

defined($ARGV[0]) && ($Title = join(" ", @ARGV));
my $colon_str = (length($Title) ? ": " : "");

my $Line = "";
my ($start_date, $end_date) = ("", "");

while ($Line = <STDIN>) {
	push(@Data, $Line);
	unless (length($start_date)) {
		if ($Line =~ /^(?:# )?(\d\d\d\d)-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d)(Z?)\t/) {
			$start_date = "$1$2${3}T$4$5$6$7";
		} elsif ($Line =~ /^(?:# )?(\d\d\d\d\d\d\d\dT\d\d\d\d\d\dZ?)\t/) {
			$start_date = $1;
		} elsif ($Line =~ /^(?:# )?1 (\S+) (\S+) (\S+) (\S+) (\d\d)\/(\d\d)\/(\d\d\d\d) (\d\d):(\d\d):(\d\d)/) {
			$start_date = "$7$5${6}T$8$9$10";
		}
	}
	if ($Line =~ /^(?:# )?(\d\d\d\d)-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d)(Z?)\t/) {
		$end_date = "$1$2${3}T$4$5$6$7";
	} elsif ($Line =~ /^(?:# )?(\d\d\d\d\d\d\d\dT\d\d\d\d\d\dZ?)\t/) {
		$end_date = $1;
	} elsif ($Line =~ /^(?:# )?1 (\S+) (\S+) (\S+) (\S+) (\d\d)\/(\d\d)\/(\d\d\d\d) (\d\d):(\d\d):(\d\d)/) {
		$end_date = "$7$5${6}T$8$9$10";
	}
}

push(@Data, "# $start_date-$end_date$colon_str$Title \x7D\x7D\x7D\n");
unshift(@Data, "# $start_date-$end_date$colon_str$Title \x7B\x7B\x7B\n");
$opt_m && push(@Data, "# move\n");

for (@Data) {
	print $_;
}

# End of file $Id: gpsfold,v 1.3 2003/08/30 05:12:14 sunny Exp $
