#!/usr/bin/perl -w

# $Id: gptrans_conv,v 1.1 2002/09/02 15:53:25 sunny Exp $

while (<>) {
	if (m#^T\t(..)/(..)/(....) (..):(..):(..)\t(.+)°(.+)'(.+)"\t(.+)°(.+)'(.+)"#) {
		my ($Month, $Day, $Year, $Hour, $Min, $Sec, $lat_d, $lat_m, $lat_s, $lon_d, $lon_m, $lon_s) = ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12);
		my $lat_val = sprintf("%.5f", 1*($lat_d+($lat_m/60)+($lat_s/3600)));
		my $lon_val = sprintf("%.5f", $lon_d+($lon_m/60)+($lon_s/3600));
		print("$Year-$Month-$Day $Hour:$Min:$Sec\t$lon_val\t$lat_val\n");
		# print("$lat_val\t$lon_val\n");
	} else {
		warn("Linje $.: Ukjent: \"$_\"");
	}
}
