#!/bin/bash

#=======================================================================
# gqview
# File ID: ac113e22-5e6c-11e3-a4fa-001f3b596ec9
# gqview was forked and changed the name to geeqie years ago, but I'll 
# never get used to that.
# License: GNU General Public License version 3 or later.
#=======================================================================

geeqie "$@" &
