#!/bin/sh

# Stopper httpd(8)
# $Id: h0,v 1.9 2002/09/25 07:58:18 sunny Exp $

if [ -e /nett.mrk ]; then
	/etc/init.d/apache stop
elif [ -e /toshbb.mrk ]; then
	apachectl stop
elif [ -e /sunba.mrk ]; then
	/etc/init.d/apache stop
elif [ -e /recbb.mrk ]; then
	/var/lib/apache/sbin/apachectl stop
else
	echo Ukjent server, prøver standardløsning...
	if [ -x /etc/rc.d/init.d/httpd ]; then
		/etc/rc.d/init.d/httpd stop
	elif [ -x /etc/init.d/apache ]; then
		/etc/init.d/apache stop
	fi
fi
