#!/bin/sh

# h0
# File ID: b8705554-5d3a-11df-9ca9-90e6ba3022ac
# Stopper httpd(8)

if [ -e /nett.mrk -o -e /sunba.mrk ]; then
    /etc/init.d/apache2 stop
    while [ -e /var/run/apache2.pid ]; do :; done
elif [ -e /carmbb.mrk ]; then
    /usr/local/bin/apachectl stop
    while [ -e /var/run/apache2.pid ]; do :; done
elif [ -e /nett2.mrk ]; then
    /usr/local/bin/apachectl stop
    while [ -e /usr/local/prg/apache2/logs/httpd.pid ]; do :; done
elif [ -e /toshbb.mrk ]; then
    apachectl stop
elif [ -e /recbb.mrk ]; then
    /var/lib/apache/sbin/apachectl stop
else
    echo Ukjent server, prøver standardløsning...
    if [ -x /etc/rc.d/init.d/httpd ]; then
        /etc/rc.d/init.d/httpd stop
    elif [ -x /etc/init.d/apache ]; then
        /etc/init.d/apache stop
    fi
fi
