#!/bin/sh

# h1
# File ID: bcd3c590-5d3a-11df-958e-90e6ba3022ac
# Fyrer i gang httpd(8)

if [ -e /nett.mrk -o -e /sunba.mrk ]; then
    /etc/init.d/apache2 start
elif [ -e /carmbb.mrk ]; then
    /usr/local/bin/apachectl start
elif [ -e /nett2.mrk ]; then
    /usr/local/bin/apachectl start
elif [ -e /toshbb.mrk ]; then
    apachectl start
elif [ -e /recbb.mrk ]; then
    /var/lib/apache/sbin/apachectl start
else
    echo Ukjent server, prøver standardløsning...
    if [ -x /etc/rc.d/init.d/httpd ]; then
        /etc/rc.d/init.d/httpd start
    elif [ -x /etc/init.d/apache ]; then
        /etc/init.d/apache start
    fi
fi
