#!/bin/bash

# $Id$

# wget -bx `sget "$@" | urlstrip | egrep -i '\.(mpg|mpeg|avi|wmv|mng|mov)'`
if [ "$1" = "-b" ]; then
    patt='*.png,*.jpg'
    shift
else
    patt='*.mpg,*.mpeg,*.avi,*.wmv,*.mng,*.mov,*.asx'
fi
wget -l 1 -Hbxr -nc -A $patt -U 'Mozilla/4.78 [en] (X11; U; Linux 2.4.9-31 i686)' "$@"
