#!/bin/sh

#==============================================================================
# hum
# File ID: a59a7f7a-7e6f-11ea-bb07-4f45262dc9b5
#
# Convert numbers to human-readable format with numfmt(1).
#==============================================================================

progname=hum
VERSION=0.1.1

numfmt --to=si --format=%7.2f --invalid=ignore "$@"

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
