#!/bin/bash

# $Id: impnet,v 1.2 2002/05/02 00:17:21 sunny Exp $
# Legger en website inn i Cvs/imp-net .
# Syntax: impnet [webnavn]

impdir=/home/sunny/Cvs/imp-net
navn=$1

[ "$1" = "" ] && { echo "Syntaks: impnet [modulnavn]"; echo; exit 1; }
[ -d $impdir ] || { echo "$impdir er ikke her." >&2; exit 1; }
cvs -d $impdir import -d -kb -I \! raw www $1-$(date -u +"%Y%m%dT%H%M%SZ")
