#!/usr/bin/perl -w

# $Id: inc_epstat,v 1.2 2002/07/15 13:24:45 sunny Exp $
# Filter for å gjøre epstat-format brukbart i gnuplot.

my $Count = 0;

while (<>) {
	$Count++;
	s/^([\-\.\d]+)/$1\t$Count/;
	print;
}
