#!/usr/bin/perl -w

# $Id$
# Filter for å gjøre epstat-format brukbart i gnuplot.
# -f skriver telleren foran istedenfor etter.

use Getopt::Std;

our $opt_f = 0;
my $Count = 0;

getopts('f');

if ($opt_f) { # For å få opp farta
	while (<>) {
		s/^(.+)/$Count\t$1/;
		print;
		$Count++;
	}
} else {
	while (<>) {
		s/^(.+)/$1\t$Count/;
		print;
		$Count++;
	}
}
