#!/bin/bash

#=======================================================================
# irssi
# File ID: 8e00c630-8d1d-11e2-ab91-fefdb24f8e10
# Start irssi(1) using the only acceptable time zone ever
# (Han som oppfant sommertid skulle hatt i ræven.)
#=======================================================================

progname=irssi

if test -e /usr/local/bin/irssi; then
    irssi_cmd=/usr/local/bin/irssi
elif test -e /usr/bin/irssi; then
    irssi_cmd=/usr/bin/irssi
else
    echo $progname: Seems as irssi isn\'t installed here >&2
    exit 1
fi

TZ=UTC sess -d irssi -- $irssi_cmd "$@"
