#!/bin/bash

#==============================================================================
# jsondiff
# File ID: c660f5f6-08ef-11e8-9214-f74d993421b0
#==============================================================================

progname=jsondiff
VERSION=0.1.0

vimdiff <(jsonfmt.py <"$1") <(jsonfmt.py <"$2")

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
