#!/bin/bash

#=======================================================================
# kar
# File ID: fe72f7b6-e0b7-11e1-b043-f713f3430bad
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

mplayer -af karaoke "$@"
