#!/bin/bash

# $Id$
# Setter properties på tekstfiler sånn som jeg vil ha det.
# Hvis -u spesifiseres som første parameter, settes ikke svn:eol-style.

if [ "$1" != "-u" ]; then
	svn propset svn:eol-style native $*
else
	shift
fi
svn propset svn:keywords "Id Date" $*
svn propdel cvs2svn:cvs-rev $*
