#!/bin/bash

#=======================================================================
# $Id$
# Setter properties på tekstfiler sånn som jeg vil ha det.
# Hvis -u spesifiseres som første parameter, settes ikke svn:eol-style.
#=======================================================================

if [ "$1" != "-u" ]; then
    for _k in $*; do
        [ -f $_k ] && svn propset svn:eol-style native $_k
    done
else
    shift
fi

for _k in $*; do
    [ -f $_k ] && svn propset svn:keywords Id $_k
    svn propdel cvs2svn:cvs-rev $_k
    svn proplist -v $_k
done

# vim: set ts=4 sw=4 sts=4 et fo+=w fenc=utf8 :
