#!/bin/bash

#=======================================================================
# keyw
# File ID: 881b567a-fc3c-11dd-9a35-0001805bf4b1
# Setter properties på tekstfiler sånn som jeg vil ha det.
# Valg:
#   -k  Bruk svk istedenfor svn.
#   -u  svn:eol-style settes ikke.
#=======================================================================

if [ "$1" = "-k" ]; then
    CMD_SVN=svk
    shift
else
    CMD_SVN=svn
fi

if [ "$1" != "-u" ]; then
    for _k in "$@"; do
        [ -f "$_k" ] && $CMD_SVN propset svn:eol-style native "$_k"
    done
else
    shift
fi

for _k in "$@"; do
    $CMD_SVN propdel cvs2svn:cvs-rev "$_k"
    $CMD_SVN proplist -v "$_k"
done

# vim: set ts=4 sw=4 sts=4 et fo+=w fenc=utf8 :
