#!/bin/bash

#=======================================================================
# $Id$
# Skriver ut dato og klokkeslett, brukes for det meste for å sjekke 
# synkroniseringa mellom maskiner.
#=======================================================================

while :; do
    echo -n `date | tr '\n' '\r'`
done
