#!/bin/bash

#=======================================================================
# konvflac
# File ID: dde2fab8-3dfd-11e0-9b12-1b57187fd9d3
#
# Convert .wav files to .flac and keep metadata
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=konvflac
VERSION=0.2.0

ARGS="$(getopt -o "hqv" -l "help,quiet,verbose,version" \
    -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Convert .wav files to .flac and keep all metadata + verify that the file 
uncompresses to an identical .wav file. If the tiniest difference is 
found, the file is skipped and an error message is written to 
konvflac-error.txt .

Usage: $progname [options] wav_file [...]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

if test -z "$1"; then
    echo $progname: No files specified >&2
    exit 1
fi

tmpuuid=$(suuid -m -t c_konvflac -wa -c "Starting conversion")
test -z "$tmpuuid" && { echo "konvflac: Broken suuid(1)" >&2; exit 1; }
chkfile="/tmp/konvflac.$tmpuuid.tmp"
for curr in "$@"; do
    echo
    echo ======== $(ls -l "$curr")
    rm -f "$chkfile"
    noext="$(basename "$curr" .wav)"
    wavfile="$noext.wav"
    flacfile="$noext.flac"
    test -e "$flacfile" && {
        echo $flacfile: File already exists >&2
        continue
    }
    wavsha=$(sha1sum "$wavfile" | cut -f1 -d ' ')
    wavid=$(finduuid "$wavfile")
    wavid_str=
    test -n "$wavid" && wavid_str=" (File ID $wavid)"
    # FIXME: Kludgy grep
    flac -T FILEID=$(
        suuid -m -t encode,c_konvflac -wa \
        -c "Converting $wavfile$wavid_str to flac"
    ) --keep-foreign-metadata "$wavfile" 2>&1 |
        grep -v \
            -e "keep-foreign-metadata is a new feature" \
            -e "2000,2001,2002,2003,2004,2005,2006,2007" \
            -e "2000-2009, 2011-2013" \
            -e "flac comes with ABSOLUTELY NO WARRANTY" \
            -e "welcome to redistribute it under certain conditions" \
            -e '^$'
    flac -d -o "$chkfile" --keep-foreign-metadata "$flacfile" 2>&1 |
        grep -v \
            -e "keep-foreign-metadata is a new feature" \
            -e "2000,2001,2002,2003,2004,2005,2006,2007" \
            -e "2000-2009, 2011-2013" \
            -e "flac comes with ABSOLUTELY NO WARRANTY" \
            -e "welcome to redistribute it under certain conditions" \
            -e '^$'
    flacsha=$(sha1sum "$chkfile" | cut -f 1 -d ' ')
    if test "$wavsha" = "$flacsha"; then
        echo Verification OK
        rm -vf "$wavfile"
    else
        echo ==== ENCODING ERROR ====
        echo "$noext" >>konvflac-error.txt
    fi
done
