#!/usr/bin/perl -w

#=======================================================================
# $Id$
# [Description]
#
# Character set: UTF-8
# ©opyleft 2004– Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License, see end of file for legal stuff.
#=======================================================================

use strict;
use Getopt::Long;

$| = 1;

our ($opt_help) =
    (        0);

my $VERSION = "0.0";

our $progname = $0;
$progname =~ s#^.*/(.*?)$#$1#;

my $rcs_id = '$Id$';
my $id_date = $rcs_id;
$id_date =~ s/^.*?\d+ (\d\d\d\d-.*?\d\d:\d\d:\d\d\S+).*/$1/;

Getopt::Long::Configure("bundling");
GetOptions(
    "help|h"       => \$opt_help
) || die("$progname: Option error. Use -h for help.\n");

$opt_help && usage(0);

print(<<END);
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="no" lang="no">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Pictures from the Skolelinux developer gathering in Bergen, Norway, 2005-06</title>
    <style type="text/css">
      <!--
      body { background-color: white; color: black; font-family: sans-serif; }
      a:link { color: blue; background-color: white; }
      a:visited { color: maroon; background-color: white; }
      a:active { color: fuchsia; background-color: white; }
      h1 { text-align: center; font-size: 100%; font-weight: bold; }
      table.main { margin: 0 auto; }
      td.head { text-align: center; vertical-align: middle; }
      td.image { text-align: center; vertical-align: middle; }
      td.text { text-align: center; vertical-align: top; font-size: 80%; }
      td.lefticon { text-align: center; vertical-align: middle; font-size: 80%; }
      td.righticon { text-align: center; vertical-align: middle; font-size: 80%; }
      td.footer { text-align: center; vertical-align: top; font-size: 100%; }
      -->
    </style>
    <meta name="author"
          content="Øyvind A. Holm — sunny\@sunbase.org" />
    <meta name="copyright"
          content="©2005 Øyvind A. Holm" />
    <link rev="made" href="mailto:sunny\@sunbase.org" />
  </head>
  <body>

    <table class="main" cellpadding="10" cellspacing="0" border="1">
    <tr>
      <td class="head" colspan="4">
        <h1>Skolelinux developer gathering in Bergen, Norway 2005-06</h1>
      </td>
    </tr>
END

my $Count = 0;

for my $Curr (@ARGV) {
    if (!$Count) {
      print("      <tr>\n");
    }
    print(<<END);
        <td>
          <table width="100%" cellpadding="2" cellspacing="0" border="0">
            <tr>
              <td class="image" colspan="2">
                <img src="120x160/$Curr" width="160" height="120" alt="$Curr" />
              </td>
            </tr>
            <tr>
              <td class="text">
                [<a href="2592x1944/$Curr">2592x1944</a>]<br />
                [<a href="640x480/$Curr">640x480</a>]
              </td>
              <td class="text">
                [<a href="800x600/$Curr">800x600</a>]<br />
                [<a href="120x160/$Curr">120x160</a>]
              </td>
            </tr>
          </table>
        </td>
END
    $Count++;
    if ($Count > 3) {
        print("      </tr>\n");
        $Count = 0;
    }
}

print(<<END);
      <tr>
        <td colspan="4">
          <table cellpadding="5" cellspacing="0" border="0">
            <tr>
              <td class="lefticon">
                <a href="http://validator.w3.org/check?uri=referer"><img src="http://www.w3.org/Icons/valid-xhtml10.png" alt="Valid XHTML 1.0" width="88" height="31" style="border: 0;" /></a>
              </td>
              <td class="footer" colspan="2" width="100%">
                ©2005 Øyvind A. Holm &lt;sunny\@sunbase.org&gt;<br />
                Licensed under the <a href="LICENSE.txt">GNU Free Documentation License</a>.
              </td>
              <td class="righticon">
                <a href="http://jigsaw.w3.org/css-validator/check/referer"><img src="http://www.w3.org/Icons/valid-css.png" alt="Valid CSS" width="88" height="31" style="border: 0;" /></a>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
END

sub usage {
    # Send the help message to stdout {{{
    my $Retval = shift;
    print(<<END);

$progname v$VERSION -- $id_date

Usage: $progname [options] [file [files [...]]]

Options:

-h, --help  Show this help.

END
    exit($Retval);
    # }}}
}

__END__

# Plain Old Documentation (POD) {{{

=pod

=head1 NAME



=head1 REVISION

$Id$

=head1 SYNOPSIS



=head1 DESCRIPTION



=head1 OPTIONS

=over 4

=item B<-h>, B<--help>

Print a brief help summary.

=back

=head1 BUGS



=head1 AUTHOR

Made by Øyvind A. Holm S<E<lt>sunny _AT_ sunbase.orgE<gt>>.

=head1 COPYRIGHT

Copyleft © Øyvind A. Holm &lt;sunny@sunbase.org&gt;
This is free software; see the file F<COPYING> for legalese stuff.

=head1 LICENCE

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2 of the License, or (at your 
option) any later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

=head1 SEE ALSO

=cut

# }}}

# vim: set fenc=UTF-8 ft=perl fdm=marker ts=4 sw=4 sts=4 et fo+=w :
# End of file $Id$
