#!/bin/bash

#=======================================================================
# lag_linker
# File ID: 578c1f6c-5d3e-11df-ba31-90e6ba3022ac
# Lager symlinker i current dir til alle filer som ligger nedenfor i 
# treet.
#=======================================================================

for f in `find -type f | ns`; do
    ln -sv $f `echo $f|tr / _|cut -c 3-`
done
