#!/bin/bash

#=======================================================================
# $Id$
# Mekker ihop ny, fin Vim.
#=======================================================================

lv_lockdir=$HOME/.lag_vim.LOCK

function usage() {
    cat <<END

Syntax: lag_vim [valg]

Mekker ihop ny, fin Vim.

Valg (må være spesifisert alfabetisk):

-f  Fjern lockdir før man peiser videre.
-h  Skriv denne hjelpen. Må være første parameter.
-l  Lokal laging, ikke kjør update_vim-clean (CVS-oppdatering)
-p  Ikke patch filene
-x  Lag gvim med X og saker. Standard oppførsel er å ikke lage med X, 
    for det er som kjent et delay i begynnelsen hvis det er manko på 
    X-forbindelse, og Vimmene har en tendens til å daue når X stoppes.

END
    exit 0
}

[ "$1" = "-h" ] && { usage; }

[ "$1" = "-f" ] && { rmdir $lv_lockdir 2>/dev/null; shift; }
mkdir $lv_lockdir || { echo "lag_vim: $lv_lockdir: Lockdir eksisterer, avbryter." >&2; exit 1; }

[ "$1" = "-l" ] && { bruk_lokal=1; shift; }
unset ingen_patch
[ "$1" = "-p" ] && { ingen_patch=-p; shift; }
[ "$1" = "-x" ] && { med_x=1; shift; }

if [ "$bruk_lokal" != "1" ]; then
    update_vim-clean
fi

mincvs_vim $ingen_patch || { echo "Et eller annet speist skjedde med mincvs_vim. Kreperer." >&2; rmdir $lv_lockdir; exit 0; }

vimcompdir=$HOME/src/other/vim/vim
cd $vimcompdir || { echo "cd $vimcompdir; Ånn ðe tryn." >&2; rmdir $lv_lockdir; exit 0; }

x_flags="--enable-gui=no --without-x"
vim_size=huge

if [ -e $HOME/.petronas.mrk -o -e $HOME/.vagabond.mrk -o -e $HOME/.solsje.mrk ]; then
    echo ======== Man er på petronas, vagabond eller solsje. Lag lokal vim.
    vimdir=$HOME/local/prg/vim
    [ -e $HOME/.vagabond.mrk ] && vim_size=normal
else
    vimdir=/usr/local/prg/vim
    if [ "$med_x" = "1" ]; then
        echo ======== Fikk beskjed om å lage Vim med X og gode greia
        x_flags="--with-x --enable-gui=gtk"
    fi
fi

echo -e "======== ./configure --prefix=$vimdir --with-features=$vim_size --enable-multibyte $x_flags \x7B\x7B\x7B"
CFLAGS=-g
./configure --prefix=$vimdir --with-features=$vim_size --enable-multibyte $x_flags
echo -e "======== ./configure --prefix=$vimdir --with-features=$vim_size --enable-multibyte $x_flags \x7D\x7D\x7D"

echo -e "======== make \x7B\x7B\x7B"
make
echo -e "======== make \x7D\x7D\x7D"

if [ -e $HOME/.petronas.mrk -o -e $HOME/.vagabond.mrk -o -e $HOME/.solsje.mrk ]; then
    # installcmd="rm -rf $vimdir && make install"
    echo Vi er på petronas, vagabond eller solsje, så vi nøyer oss med:
else
    # installcmd="su -c \"rm -rf $vimdir && make install\""
    echo Hvis det gikk bra, er det på tide å bli root, og...
fi
echo "cd $vimcompdir && rm -rf $vimdir && make install && cp -vp src/vim $vimdir/bin/"

rmdir $lv_lockdir

# vim: set ts=4 sw=4 sts=4 et fenc=utf8 :
