#!/bin/bash

#=======================================================================
# list-extensions
# File ID: eeac3f34-031b-11e5-aec1-2330d30b8995
#
# Read filenames or paths from stdin and output a list of used 
# extensions, sorted by frequency.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=list-extensions
VERSION=0.1.0

if test "$1" = "--version"; then
    echo $progname $VERSION
    exit 0
fi

if test "$1" = "-h" -o "$1" = "--help"; then
    cat <<END

Read filenames or paths from stdin and output a list of used extensions, 
sorted by frequency.

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  --version
    Print version information.

END
    exit 0
fi

perl -pe 's/^.*\/(.+?)$/$1/' |
    grep '\.' |
    rev |
    cut -f 1 -d . |
    rev |
    sort |
    uniq -c |
    sort -n
