#!/bin/sh

# $Id$

logdir=$HOME/log

[ -d $logdir ] || mkdir -p logdir || { echo "mkdir $logdir: På trynet" >&2; exit 1; }
[ -x /usr/sbin/cronolog ] || { echo "Fant ikke /usr/sbin/cronolog, avbryter." >&2; exit 1; }

[ -r $logdir/.disks ] || { echo "$logdir/.disks finnes ikke, avbryter." >&2; exit 1; }

df -P `cat $logdir/.disks` | grep / | perl -pe 'chomp(my $a = `date -u +"%Y-%m-%dT%H:%M:%SZ"`); s/^/$a /;' | cronolog -z 0 -S $logdir/curr_df $logdir/df/%Y/%Y-%m-%d.df.log
