#!/bin/sh

# $Id: log_df,v 1.3 2003/09/30 06:09:06 sunny Exp $

logdir=$HOME/log

[ -d $logdir ] || mkdir -p logdir || { echo "mkdir $logdir: På trynet" >&2, exit 1; }

lockname=$logdir/df.log.LOCK

[ -r $logdir/.disks ] || { echo "$logdir/.disks finnes ikke, avbryter." >&2; exit 1; }
until mkdir $lockname 2>/dev/null; do
	echo $0: $lockname: Lockdir finnes, avbryter. >&2
	exit 1
done

df `cat $logdir/.disks` | grep / | perl -pe 'my $a = `u`; s/^/$a /;' >>$logdir/df.log

rmdir $lockname
