#!/bin/bash

# $Id$

export LOGDIR=$HOME/log/script
[ -d $LOGDIR/. ] || mkdir -p $LOGDIR || { echo logging: $LOGDIR: Cannot create log directory >&2; exit 1; }
export LDATE=`u`
if [ -z "$1" ]; then
    export LNAME="$LOGDIR/$LDATE"
else
    export LNAME="$LOGDIR/$LDATE.$1"
fi
script -ft $LNAME.scrlog 2>$LNAME.timing
