#!/bin/bash

# $Id$

export LOGDIR=$HOME/log/script
[ -d $LOGDIR/. ] || mkdir -p $LOGDIR || { echo logging: $LOGDIR: Cannot create log directory >&2; exit 1; }
export LDATE=`u`
script -ft $LOGDIR/$LDATE.scrlog 2>$LOGDIR/$LDATE.timing
