#!/bin/bash

#=======================================================================
# ls-broken
# File ID: fe82548a-5d3e-11df-b882-90e6ba3022ac
# Lists broken links. Hacky and has to be tuned for other environments.
#=======================================================================

ls -la --color "$@" | grep ^l | grep '01;05;37;41m'
