#!/usr/bin/perl -w

#========================================================
# $Id$
# Leser filnavn fra stdin eller en fil og skriver ut alle
# som er lesbar. Hvis -u spesifiseres, listes alle som
# IKKE er leselige. Hvis -w skrives, listes alle
# skrivelige/uskrivelige ting ut istedenfor.
#========================================================

use strict;
use Getopt::Std;

our ($opt_u, $opt_w) =
    (     0,      0);

$| = 1;

getopts('uw');

# Gjøres på amøbemåte for å få opp farta.

if ($opt_u) {
	if ($opt_w) {
		while (<>) {
			chomp;
			-w $_ || print("$_\n");
		}
	} else {
		while (<>) {
			chomp;
			-r $_ || print("$_\n");
		}
	}
} else {
	if ($opt_w) {
		while (<>) {
			chomp;
			-w $_ && print("$_\n");
		}
	} else {
		while (<>) {
			chomp;
			-r $_ && print("$_\n");
		}
	}
}
