#!/bin/bash

#=======================================================================
# $Id$
# Konverter greier i ISO-8859-1 til UTF-8 før det vises med w3m(1).
# License: GNU General Public License version 2 or later.
#=======================================================================

if [ "$1" = "" ]; then
	charset=ISO-8859-1
else
	charset=$1
fi

recode $charset..utf-8
