#!/usr/bin/perl -w

# mangefiler
# File ID: 641d045c-5d3f-11df-a680-90e6ba3022ac

use strict;
use File::Path;

my ($a, $b) = (0, 0);
my $Innh = $ARGV[0];

my @arr = qw{

	e
	e/h
	e/h/CVS
	e/h/Desktop
	e/h/Desktop/Trash
	e/h/Mail
	e/h/dagens_orbit
	e/h/dbk
	e/h/dbk/2001
	e/h/dbk/2001/CVS
	e/h/dbk/2002
	e/h/dbk/2002/CVS
	e/h/dbk/2003
	e/h/dbk/2003/CVS
	e/h/dbk/2004
	e/h/dbk/2004/CVS
	e/h/dbk/CVS
	e/h/depot
	e/h/depot/CVSROOT
	e/h/depot/CVSROOT/Emptydir
	e/h/devtodo
	e/h/div
	e/h/div/lysaar
	e/h/dl
	e/h/dl/amaya
	e/h/doc
	e/h/etc
	e/h/fra_recbb
	e/h/fra_recbb/r0tter
	e/h/freebsd
	e/h/hege-diskett
	e/h/lock
	e/h/lock/dev
	e/h/lock/dev/pts
	e/h/lock/dev/pts/1
	e/h/lock/dev/pts/2
	e/h/lock/dev/pts/3
	e/h/lock/dev/pts/5
	e/h/lock/dev/pts/6
	e/h/lock/dev/pts/8
	e/h/lock/dev/pts/9
	e/h/mail
	e/h/mail/CVS
	e/h/mail/lister
	e/h/mail/lister/archive
	e/h/mail/lister/debian
	e/h/mail/lister/gml
	e/h/mail/lister/gml/att-0020
	e/h/mail/lister/gml/att-0098
	e/h/mail/lister/gml/att-0159
	e/h/mail/lister/gml/att-0160
	e/h/mail/lister/gml/att-0173
	e/h/mail/lister/gml/att-0185
	e/h/mail/lister/gml/att-0199
	e/h/merete
	e/h/merete/isdn
	e/h/merete/isdn/prog
	e/h/merete/isdn/spec
	e/h/ny-celestia
	e/h/ny-celestia/celestia
	e/h/ny-celestia/celestia/extras
	e/h/ny-celestia/celestia/extras/data
	e/h/ny-celestia/celestia/extras/extras
	e/h/ny-celestia/celestia/extras/models
	e/h/ny-celestia/celestia/extras/textures
	e/h/pCvs
	e/h/pCvs/p
	e/h/pCvs/p/CVSROOT
	e/h/pCvs/p/CVSROOT/Emptydir
	e/h/pCvs/p/div
	e/h/pCvs/p/div/Attic
	e/h/pCvs/p/div/junenavn
	e/h/pCvs/p/gnupg
	e/h/pCvs/p/gnupg/diskett
	e/h/pCvs/p/k-vask
	e/h/pCvs/p/plan
	e/h/pCvs/p/plan/Attic
	e/h/pCvs/p/regnskap
	e/h/pCvs/p/regnskap/bin
	e/h/pCvs/p/regnskap/kontoutskrifter
	e/h/pCvs/p/story
	e/h/pCvs/p/story/e0fm
	e/h/pub
	e/h/revisionliste_i_anledning_sun-gnupg
	e/h/s2
	e/h/screendumps
	e/h/screendumps/celestia
	e/h/svn
	e/h/svn/test
	e/h/tema
	e/h/test-Svn
	e/h/test-Svn/conf
	e/h/test-Svn/dav
	e/h/test-Svn/db
	e/h/test-Svn/hooks
	e/h/test-Svn/locks
	e/h/test2
	e/h/til_carmbb
	e/h/tmp
	e/h/tmp/carmbb-gpg
	e/h/tmp/coredump
	e/h/tmp/cr
	e/h/tmp/cr/00
	e/h/tmp/cr/00/CVS
	e/h/tmp/cr/00/src
	e/h/tmp/cr/00/src/CVS
	e/h/tmp/cr/31
	e/h/tmp/cr/31/CVS
	e/h/tmp/cr/31/src
	e/h/tmp/cr/31/src/CVS
	e/h/tmp/cr/32
	e/h/tmp/cr/32/CVS
	e/h/tmp/cr/32/src
	e/h/tmp/cr/32/src/CVS
	e/h/tmp/dump
	e/h/tmp/efn-1versjoner
	e/h/tmp/efn-1versjoner/CVS
	e/h/tmp/efn-1versjoner/CVSROOT
	e/h/tmp/efn-1versjoner/CVSROOT/CVS
	e/h/tmp/efn-1versjoner/public
	e/h/tmp/efn-1versjoner/public/CVS
	e/h/tmp/efn-1versjoner/public/ungdom
	e/h/tmp/efn-1versjoner/public/ungdom/CVS
	e/h/tmp/efn-1versjoner/test
	e/h/tmp/efn-1versjoner/test/CVS
	e/h/tmp/ispell
	e/h/tmp/km
	e/h/tmp/kv
	e/h/tmp/mencode
	e/h/tmp/mplayer
	e/h/tmp/mplayer/edlout
	e/h/tmp/p
	e/h/tmp/p-katalog
	e/h/tmp/plakat
	e/h/tmp/sodipodi
	e/h/tmp/sw
	e/h/tmp/test
	e/h/tmp/treebuilder
	e/h/tmp/utf8_vs_utf16
	e/h/tmp/uudev
	e/h/tmp/vektorfont
	e/h/uff
	e/h/vim
	e/h/xmms

};

for (@arr) {
	print("$_/\n");
	if (mkpath($_)) {
		for ($a = 0; $a < 10; $a++) {
			open(FP, ">$_/fukk$a") || die("$_/$a: Laging: $!");
			print(FP $Innh);
		}
	} else {
		warn("mkpath(\"$_\"): $!\n");
	}
}
