#!/bin/bash

#=======================================================================
# $Id$
# Oppdaterer de norske språkfilene i Vim-sourcen.
#=======================================================================

vimdir=$HOME/src/other/vim
osvim=$HOME/src/svn/norwegian_vim/branches/utv/msgs/vim

for f in $vimdir $vimdir/vim.clean $osvim ; do
    [ -d $f/. ] || { echo "$0: $f: Katalogen finnes ikke. Den trenger man." >&2; exit 1; }
done

cd $osvim || { echo "cd $osvim: Gikk på trynet." >&2; exit 1; }
echo -e "======== cd $osvim; svn up \x7B\x7B\x7B"
svn up
echo -e "\x7D\x7D\x7D"

cd $vimdir || { echo "cd $vimdir: Gikk på trynet." >&2; exit 1; }
[ -d vim/. ] || mkdir vim || { echo "mkdir vim gikk te hælvete." >&2; exit 1; }
echo -e "======== cd $vimdir; rsync -av --delete vim.clean/ vim \x7B\x7B\x7B"
rsync -av --delete vim.clean/ vim
echo -e "\x7D\x7D\x7D"

echo -e "======== rsync -av $osvim/ vim \x7B\x7B\x7B"
rsync -av $osvim/ vim
echo -e "\x7D\x7D\x7D"

# vim: set ts=4 sw=4 sts=4 et fo+=w fenc=utf8 :
