#!/bin/bash

# $Id: mincvs_vim,v 1.3 2004/02/09 04:05:38 sunny Exp $

vimdir=$HOME/src/other/vim
vimlinks=$HOME/vim
osvim=$HOME/src/cvs/norwegian_vim/msgs/vim

cd $osvim || { echo "cd $osvim: Gikk på trynet." >&2; exit 1; }
echo "======== cd $osvim; cvs -q upd -dA -r official_vim"
cvs -q upd -dA -r official_vim
cd $vimdir || { echo "cd $vimdir: Gikk på trynet." >&2; exit 1; }
[ -d vim ] || mkdir vim || { echo "mkdir vim: Gikk te hælvete." >&2; exit 1; }
echo "======== cd $vimdir; rsync -av --delete vim.clean/ vim"
rsync -av --delete vim.clean/ vim

for f in runtime/lang runtime/tutor src/po; do
	echo "======== Ordner $f"
	if [ ! -e $f/CVS_orig ]; then
		mv -v vim/$f/CVS vim/$f/CVS_orig
	fi
	cp -av $osvim/$f/CVS vim/$f
done

cd $vimlinks || { echo "cd $vimlinks: Gikk på trynet."; exit 1; }
echo "======== cd $vimlinks; cvs -q upd -dA -r utv [a-z]*"
cvs -q upd -dA -r utv [a-z]*
