#!/usr/bin/perl -w

# $Id: mixline,v 1.1 2001/03/08 03:16:53 sunny Exp $
# Blander linjer tilfeldig.

use strict;

my @Linjer = <>;

mix_array(\@Linjer);

foreach(@Linjer) {
	print;
}

sub mix_array {
	my $array = shift;
	my $i;
	for ($i = @$array; --$i; ) {
		my $j = int rand ($i+1);
		next if $i == $j;
		@$array[$i,$j] = @$array[$j,$i];
	}
} # mix_array()
