#!/usr/bin/perl -w

# mixline
# File ID: b1e95adc-5d3f-11df-b77c-90e6ba3022ac
# Blander linjer tilfeldig.

use strict;

my @Linjer = <>;

mix_array(\@Linjer);

foreach(@Linjer) {
	print;
}

sub mix_array {
	my $array = shift;
	my $i;
	for ($i = @$array; --$i; ) {
		my $j = int rand ($i+1);
		next if $i == $j;
		@$array[$i,$j] = @$array[$j,$i];
	}
} # mix_array()
