#!/usr/bin/perl

# $Id: mkd,v 1.1 2000/04/03 14:31:04 sunny Exp $
# Konverterer datoer til dbk-link.

while (<>) {
	s!([12]\d\d\d)([/\-])(\d\d)([/\-])(\d\d)!<a href="../$1/$1$3$5.html">$1$2$3$4$5</a>!g;
	s!([12]\d\d\d)(\d\d)(\d\d)(T\d+)(Z?)!<a href="../$1/$1$2$3.html">$1$2$3$4$5</a>!g;
	print;
}
