#!/bin/bash

#=======================================================================
# $Id$
# Creates Files.md5 and Files.sha1 in current directory.
#=======================================================================

lockname=mkFiles.lock
until mkdir $lockname 2>/dev/null; do
	echo $0: $lockname: Waiting for lock... >&2
	sleep 5
done

find -type f -print0 | LC_COLLATE=C sort -z | xargs -0 smsum -m | grep -v '  \./Files\.smsum' >Files.smsum
echo mkFiles: Done.

rmdir $lockname
