#!/bin/bash

#=======================================================================
# $Id$
# Creates Files.smsum in current directory.
#=======================================================================

lockname=mkFiles.lock
until mkdir $lockname 2>/dev/null; do
	echo $0: $lockname: Waiting for lock... >&2
	sleep 5
done

echo \# `suuid -t mkfiles -c "mkFiles i $(hostname):$(/bin/pwd)"` >Files.smsum
find -type f -print0 | \
    grep -zv '/\.svn/' | \
    LC_COLLATE=C sort -z | \
    grep -zv -e '^\./Files\.smsum$' | \
    xargs -0 smsum -m >>Files.smsum
    echo -n "# " >>Files.smsum
    echo smsum:`smsum <Files.smsum` >>Files.smsum
echo mkFiles: Done.

rmdir $lockname
