#!/bin/bash

#=======================================================================
# mobilstripp
# File ID: 81a4b5e0-cb0b-11e3-8632-000df06acc56
#
# Strip irrelevant stuff from nf list of mobile files
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=mobilstripp
VERSION=0.1.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Strip irrelevant stuff from nf list of mobile files

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

grep -i -E -e '\.(flac|gz|jpeg|jpg|m4a|mp3|mp4|pdf|pgn|png|wav)' \
-e /SMSBackupRestore/ | \
grep -v \
-e /Actionmemo/ \
-e /Android/data/com\\.andrewshu\\.android\\.redditdonation/cache/prefetch/ \
-e /Android/data/com\\.bambuna\\.podcastaddict/files/podcast/thumbnails/ \
-e /Android/data/com\\.dropbox\\.android/cache/ \
-e /Android/data/com\\.dropbox\\.android/cache/thumbs/ \
-e /Android/data/com\\.dropbox\\.android/files/scratch/ \
-e /Android/data/com\\.evernote/files/announcements/ \
-e /Android/data/com\\.google\\.android\\.apps\\.docs/files/pinned_docs_files_do_not_edit/ \
-e /Android/data/com\\.google\\.android\\.gms/files/ \
-e /Android/data/com\\.google\\.earth/cache/ \
-e /Android/data/com\\.gopro\\.smarty/cache/ \
-e /Android/data/com\\.handmark\\.tweetcaster/cache/ \
-e /Android/data/com\\.nianticproject\\.ingress/cache/ \
-e /Android/data/com\\.rovio\\.angrybirdsspace\\.ads/cache/sessions/ \
-e /Android/data/com\\.samsung\\.android\\.app\\.episodes/cache/thumbnail \
-e /Android/data/com\\.samsung\\.android\\.app\\.episodes/files/album/ \
-e /Android/data/com\\.samsung\\.android\\.snote/cache/sstream_cache/ \
-e /Android/data/com\\.sec\\.android\\.app\\.sbrowser/TabManager/ \
-e /Android/data/com\\.sec\\.android\\.app\\.sbrowser/files/Pictures/com\\.sec\\.android\\.app\\.sbrowser/TabManager/ \
-e /Android/data/com\\.sec\\.android\\.app\\.shealth/cache/ \
-e /Android/data/com\\.sec\\.everglades/Files/icons/ \
-e /Android/data/com\\.touchtype\\.swiftkey/files/ \
-e /Android/data/com\\.tripadvisor\\.tripadvisor/files/MapResources/ \
-e /Android/data/dentex\\.youtube\\.downloader/files/cache/ \
-e /Android/data/org\\.videolan\\.vlc/cache/art/ \
-e /Android/data/reddit\\.news/cache/ \
-e /BeyondPod/Podcasts/ \
-e /Camera360/TempData/ \
-e /Camera360/www/demo/ \
-e /Camera360/www/images/ \
-e /Camera360/www/scene/ \
-e /Camera360/www/skin/ \
-e /DCIM/\\.thumbnails/ \
-e /DoggCatcher/EpisodeEnclosures/ \
-e /DoggCatcher/PodcastImages/ \
-e /QrDroid/tmp/ \
-e /UnityAdsVideoCache/ \
-e /\\.ActionMemo/ \
-e /\\.cgeo/ \
-e /\\.samsungvideohub/cache/ \
-e /annex/mobile/ \
-e /foursquare/cache/ \
-e /foursquare/category_cache/ \
-e /foursquare/photo_cache/ \
-e \\.pcg\$ \
-e ☠_her_har_vi_slutten | less
