#!/bin/bash

#=======================================================================
# mobilstripp
# File ID: 81a4b5e0-cb0b-11e3-8632-000df06acc56
# Strip irrelevant stuff from nf list of mobile files
# License: GNU General Public License version 3 or later.
#=======================================================================

grep -i -E -e '\.(flac|gz|jpeg|jpg|m4a|mp3|mp4|pdf|pgn|png|wav)' \
-e /SMSBackupRestore/ | \
grep -v \
-e /Actionmemo/ \
-e /Android/data/com\\.andrewshu\\.android\\.redditdonation/cache/prefetch/ \
-e /Android/data/com\\.bambuna\\.podcastaddict/files/podcast/thumbnails/ \
-e /Android/data/com\\.dropbox\\.android/cache/ \
-e /Android/data/com\\.dropbox\\.android/cache/thumbs/ \
-e /Android/data/com\\.dropbox\\.android/files/scratch/ \
-e /Android/data/com\\.evernote/files/announcements/ \
-e /Android/data/com\\.google\\.android\\.apps\\.docs/files/pinned_docs_files_do_not_edit/ \
-e /Android/data/com\\.google\\.android\\.gms/files/ \
-e /Android/data/com\\.google\\.earth/cache/ \
-e /Android/data/com\\.gopro\\.smarty/cache/ \
-e /Android/data/com\\.handmark\\.tweetcaster/cache/ \
-e /Android/data/com\\.nianticproject\\.ingress/cache/ \
-e /Android/data/com\\.rovio\\.angrybirdsspace\\.ads/cache/sessions/ \
-e /Android/data/com\\.samsung\\.android\\.app\\.episodes/files/album/ \
-e /Android/data/com\\.samsung\\.android\\.snote/cache/sstream_cache/ \
-e /Android/data/com\\.sec\\.android\\.app\\.sbrowser/TabManager/ \
-e /Android/data/com\\.sec\\.android\\.app\\.sbrowser/files/Pictures/com\\.sec\\.android\\.app\\.sbrowser/TabManager/ \
-e /Android/data/com\\.sec\\.everglades/Files/icons/ \
-e /Android/data/com\\.touchtype\\.swiftkey/files/ \
-e /Android/data/com\\.tripadvisor\\.tripadvisor/files/MapResources/ \
-e /Android/data/dentex\\.youtube\\.downloader/files/cache/ \
-e /Android/data/org\\.videolan\\.vlc/cache/art/ \
-e /Android/data/reddit\\.news/cache/ \
-e /BeyondPod/Podcasts/ \
-e /Camera360/TempData/ \
-e /Camera360/www/demo/ \
-e /Camera360/www/images/ \
-e /Camera360/www/scene/ \
-e /Camera360/www/skin/ \
-e /DCIM/\\.thumbnails/ \
-e /DoggCatcher/EpisodeEnclosures/ \
-e /DoggCatcher/PodcastImages/ \
-e /QrDroid/tmp/ \
-e /UnityAdsVideoCache/ \
-e /\\.ActionMemo/ \
-e /\\.cgeo/ \
-e /\\.samsungvideohub/cache/ \
-e /annex/mobile/ \
-e /foursquare/cache/ \
-e /foursquare/category_cache/ \
-e /foursquare/photo_cache/ \
-e \\.pcg\$ \
-e ☠_her_har_vi_slutten | less
