#!/bin/bash

#=======================================================================
# multiapt
# File ID: ffa9a0ac-28af-11e4-9136-c80aa9e67bbd
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

progname=multiapt

if test -e "/gitrepos.txt"; then
    cd /
    git update-dirs $(cat gitrepos.txt) -q -e "git wait-until-clean"
fi

for f in "$@"; do
    cd /etc || { echo $progname: Cannot chdir to /etc >&2; exit 1; }
    echo
    echo apt-get install $f
    apt-get install "$f"
    ciall -d -y apt-get install $f
    if test -e "/gitrepos.txt"; then
        cd /
        git update-dirs $(cat gitrepos.txt) -e "ciall -y apt-get install $f"
    fi
done
