#!/usr/bin/perl

# $Id: mvdirnewest,v 1.1 1999/02/14 01:35:12 sunny Exp $
# Syntax: $0 directory
# Forandrer navnet på directoryen til den nyeste fila i trestrukturen under.
# Brukes til å lage orden i gamle versjoner av ting som ligger slengende rundt.
#
# (C)opyleft 1999 Øyvind A. Holm <sunny@tritech.no>

my $RetVal;

if ($#ARGV == -1) {
	print <<END;

Syntax: $0 directory [directory [...]]

The program scans the underlying tree structure and renames the directory
to the date of the newest file.
END
	exit 1;
}

die("$0: Unknown version of find(1) or program not found\n") unless (`find --version` =~ /GNU find/);

foreach (@ARGV) {
	$RetVal ||= &process_dir($_);
}

exit $RetVal;

sub process_dir {
	my $dir_name = shift;
	unless (-d $dir_name) {
		warn("$0: $dir_name: Directory not found\n");
		return 1;
	}
	my $newest_date = 0;
	my $newest_file = "";

	# FIXME: Dette med find er midlertidig (og kommer sikkert til å forbli her :)
	my @Files = `find $dir_name -type f`;
	unless (scalar @Files) {
		warn("$0: $dir_name: No files found in directory\n");
		return 1;
	}
	foreach (@Files) {
		chomp;
		my $file_name = $_;
		my @stat_array;
		unless (@stat_array = stat($file_name)) {
			warn("$0: $file_name: Can't stat file: $!\n");
			return 1;
		}
		my $file_date = $stat_array[9];
		if ($file_date > $newest_date) {
			$newest_date = $file_date;
			$newest_file = $file_name;
		}
		# printf("$file_name: %s\n", &date2str($file_date));
		my $new_name = &date2str($file_date);
	}
	$new_name = sprintf("%s.%s", &date2str($newest_date), $dir_name);
	if (-e $new_name) {
		warn("$0: $new_name: Directory entry already exists, skipping directory $dir_name\n");
		return 1;
	} else {
		# printf("Skulle til å rename(%s, %s)\n", $dir_name, $new_name);
		rename($dir_name, $new_name) || warn("$dir_name: Can't rename directory to $new_name: $!\n");
	}
	return 0;
} # process_dir()

sub date2str {
	@TA = localtime(shift);
	return(sprintf("%04u%02u%02uT%02u%02u%02u", $TA[5]+1900, $TA[4]+1, $TA[3], $TA[2], $TA[1], $TA[0]));
} # date2str()

#### End of file $Id: mvdirnewest,v 1.1 1999/02/14 01:35:12 sunny Exp $ ####
