#!/bin/bash

# $Id: myf,v 1.3 2004/03/01 07:51:59 sunny Exp $
# Nå er jeg lei av mankoen på skikkelig datoformat.

if [ "$1" = "-e" ]; then
	# Bruk epoch-format på datoen (Antall sekunder sia 1970-01-01 00:00:00 GMT)
	shift
	find $* -printf "%T@\t%6s\t%U.%G\t%p\n"
else
	find $* -printf "%TY-%Tm-%Td %TH:%TM:%TS\t%6s\t%U.%G\t%p\n"
fi
