#!/bin/bash

#=======================================================================
# mymkdir
# File ID: cbdb01c6-63be-11e5-84b6-fefdb24f8e10
#
# Create a directory using sudo(8) where the current user don't have 
# permission to do so, and set the owner of that directory to the 
# current user.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=mymkdir
VERSION=0.2.1

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Create a directory using sudo(8) where the current user don't have 
permission to do so, and set the owner of that directory to the current 
user.

Usage: $progname [options] DIRECTORY

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

user="$(whoami)"

if test "$user" = "root"; then
    echo $progname: You are root, should be run as a regular user
    exit 1
fi

sudo mkdir -vp "$1"
sudo chown -v "$user"."$user" "$1"
sudo -k
