#!/bin/bash

#=======================================================================
# n0
# File ID: 72d76968-5d41-11df-8bdf-90e6ba3022ac
# Stopper nettverket på carmbb.
#=======================================================================

if [ -e /carmbb.mrk ]; then
    killall ssh
    /etc/init.d/networking stop
else
    echo "$0: Må være på carmbb" >&2
    exit 1
fi
