#!/bin/bash

#=======================================================================
# n1
# File ID: 7b9909da-5d41-11df-aa28-90e6ba3022ac
# Kjører opp nettverket på carmbb.
#=======================================================================

if [ -e /carmbb.mrk ]; then
    killall ssh
    /etc/init.d/networking start
else
    echo "$0: Må være på carmbb" >&2
    exit 1
fi
