#!/bin/bash

#=======================================================================
# $Id$
# File ID: a24f4cb6-f743-11dd-b795-000475e441b9
# Standardgenerering av filmer til Nokiaen.
# License: GNU General Public License version 2 or later.
#=======================================================================

[ "$1" = "-h" -o "$1" = "--help" ] && { echo; echo "n95film: No help available, but here's the source code:"; echo; cat $0; exit; }
[ -d mp4/. ] || mkdir mp4 || { echo mp4: Cannot create directory; exit 1; }
export ENC=$HOME/bin/enc-mp4
# FIXME: Dirty, men det funker foreløpig.
export encver=`svn --xml info $ENC | xf | grep '<commit revision' | perl -pe 's/^.*"(\d+)".*$/$1/'`
for f in "$@"; do
    ~/bin/enc-mp4 -vv -o "mp4/$f.mp4" -c $(suuid -t n95film -w eo -c "enc-mp4 r$encver på $f ($(smsum -vv "$f" | cut -f 1))") "$f";
done
