#!/bin/sh

# $Id: nets,v 1.1 2002/03/08 01:02:32 sunny Exp $
# Hælvetes føkkings Netscrape kødder seg bestandig, så her gjør vi kort
# prosess og myrder driten.

if [ -e /sunba.mrk ]; then
	killall -9 communicator-smotif.real
else
	killall -9 netscape-navigator
fi
