#!/bin/sh

# $Id: nets,v 1.3 2003/01/07 17:55:41 sunny Exp $
# Hælvetes føkkings Netscrape kødder seg bestandig, så her gjør vi kort
# prosess og myrder driten.

if [ -e /sunba.mrk ]; then
	killall -9 communicator-smotif.real
else
	killall -9 netscape-navigator netscape-communicator communicator-smotif.real
fi
