#!/bin/sh

#====================================================
# Latskapen lenge leve.
# $Id: netscape,v 1.4 2001/09/16 17:11:09 sunny Exp $
#====================================================

cd
if [ -e /sunba.mrk ]; then
	/usr/X11R6/bin/netscape &
else
	netscape-navigator &>/dev/null &
fi
cd -
