#!/bin/sh

#====================================================
# Latskapen lenge leve.
# $Id: netscape,v 1.5 2001/10/27 15:43:50 sunny Exp $
#====================================================

cd
if [ -e /sunba.mrk ]; then
	/usr/X11R6/bin/netscape $* &
else
	netscape-navigator $* &>/dev/null &
fi
cd -
