#!/bin/sh

# $Id: nets,v 1.4 2003/02/20 07:39:25 sunny Exp $
# Hælvetes føkkings Netscrape kødder seg bestandig, så her gjør vi kort
# prosess og myrder driten.

killall -9 netscape-navigator netscape-communicator communicator-smotif.real navigator-smotif.real
