#!/bin/sh

# $Id: nettradio,v 1.3 2003/03/15 03:50:25 sunny Exp $
# Spiller av nettradioer -- eller rettere sagt sender en
# .ogg-strøm som kan lagres og tailes eller trøkkes inn i ogg123.

case "$1" in
	p2)
		radio=http://radio.hiof.no:8000/nrk-p2-128
		mpg321 -q $radio --wav - - | oggenc -Q -q-1 -
		;;
	p3|petre)
		# radio=http://radio.hiof.no:8000/nrk-petre-128
		radio=http://radio.hiof.no:8000/nrk-petre-128
		sget http://radio.hiof.no:8000/nrk-petre-128 | buffer -p 10 | mpg321 -v -
		# tee $HOME/dl/nettradio/nrk_p3.`u`.mp3 | buffer -p 5 | mpg321 -v -
		# mpg321 -q --wav - - | oggenc -Q -q1 -
		# mpg321 -q $radio --wav - | oggenc -Q -q-1 -
		;;
	bbc1q0)
		radio=http://ogg.bbc.co.uk:8001/radio1_low.ogg
		;;	
	bbc1|bbc1-q3)
		radio=http://ogg.bbc.co.uk:8001/radio1_high.ogg
		;;
	bbc6-q0)
		radio=http://ogg.bbc.co.uk:8001/6music_low.ogg
		;;
	bbc6|bbc6-q3)
		radio=http://ogg.bbc.co.uk:8001/6music_high.ogg
		;;
	*)
		echo "$0: Mangler radionavn" >&2
		;;
esac

wget -O - -o /dev/null $radio
