#!/bin/sh

# $Id: nettradio,v 1.1 2002/04/15 02:30:57 sunny Exp $
# Spiller av nettradioer -- eller rettere sagt sender en
# .ogg-strøm som kan lagres og tailes eller trøkkes inn i ogg123.

wget -O - -o /dev/null http://ogg.bbc.co.uk:8001/6music.ogg
