#!/bin/bash

#=======================================================================
# $Id$
# File ID: b08ec95a-f743-11dd-a59e-000475e441b9
# Sjekker om den NextGenTel-forbindelsen er herpa
# License: GNU General Public License version 2 or later.
#=======================================================================

res=`sget http://nett.ba.no/ngt/test | tohex | rmspcall`

logfile=~/ngt-fucked/logg.txt
echo -n `u` "Fikk \"$res\". Det vil si at den er " >>$logfile
if [ "$res" = "0a 00 00 02" ]; then
    echo OK. Fantastisk. >>$logfile
    tail -1 $logfile
    exit 0
else
    echo herpa. Fuck you. >>$logfile
    tail -1 $logfile
    exit 1
fi
