#!/bin/sh

#=======================================================================
# $Id$
# Reads a bunch of filenames from stdin or files specified on the 
# command line and strips .svn directories away. Example of really 
# cleaning up the working copy:
#   cd /top/of/working/copy
#   find . -type f | nosvn | xargs rm
#   svn revert -R .
#=======================================================================

cat $* | egrep -v '/\.svn(/|$)'
