#!/bin/bash

#=======================================================================
# oggname
# File ID: dd535e78-5d41-11df-937b-90e6ba3022ac
#
# Skifter navn på musikkfiler til sånn som jeg liker det:
# Bandnavn_-_Platetittel_-_Sangnummer_-_Sangtittel.ext
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=oggname
VERSION=0.2.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

patt='*.flac *.mp3 *.ogg'
echo ==== Space til understrek
prename -v 's/ /_/g' $patt | perl -pe 's/ renamed as /\n/'
echo ==== Alle bokstaver til små
prename -v 'y/[A-Z]/[a-z]/' $patt | perl -pe 's/ renamed as /\n/'
echo ==== Forbokstaver i bandnavn til stor
prename -v 's/^(.*?)_([a-z])(.*?)_-_/$1_\U$2\E$3_-_/g' $patt | perl -pe 's/ renamed as /\n/'
echo ==== Første bokstav i filnavnet til stor
prename -v 's/^([a-z])/\U$1\E/' $patt | perl -pe 's/ renamed as /\n/'
echo ==== Første bokstaven i sangtittelen til stor
# prename -v 's/^(.*)_-_([a-z])(.*?)$/$1_-_\U$2\E$3/' $patt | perl -pe 's/ renamed as /\n/'
prename -v 's/_-_([a-z])/_-_\U$1\E/g' $patt | perl -pe 's/ renamed as /\n/'
echo ==== «I» til stor bokstav
prename -v 's/_i_/_I_/g' $patt
echo === Apostrofer til U+2019
prename -v "s/'/’/g" $patt
