#!/bin/bash

#=======================================================================
# pakk_logg
# File ID: 7bd794f8-5551-11e0-942f-b7ae6f27caa2
# Compress script logs
# License: GNU General Public License version 3 or later.
#=======================================================================

lockdir=~/.pakk_log.lock
mkdir $lockdir || { echo $0: $lockdir: Cannot create lockdir >&2; exit 1; }

myexit() {
    rmdir $lockdir || { echo $0: $lockdir: Cannot remove lockdir >&2; exit 1; }
    exit $1
}
trap "myexit 1" INT TERM

pakklogg() {
    echo Will commit: $(find $1 -printf "%TY-%Tm-%Td %TH:%TM size:%s %p")
    gzip -v $1
    echo
}

cd ~/log/script || { echo $0: ~/log/script: Unable to chdir; exit 1; }
ls *.scrlog *.timing 2>/dev/null | grep -q . || { echo $0: No files found to pack; myexit 0; }
for f in *.scrlog *.timing; do
    file=$f
    uuid=$(echo $f | finduuid)
    ps auxwOT | grep -v "grep $uuid" | grep $uuid | grep -q . || pakklogg $file
done

myexit 0
