#!/usr/bin/perl -w

# $Id: pakkut,v 1.4 2003/06/06 12:11:54 sunny Exp $

use strict;

$| = 1;

open(PipeFP, "| uudecode | gzip -d") or die("$0: Can't open pipe: $!\n");
while (<>) {
	s/[#%";!{}]//g;
	s/^\s+(.*)/$1/;
	print PipeFP $_;
}

close(PipeFP);
