#!/usr/bin/env bash

#=======================================================================
# pakkings
# File ID: c31a44fa-001f-11e5-84cd-1fba44bd8d3d
#
# Unpack all gzip files in a directory tree and move them into one big 
# .tar.gz file. For times when you for example realise you've got more 
# than 39000 IRC logs since 2004. True story.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=pakkings
VERSION=0.2.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        -h|--help) opt_help=1; shift ;;
        -q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        -v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        --version) echo $progname $VERSION; exit 0 ;;
        --) shift; break ;;
        *) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Usage: $progname [options] DIRECTORY [DIRECTORIES [...]]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

for dir in "$@"; do
    test -d "$dir" || { echo $progname: $dir: Not a directory >&2; continue; }
    test -e "$dir.tar.gz" && { echo $progname: $dir.tar.gz already exists >&2; continue; }
    label=$(suuid -t c_$progname -c "$progname: Pack $dir")
    if test -z "$label"; then
        echo $progname: Could not create UUID for tar volume label >&2
        exit 1
    fi
    echo
    if test -n "$(git config --get annex.uuid)"; then
        echo ========= ga edit $dir
        ga edit "$dir"
    fi
    echo ========= gunzip -r $dir
    gunzip -r "$dir"
    echo === tar $dir
    tar czf "$dir.tar.gz" --label=$label --remove-files "$dir"
done
