#!/bin/bash

#=======================================================================
# pakkdir
# File ID: 5818b856-0ba9-11de-b2c1-000475e441b9
#
# Move a whole subdirectory tree into a single .pakka.tar.gz file.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=pakkdir
VERSION=0.1.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Move a whole subdirectory tree into a single .pakka.tar.gz file.

Usage: $progname [options] DIRECTORY [DIRECTORIES [...]]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

for f in $*; do
    echo Pakker $f...

    dir=$f
    targz=$f.pakka.tar.gz

    echo dir = $dir
    echo targz = $targz

    if [ -e $targz ]; then
        echo "$targz finnes allerede" >&2
        exit 1
    fi

    if [ ! -d $dir ]; then
        echo "$dir: Er ikke en dir" >&2
    else
        echo $dir | grep -q / && { echo "$dir: Forbudt med slasher i filnavnet" >&2; exit 1; }

        echo ======= tar czf $targz --remove-files $dir
        uuid=`suuid -t pakkdir --raw -w eo -c "<c_pakkdir> <filename>$targz</filename> <host>$(hostname)</host> <directory>$(/bin/pwd)</directory> </c_pakkdir>"` || { echo $0: suuid error >&2; exit 1; }
        tar czf $targz --remove-files --label=$uuid $dir
        ls -la $targz
        # echo ======= Rensk
        # (cd $dir && find -type d -print0 -depth | xargs -0 rmdir )
        # echo ======= rmdir $dir
        # rmdir $dir
    fi
done
