#!/usr/bin/env perl

# pakkut
# File ID: 096d3c90-5d42-11df-a6c3-90e6ba3022ac

use strict;
use warnings;

$| = 1;

open(PipeFP, "| uudecode | gzip -d") or die("$0: Can't open pipe: $!\n");
while (<>) {
	s/[#%";!{}]//g;
	s/^\s+(.*)/$1/;
	print PipeFP $_;
}

close(PipeFP);
