#!/usr/bin/perl -w

# $Id: perlfold,v 1.1 2003/04/24 19:06:17 sunny Exp $
# Legger inn vim-foldmerker foran og etter stdin. Brukes til å lage
# folder i perlsource.

use strict;

my $Linje = <>;
my $Indent = "";

$Linje =~ /^(\s+)/ && ($Indent = $1);
print("$Indent# \x7B\x7B\x7B\n$Linje");

while (<>) {
	print($_);
}

print("$Indent# \x7D\x7D\x7D\n");
