#!/bin/sh

# $Id: pine-editor,v 1.4 2003/11/24 14:51:30 sunny Exp $

file=$1
tempf=/tmp/pine-editor.$$.tmp

# h2u -l $file >$tempf
# mv $tempf $file
vim -X -f -c "set textwidth=72 syntax=mail expandtab" -w /home/sunny/vimlogg $file
