#!/bin/sh

# ╔══════════════════════════════════════════════════════════════
# ║ $Id: pinefilter,v 1.5 2003/08/11 16:15:55 sunny Exp $
# ║ pine(1) har ikke helt støtte for UTF-8 enda, så meldingene
# ║ filteres gjennom dette scriptet før visning.
# ╚══════════════════════════════════════════════════════════════

charset=$1

iconv -f $charset -t utf-8
