#!/bin/sh

# ╔══════════════════════════════════════════════════════════════
# ║ $Id: pinefilter,v 1.6 2004/01/24 04:57:54 sunny Exp $
# ║ pine(1) har ikke helt støtte for UTF-8 enda, så meldingene
# ║ filteres gjennom dette scriptet før visning.
# ╚══════════════════════════════════════════════════════════════

if [ "$1" = "" ]; then
	charset=ISO-8859-1
else
	charset=$1
fi

recode $charset..utf-8
