#!/bin/bash

#=======================================================================
# $Id$
# Shows translation status of every .po file in subtree.
#=======================================================================

if [ "$1" = "" ]; then
    for f in `find -name '*.po' -type f`; do
        echo $f: `msgfmt -cv -o /dev/null $f 2>&1`
    done
else
    for f in $*; do
        echo $f: `msgfmt -cv -o /dev/null $f 2>&1`
    done
fi
