#!/bin/bash

#=======================================================================
# pols
# File ID: 7e0fab50-5d42-11df-a66c-90e6ba3022ac
# Shows translation status of every .po file in subtree.
#=======================================================================

if [ "$1" = "" ]; then
    for f in `find -name '*.po' -type f`; do
        echo $f: `msgfmt -cv -o /dev/null $f 2>&1`
    done
else
    for f in $*; do
        echo $f: `msgfmt -cv -o /dev/null $f 2>&1`
    done
fi
