#!/bin/bash

#=======================================================================
# posmap
# File ID: 46c65064-61d7-11e5-8232-fefdb24f8e10
#
# Plot GPS tracks around a specific waypoint.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=posmap
VERSION=0.1.0

if test "$1" = "--version"; then
    echo $progname $VERSION
    exit 0
fi

if test "$1" = "-h" -o "$1" = "--help"; then
    cat <<END

Plot GPS tracks around a specific waypoint.

Usage:

  $progname waypoint_name [radius_in_metres]
  $progname --list

Options:

  -h, --help
    Show this help.
  -l, --list
    List all available waypoints.
  --version
    Print version information.

END
    exit 0
fi

name="$1"
if test -z "$name"; then
    echo $progname: No waypoint name specified >&2
    exit 1
fi

if test "$name" = "-l" -o "$name" = "--list"; then
    psql gps -c "COPY (SELECT name FROM wp) TO STDOUT;"
    exit 0
fi

radius=100
test -n "$2" && radius="$2"
echo $progname: radius = $radius metres

tmpfile="/tmp/.posmap.$(date +%s).$$.tmp"
cat <<SQL_END | psql gps >"$tmpfile"
COPY (
    SELECT gpst FROM gpst
        WHERE (coor <-> (
            SELECT coor FROM wayp
                WHERE name = '$1'
                LIMIT 1
            ) < 1.0*$radius/100000
        )
) TO STDOUT;
SQL_END
vg -2 -wd "$tmpfile"
rm "$tmpfile"
