#!/usr/bin/perl

# prearmor
# File ID: 90ae840c-5d42-11df-a554-90e6ba3022ac
# Setter GPG-armor i <p><pre></pre>.

while (<>) {
	s/^-----BEGIN PGP MESSAGE-----$/<p><pre>\n-----BEGIN PGP MESSAGE-----/;
	s/^-----END PGP MESSAGE-----$/-----END PGP MESSAGE-----\n<\/pre>/;
	print;
}
