#!/bin/sh

# $Id: pynt,v 1.3 1999/03/23 13:16:59 sunny Exp $

killall xearth xsnow

# Låst posisjon med Norge lurt plassert
# xearth -nomarkers -bigstars 50 -shift "-275 -162" -sunpos "20 20" -mag 0.5 -once
(xearth -bigstars 50 -shift "-275 -162" -mag 0.5 &) || (echo $0: Kunne ikke starte xearth) >&2

# xsnow -nosanta -notrees &>/dev/null &
(xsnow &>/dev/null &) || (echo $0: Kunne ikke starte xsnow >&2)
