#!/bin/bash

# $Id$
# File ID: 011d0820-fa5d-11dd-a357-0001805bf4b1
# Syntax: radiolagring navn kanal lengde

export PATH=$HOME/bin:$HOME/bin/basnakk:/usr/local/bin:/usr/local/sbin:/bin:/usr/bin:/usr/X11R6/bin:/sbin:/usr/sbin:/usr/games

navn=$1
kanal=$2
lengde=$3

dlfile=`u`.$navn.nrk_$kanal.mp3
uuid=`suuid -t radiolagring -w eo -c "radiolagring $* ($dlfile)"` || { echo "radiolagring: IMPORTANT - suuid error, but will continue" >&2; }
dldir=$HOME/dl/nettradio
logdir=$HOME/log/radiolagring
logfile=$logdir/$uuid.wgetlog

[ -d $logdir/. ] || mkdir -p $logdir || { echo "$0: $logdir: Klarte ikke mkdir" >&2; exit 1; }
timeout $[60*$lengde] wget -U "xmms/1.2.7" -o $logfile -O $dldir/$dlfile http://radio.hiof.no:8000/nrk-$kanal-128
suuid -w o -t radiolagring -c "Download $uuid ferdig."
gzip -q $logfile
