#!/bin/sh

#==============================================================================
# rdbl-luks
# File ID: 979ab972-f909-11ed-aa1e-83850402c3ce
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
#==============================================================================

progname=rdbl-luks
VERSION=0.1.0

cryptsetup luksDump "$1"

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
