#!/usr/bin/env bash

#=======================================================================
# rdbl-midi
# File ID: 833b97b0-eac2-11e5-a78d-02010e0a6634
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=rdbl-midi
VERSION=0.2.0

lilymidi --dump --pretty "$@" | grep -v ^Filename:
