#!/usr/bin/env bash

#=======================================================================
# rdbl-sqlite3
# File ID: 7515bdfa-1872-11e5-aaa8-fefdb24f8e10
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

if test "$(head -c 13 "$1")" != "SQLite format"; then
	cat "$1"
	exit
fi

sqlite3 "$1" .dbinfo
echo
sqlite3 "$1" .dump
