#!/bin/sh

# $Id: remouse,v 1.3 1999/11/08 01:01:09 sunny Exp $

killall gpm
sleep 1
if [ -e /grimme.mrk ]; then
	gpm -t MouseMan
elif [ -e /black.mrk ]; then
	gpm -t ps2
else
	echo $0: Ukjent maskin, kan ikke fyre i gang gpm\(1\) >&2
fi
