#!/bin/sh

# $Id: remouse,v 1.2 1999/05/08 20:35:11 sunny Exp $

killall gpm
sleep 1
if [ -e /grimme.mrk ]; then
	gpm -t bare
elif [ -e /black.mrk ]; then
	gpm -t ps2
else
	echo $0: Ukjent maskin, kan ikke fyre i gang gpm\(1\) >&2
fi
