#!/bin/bash

# rensk
# File ID: d938bc4c-3691-11e4-bdd6-c80aa9e67bbd
# Remove empty directories under current dir

find -depth -type d -print0 | \
  grep -azv -e '/\.svn/' -e '/\.git/' -e '\.lock$' -e '\.LOCK$' | \
  xargs -0 rmdir 2>/dev/null
exit 0
