#!/bin/bash

# $Id$

_tmpfile=/tmp/rensk.$RANDOM.tmp
find . -type d | grep -v '/\.svn' | sort >$_tmpfile
rmdir -p `cat $_tmpfile` 2>/dev/null
diff -U 0 $_tmpfile <(find . -type d | grep -v '\.svn' | sort) | grep '^-\./' | cut -c 2-
rm $_tmpfile
