#!/bin/bash

# $Id$
# Tar full (hikk) backup av svn-repositoryene og legger dem på cindy.

lockdir=/var/lock/reposbackup.LOCK

if [ ! -e /sunba.mrk ]; then
	echo "Kjør den på sunba, for svarte! SUNBA! Kjønnar, kjætting?" >&2
	exit 1
fi

if [ ! -d $HOME/cindy-sunny/svn-backup/. ]; then
	echo "Finner ikke $HOME/cindy-sunny/svn-backup/ , må ha en plass å legge schiten." >&2
	exit 1
fi

cd $HOME/Svn || { echo "cd $HOME/Svn: Gikk så dårlig som det går an." >&2; exit 1; }

until mkdir $lockdir 2>/dev/null; do
	echo "$0: $lockdir: Lockdir existerte, er det en annen som kjører?" >&2
	exit 1
done

for f in *; do
	echo ======= $f
	svnadmin dump --incremental $f | gpg -e -r sunny@sunbase >~/cindy-sunny/svn-backup/`u`.$f.dump.gpg
done

rmdir $lockdir || { echo "Øh.... Klarte ikke rmdir $lockdir" >&2; }
