#!/bin/sh

# $Id: reset,v 1.1 1999/09/20 00:45:18 sunny Exp $
# Fjerner rot med testkattributter i tillegg.

[ -x /usr/bin/reset ] || { echo $0: reset\(1\) ligger ikke under /usr/bin. Kvifor not? >&2; exit 1; }

/usr/bin/reset
printf "\x1b[0m"
