#!/bin/sh

# $Id$
# Fjerner backupfiler i current dir og subdirs.

echo "rm_backup: Fjerner alle med tilde på slutten..."
find . -type f -name '*~' -print0 | xargs -0 rm -v
echo ====================================
echo "rm_backup: Fjerner alle med teit .bak på slutten..."
find . -type f -name '*.bak' -print0 | xargs -0 rm -v
echo ====================================
echo "rm_backup: Fjerner alle som begynner med \".#\" (CVS-backuper)..."
find . -type f -name '.#*' -print0 | xargs -0 rm -v
