#!/bin/sh

# $Id: rm_backup,v 1.4 2003/10/16 05:15:54 sunny Exp $
# Fjerner backupfiler i current dir og subdirs.

find . -type f -name '*~' -print0 | xargs -0 rm -v
find . -type f -name '.#*' -print0 | xargs -0 rm -v
