#!/usr/bin/perl -w

#=======================================================================
# $Id$
# Fjerner XML/HTML/SGML-kommentarer.
# Skal vi GPL’e den? Åja, det gjør vi! ☺
#=======================================================================

use strict;

my $Dat = join("", <>);
$Dat =~ s/<!--(.*?)-->//gs;
print($Dat);
