#!/usr/bin/env bash

#==============================================================================
# run-test
# File ID: a813eb74-2b2c-11e5-b0b2-000df06acc56
#
# Execute a test file and show the first failing test in vimdiff.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=run-test
VERSION=0.1.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
	case "$1" in
		(-h|--help) opt_help=1; shift ;;
		(-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
		(-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
		(--version) echo $progname $VERSION; exit 0 ;;
		(--) shift; break ;;
		(*) echo $progname: Internal error >&2; exit 1 ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Execute a test file and show the first failing test in vimdiff.

Usage: $progname [options] TESTFILE

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
	exit 0
fi

script="$1"
shift
"$script" 2>&1 | gotexp "$@"
vimdiff -c "windo set wrap" got exp
rm got exp

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
