#!/bin/bash

#=======================================================================
# scrdump
# File ID: 64a02bf2-3e32-11de-b61f-000475e441b9
# Skjermdump i X.
#=======================================================================

scrdumpdir=$HOME/annex/opptak/alt/$(date -u +"%Y/%m")

[ -d $scrdumpdir/. ] || mkdir $scrdumpdir || { echo "$0: $scrdumpdir: Cannot create directory" >&2; exit 1; }

TZ=UTC shutter -e --full -o $scrdumpdir/%Y%m%dT%H%M%SZ.$(hostname)-screendump.\$wx\$h.png
