#!/bin/bash

#=======================================================================
# $Id$
# Skjermdump i X.
#=======================================================================

scrdumpdir=$HOME/screendumps

[ -d $scrdumpdir/. ] || mkdir $scrdumpdir || { echo "$0: $scrdumpdir: Cannot create directory" >&2; exit 1; }

# import-programmet hører med til ImageMagick.
import -w root $scrdumpdir/$(date -u +"%Y%m%dT%H%M%SZ").$(hostname)-screendump.png
