#!/bin/bash

#=======================================================================
# $Id$
# [Description]
# License: GNU General Public License version 2 or later.
#=======================================================================

cat "$@" | od -tu1 -An -v | lag3d >/tmp/sjekkrand.tmp

