#!/bin/bash

# sjekksommer
# File ID: d421f5d8-5d43-11df-89d2-90e6ba3022ac

echo ============== $1 $2 $3 ==============
sommer $1 $2 $3 1 59
sommer $1 $2 $3 2 00
sommer $1 $2 $3 2 59
sommer $1 $2 $3 3 00
