#!/bin/bash

#=======================================================================
# sjt
# File ID: 7e4abe36-82bb-11df-b38f-001b243b5bb5
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

ntpdate -q pool.ntp.org
