#!/bin/sh

#==============================================================================
# skriv
# File ID: 2706f4c0-b7bb-11ee-bb6f-83850402c3ce
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=skriv
VERSION=0.0.0

opt_help=0
opt_landscape=0
opt_pretty=0
opt_printer=
opt_quiet=0
opt_two_sided=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-2|--two-sided) opt_two_sided=1; shift ;;
	-P|--printer) opt_printer="$2"; shift 2 ;;
	-h|--help) opt_help=1; shift ;;
	-l|--landscape) opt_landscape=1; shift ;;
	-p|--pretty) opt_pretty=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Usage: $progname [options]

Options:

  -2, --two-sided
    Print on both pages of the paper.
  -h, --help
    Show this help.
  -l, --landscape
    Use landscape format.
  -P DEST, --printer DEST
    Use DEST as print destination.
  -p, --pretty
    Create page headers and use syntax highlighting.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
	exit 0
fi

pretty_str=
if [ "$opt_pretty" = "1" ]; then
	pretty_str="-p"
fi

printer_str=
if [ -n "$opt_printer" ]; then
	printer_str="-P $opt_printer"
fi

rot_str=
if [ "$opt_landscape" = "1" ]; then
	rot_str="-o orientation-requested=4"
fi

sides_str=
if [ "$opt_two_sided" = "1" ]; then
	if [ "$opt_landscape" = "1" ]; then
		sides_str="-o sides=two-sided-short-edge"
	else
		sides_str="-o sides=two-sided-long-edge"
	fi
fi

lpr \
  -o fit-to-page \
  -o print-quality=5 \
  $pretty_str \
  $printer_str \
  $rot_str \
  $sides_str \
  "$@"

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
