#!/usr/bin/perl -w

# snu_epstat
# File ID: 2a0a79c0-5d44-11df-a312-90e6ba3022ac
# Snur outputen fra epstat,v 1.3 og tidlligere og plasserer datoen først.

use strict;

while (<>) {
	if (/^\s+(\d+)\s+(.*)$/) {
		# s/ /\t/;
		print("$2\t$1\n");
	} else {
		print;
	}
}
