#!/usr/bin/perl -w

# $Id: split_md5,v 1.1 2001/11/28 09:10:24 sunny Exp $
# Setter inn punktumer i MD5'er, gjør det mer leselig.

use strict;

my $L = "0123456789abcdef";

while (<>) {
	s/\b([$L]{4})([$L]{4})([$L]{4})([$L]{4})([$L]{4})([$L]{4})([$L]{4})([$L]{4})\b/$1.$2.$3.$4.$5.$6.$7.$8/g;
	print;
}
