#!/usr/bin/perl -w

# split_md5
# File ID: c6346df6-5d44-11df-9981-90e6ba3022ac
# Setter inn punktumer i MD5'er, gjør det mer leselig.

use strict;

my $L = "0123456789abcdef";

while (<>) {
	s/\b([$L]{4})([$L]{4})([$L]{4})([$L]{4})([$L]{4})([$L]{4})([$L]{4})([$L]{4})\b/$1.$2.$3.$4.$5.$6.$7.$8/g;
	print;
}
