#!/bin/bash

#=======================================================================
# ssht
# File ID: 307e8876-e099-11e0-94c2-ef2688b28a12
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

progname=ssht
PORT=9141
HOST=sunny@sunbase.org
CMD="ssh -A -Y -q -N -R $PORT:localhost:22 $HOST"

unset PID
PID=$(pgrep -f -x "$CMD")

if test "$1" = "-c"; then
    USERNAME=$2
    test -z "$2" && USERNAME=sunny
    sess -t c_ssht.c -- ssh -A -Y -p $PORT -l $USERNAME localhost
elif test "$1" = "-k"; then
    test -n "$PID" || { echo $progname: No tunnel found >&2; exit 1; }
    kill $PID
elif test "$1" = "-l"; then
    test -n "$PID" && echo $PID
elif test "$1" = "-t"; then
    test -n "$PID" && { echo $progname: Tunnel already active at PID $PID >&2; exit 1; }
    sess -t c_ssht.t -- $CMD &
else
    echo Syntax: $progname \[ -c \| -k \| -l \| -t \]
fi
