#!/bin/sh

# $Id: still_klokka,v 1.1 2001/10/08 23:33:27 sunny Exp $

if [ -e /toshbb.mrk ]; then
	[ "`whoami`" = "root" ] || { echo $0: Må være root. >&2; exit 1; }
	getdate -set 3 300 ntp.lth.se
	setclock
else
	echo $0: Er beregnet for toshbb. >&2
	exit 1
fi
