#!/usr/bin/perl

#=======================================================================
# storelog
# File ID: 8044b360-3365-11e2-a80a-00c0a8deee11
# [Description]
#
# Character set: UTF-8
# ©opyleft 2012– Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 3 or later, see end of 
# file for legal stuff.
#=======================================================================

use strict;
use warnings;
use Getopt::Long;

local $| = 1;

our $Debug = 0;

our %Opt = (

    'debug' => 0,
    'help' => 0,
    'host' => `hostname`,
    'spec' => '',
    'verbose' => 0,
    'version' => 0,

);
chomp($Opt{'host'});

our $progname = $0;
$progname =~ s/^.*\/(.*?)$/$1/;
our $VERSION = '0.00';

Getopt::Long::Configure('bundling');
GetOptions(

    'debug' => \$Opt{'debug'},
    'help|h' => \$Opt{'help'},
    'host|H=s' => \$Opt{'host'},
    'spec|s=s' => \$Opt{'spec'},
    'verbose|v+' => \$Opt{'verbose'},
    'version' => \$Opt{'version'},

) || die("$progname: Option error. Use -h for help.\n");

$Opt{'debug'} && ($Debug = 1);
$Opt{'help'} && usage(0);
if ($Opt{'version'}) {
    print_version();
    exit(0);
}
defined($ARGV[0]) || die("$progname: Missing project name\n");

my $project = $ARGV[0];
msg(2, "\$project = '$project'");

my $host = $Opt{'host'};
msg(2, "\$host = '$host'");

my $projdir = "$ENV{'HOME'}/annex/log/$project/$host";
msg(2, "\$projdir = '$projdir'");

msg(0, "dirstruct('$Opt{'spec'}') = '" . dirstruct($Opt{'spec'}) . "'");

exit(0);

sub dirstruct {
    # {{{
    my $gran = shift;
    msg(2, "dirstruct('$gran')'");

    my $count;
    my $period;
    if ($gran =~ /^(\d+)\.(.*)$/) {
        $count = $1;
        $period = $2;
        $period =~ s/^(...).*/$1/;
    } else {
        die("$progname: $gran: Wrong --spec format.\n");
    }
    msg(2, "\$gran = '$gran'");
    msg(2, "\$count = '$count'");
    msg(2, "\$period = '$period'");

    my $retval;

    my %mult = (
        'yea' => 1,
        'mon' => 12,
        'wee' => 52,
        'day' => 365,
        'hou' => 365 * 24,
        'min' => 365 * 24 * 60,
        'sec' => 365 * 24 * 60 * 60,
    );
    my $pryear;
    defined($mult{"$period"}) || die("$progname: $period: Unknown period\n");
    $pryear = $count * $mult{"$period"};
    msg(0, "\$pryear = '$pryear'");

    my $maxfiles = 500;
    if ($pryear < $maxfiles) {
        $retval = '%Y';
    } elsif ($pryear < $maxfiles * $mult{'mon'}) {
        $retval = '%Y/%m';
    } elsif ($pryear < $maxfiles * $mult{'day'}) {
        $retval = '%Y/%m/%d';
    } elsif ($pryear < $maxfiles * $mult{'hou'}) {
        $retval = '%Y/%m/%d/%H';
    } elsif ($pryear < $maxfiles * $mult{'min'}) {
        $retval = '%Y/%m/%d/%H/%M';
    } else {
        $retval = '%Y/%m/%d/%H/%M/%S';
    }

    msg(2, "dirstruct('$gran') returns '$retval'");
    return($retval);

    # }}}
} # dirstruct()

sub print_version {
    # Print program version {{{
    print("$progname v$VERSION\n");
    return;
    # }}}
} # print_version()

sub usage {
    # Send the help message to stdout {{{
    my $Retval = shift;

    if ($Opt{'verbose'}) {
        print("\n");
        print_version();
    }
    print(<<"END");

Usage: $progname [options] project_name

Options:

  -h, --help
    Show this help.
  -H X, --host X
    Specify as host X.
  -s X, --spec X
    Create directory structure, use specification X. Format: "x.y" where 
    x is number of expected log entries, and y is a period. Example:
      100.day - 100 entries per day
      1.sec - 1 entry per second
      20.week - 20 entries per week
    Only the first three letters are used. These periods are available:
      year, month, week, day, hour, minute, second,
      yea, mon, wee, day, hou, min, sec.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.
  --debug
    Print debugging messages.

END
    exit($Retval);
    # }}}
} # usage()

sub msg {
    # Print a status message to stderr based on verbosity level {{{
    my ($verbose_level, $Txt) = @_;

    if ($Opt{'verbose'} >= $verbose_level) {
        print(STDERR "$progname: $Txt\n");
    }
    return;
    # }}}
} # msg()

sub D {
    # Print a debugging message {{{
    $Debug || return;
    my @call_info = caller;
    chomp(my $Txt = shift);
    my $File = $call_info[1];
    $File =~ s#\\#/#g;
    $File =~ s#^.*/(.*?)$#$1#;
    print(STDERR "$File:$call_info[2] $$ $Txt\n");
    return('');
    # }}}
} # D()

__END__

# Plain Old Documentation (POD) {{{

=pod

=head1 NAME



=head1 SYNOPSIS

 [options] [file [files [...]]]

=head1 DESCRIPTION



=head1 OPTIONS

=over 4

=item B<-h>, B<--help>

Print a brief help summary.

=item B<-v>, B<--verbose>

Increase level of verbosity. Can be repeated.

=item B<--version>

Print version information.

=item B<--debug>

Print debugging messages.

=back

=head1 BUGS



=head1 AUTHOR

Made by Øyvind A. Holm S<E<lt>sunny@sunbase.orgE<gt>>.

=head1 COPYRIGHT

Copyleft © Øyvind A. Holm E<lt>sunny@sunbase.orgE<gt>
This is free software; see the file F<COPYING> for legalese stuff.

=head1 LICENCE

This program is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation, either version 3 of the License, or (at your 
option) any later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along 
with this program.
If not, see L<http://www.gnu.org/licenses/>.

=head1 SEE ALSO

=cut

# }}}

# vim: set fenc=UTF-8 ft=perl fdm=marker ts=4 sw=4 sts=4 et fo+=w :
