#!/usr/bin/perl -w

# $Id$
# Stripper bort oversettelser i .po-filer for å se om det er noe grums som har
# oppstått der.

my $Print = 1;

while (<>) {
	if (/^msgid/ || /^$/) {
		$Print = 1;
	}
	elsif (/^msgstr/) {
		$Print = 0;
	}
	$Print && print;
}
