#!/usr/bin/perl -w

#============================================================================
# $Id$
# Lager «-kv»-feeling på Id og Date. Subversion gjør visst ikke sånt enda. Og
# jeg er mildt sagt irritert over det nye formatet på $Date , så det engelske
# kjøret i parentesen strippes bort.
#
# Character set: UTF-8
# License: GNU General Public License
# ©opyleft 2004 Øyvind A. Holm <sunny@sunbase.org>
#============================================================================

use strict;

$| = 1;

my $rand_ext = "$$." . substr(rand, 2, 8);
while (defined($ARGV[0])) {
	my $Curr = shift;
	my $Dest = "$Curr.$rand_ext.tmp";
	if (open(FromFP, $Curr)) {
		(-e $Dest) && die("$Dest: What??? File already exists!");
		if (open(ToFP, ">$Dest")) {
			while (<FromFP>) {
				$_ = process_line($_);
				print(ToFP $_);
			}
			close(FromFP);
			close(ToFP);
			rename($Dest, $Curr) || warn("rename($Dest, $Curr): $!");
		} else {
			warn("$Dest: Unable to create file: $!");
		}
	} else {
		warn("$Curr: Unable to open file for read: $!");
	}
}

sub process_line {
	my $Retval = shift;
	$Retval =~ s/(\$Date: .*?)\(..., \d+ ... \d\d\d\d\)( \$)/$1$2/g;
	$Retval =~ s/\$(Id|Date): (.*?) \$/$2/g;
	return($Retval);
}

__END__

# vim: set fileencoding=UTF-8 filetype=perl foldmethod=marker foldlevel=0 :
# End of file $Id$
