#!/usr/bin/perl -w

# $Id: strip_msgstr,v 1.1 2003/05/13 15:10:13 sunny Exp $
# Stripper bort oversettelser i .po-filer for å se om det er noe grums som har
# oppstått der.

my $Print = 1;

while (<>) {
	if (/^msgid/ || /^$/) {
		$Print = 1;
	}
	elsif (/^msgstr/) {
		$Print = 0;
	}
	$Print && print;
}
