#!/bin/bash

#=======================================================================
# $Id$
# Forandrer eierskap te han sunny og setter sticky bit på katalogene så 
# han (jeg) fortsetter å eie dem. Beregnet på .svn-kataloger først og 
# fremst.
#=======================================================================

abort=0
progname=sunnyrights
if [ "$1" = "" ]; then
  echo "Syntax: $progname dir [dir [...]]" >&2
  exit 1
fi
for ft in $*; do
  [ -d $ft ] || { echo "$progname: $ft: Katalogen finnes ikke" >&2; abort=1; }
done
[ "$abort" = "1" ] && { echo "$progname: Avbryter." >&2; exit 1; }
chown -Rc sunny.sunny $*
find $* -type d | xargs chmod -c +s

# vim: set ts=2 sw=2 sts=2 et fo+=w fenc=utf8 :
