#!/bin/bash

#=======================================================================
# sunnyrights
# File ID: 9b90e1dc-5d45-11df-8c34-90e6ba3022ac
#
# Forandrer eierskap te han sunny og setter sticky bit på katalogene så 
# han (jeg) fortsetter å eie dem. Beregnet på .svn-kataloger først og 
# fremst.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=sunnyrights
VERSION=0.1.2

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Forandrer eierskap te han sunny og setter sticky bit på katalogene så 
han (jeg) fortsetter å eie dem. Beregnet på .svn-kataloger først og 
fremst.

Usage: $progname [options] DIRECTORY [DIRECTORIES [...]]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

if test "$1" = ""; then
    echo "$progname: No directory specified" >&2
    exit 1
fi

abort=0
for ft in "$@"; do
    test -d "$ft" || {
        echo "$progname: $ft: Katalogen finnes ikke" >&2
        abort=1
    }
done
test "$abort" = "1" && { echo "$progname: Avbryter." >&2; exit 1; }
chown -Rc sunny.sunny "$@"
find "$@" -type d -print0 | xargs -0 chmod -c +s
