#!/usr/bin/perl -w

# suntodofold
# File ID: a7b42cf8-5d45-11df-b2c3-90e6ba3022ac
# Inserts fold marks in TODO files before and after stdin.
# Select text in visual line mode and filter the block through this script.

use strict;

$| = 1;

my $Line = <STDIN>;
my ($Indent) = ("");

# defined($ARGV[0]) && ($Title = join(" ", @ARGV) . " ");
$Line =~ /^(\s+)/ && ($Indent = $1);
chomp($Line);
print("$Line \x7B\x7B\x7B\n");

while (<STDIN>) {
	print("$_");
}

print("$Indent\x7D\x7D\x7D\n");
