#!/usr/bin/perl -w

# $Id: suntodofold,v 1.1 2003/08/01 23:02:44 sunny Exp $
# Inserts fold marks in TODO files before and after stdin.
# Select text in visual line mode and filter the block through this script.

use strict;

$| = 1;

my $Line = <STDIN>;
my ($Indent) = ("");

# defined($ARGV[0]) && ($Title = join(" ", @ARGV) . " ");
$Line =~ /^(\s+)/ && ($Indent = $1);
chomp($Line);
print("$Line \x7B\x7B\x7B\n");

while (<STDIN>) {
	print($_);
}

print("$Indent\x7D\x7D\x7D\n");
