#!/usr/bin/perl -w

#=======================================================================
# $Id$
# Uses vimdiff to show differences in a Subversion-controlled file.
#
# Character set: UTF-8
# License: GNU General Public License, see end of file for legal stuff.
# ©opyleft 2004– Øyvind A. Holm <sunny@sunbase.org>
#=======================================================================

use strict;

$| = 1;

use Getopt::Std;
our ($opt_a, $opt_c, $opt_h) =
    (     0,     "",      0);
getopts('ac:h') || die("Option error. Use -h for help.\n");

# Change this to the default diff command to use
my $Cmd = "vimdiff";

my $Debug = 0;

our $progname = $0;
$progname =~ s#^(.*)/(.+?)$#$2#;

$opt_h && usage(0);

length($opt_c) && ($Cmd = $opt_c);

for my $Curr (@ARGV) {
    D("ARG = \"$Curr\"\n");
    diff_file($Curr);
}

my @mod_array = ();

if ($opt_a) {
    if (open(PipeFP, "svn stat -q |")) {
        while (<PipeFP>) {
            if (/^[MC]......(.*)/) {
                push(@mod_array, $1);
            }
        }
        close(PipeFP);
        for (sort @mod_array) {
            diff_file($_);
        }
    } else {
        warn("$progname: Error opening \"svn stat -q\" pipe");
    }
}

sub diff_file {
    my $File1 = shift;
    my $Path = "";
    my $File = $File1;

    D("diff_file(\"$File1\");\n");

    if ($File =~ m#^(.*/)(.+?)$#) {
        $Path = $1;
        $File = $2;
    }

    my $File2 = "$Path.svn/text-base/$File.svn-base";
    D("File1 = \"$File1\"\n");
    D("File2 = \"$File2\"\n");

    (-e $File1) || ( warn("$File1: File not found\n"), return);
    (-e $File2) || ( warn("$File2: File not found, is not under version control\n"), return);

    if ($Cmd eq "vimdiff") {
        D("CMD: $Cmd $File1 $File2\n");
        system("$Cmd $File1 $File2");
    } else {
        D("CMD: $Cmd $File2 $File1\n");
        system("$Cmd $File2 $File1");
    }

    # Sleep one second after $Cmd is done to make it easier to interrupt 
    # the thing with CTRL-C if there are many files
    sleep(1) if (scalar(@mod_array) > 1);
}

sub D {
    $Debug || return;
    chomp(my $Txt = shift);
    print("$Txt\n");
}

sub usage {
    # Send the help message to stdout {{{
    my $Retval = shift;
    print(<<END);

Usage: $progname [options] file

Options:

-a    Run $progname on every modified file in current directory and all 
      subdirectories. Needs the svn command-line client.
-c x  Use x as the diff command. Default: "$Cmd".
-h    Show this help.

END
    exit($Retval);
    # }}}
}

__END__

# Plain Old Documentation (POD) {{{

=pod

=head1 NAME

svndiff

=head1 REVISION

$Id$

=head1 SYNOPSIS



=head1 DESCRIPTION



=head1 OPTIONS

=over 4

=item B<-h>

Print a brief help summary.

=back

=head1 BUGS



=head1 AUTHOR

Made by Øyvind A. Holm S<E<lt>sunny _AT_ sunbase.orgE<gt>>.

=head1 COPYRIGHT

Copyleft © Øyvind A. Holm &lt;sunny@sunbase.org&gt;
This is free software; see the file F<COPYING> for legalese stuff.

=head1 LICENCE

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2 of the License, or (at your 
option) any later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

=head1 SEE ALSO

=cut

# }}}

# vim: set fenc=UTF-8 ft=perl fdm=marker ts=4 sw=4 sts=4 et fo+=w :
# End of file $Id$
