#!/bin/sh

#=======================================================================
# $Id$
# Fyrer opp en vimdiff på $* og text-basen som ligger i WC-en.
# FIXME: Funker bare i current dir.
#=======================================================================

for _sd in $*; do
    vimdiff $_sd .svn/text-base/$_sd.svn-base
done

# vim: set sw=4 ts=4 sts=4 et :
