#!/bin/bash

# svnsize
# File ID: ed4bb18c-5d45-11df-9c60-90e6ba3022ac
# Lister ut fildato og størrelse for revisjonene i en fil i svn.

fil=$1

for f in `svnrevs -r1:HEAD $fil | tr -d ,`; do
    date=`svn log --xml -$f $fil | perl -e '$a = join("", <>); $a =~ s/^.*<date>(.{19}).*?<\/date>.*$/$1/gs; print("${a}Z");'`
    size=`svn ls -v -$f $fil | tr -s ' ' | rmspcall | cut -d ' ' -f 3`
    echo "$date $size"
done
