#!/bin/bash

#=======================================================================
# svup
# File ID: 63b136e2-fa61-11dd-81d3-0001805bf4b1
# Lazyness script.
#=======================================================================

LC_ALL=C svn info | grep '^URL: '
echo ==== svn update --ignore-externals "$@"
svn update --ignore-externals "$@"
echo ==== svn stat "$@"
svn stat "$@"
