#!/bin/bash

#=======================================================================
# $Id$
# Lazyness script.
#=======================================================================

LC_ALL=C svn info | grep '^URL: '
echo ==== svn update --ignore-externals "$@"
svn up --ignore-externals "$@"
echo ==== svn stat "$@"
svn st "$@"
