PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE synced (
  file TEXT
    CONSTRAINT filename_length
      CHECK (length(file) > 0)
    UNIQUE
    NOT NULL,
  orig TEXT,
  rev TEXT
    CONSTRAINT rev_length
      CHECK (length(rev) = 40 OR rev = ''),
  date TEXT
    CONSTRAINT date_length
      CHECK (date IS NULL OR length(date) = 19)
    CONSTRAINT valid_date
      CHECK (date IS NULL OR datetime(date) IS NOT NULL)
);
INSERT INTO "synced" VALUES('.gitattributes','',NULL,NULL);
INSERT INTO "synced" VALUES('.gitignore','',NULL,NULL);
INSERT INTO "synced" VALUES('.gitmodules','',NULL,NULL);
INSERT INTO "synced" VALUES('.mailmap','',NULL,NULL);
INSERT INTO "synced" VALUES('256colors2.pl','',NULL,NULL);
INSERT INTO "synced" VALUES('Add_test','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('BUGS','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/HiRes-test','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('Div/apt-get.ubstud.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/bash-cmds.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/compr-test','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('Div/doc/linux-keyboard.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/doc/ssh_tunnelling.html','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/fileid-test','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Div/guieditor','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Div/looping','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('Div/mergeloop','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Div/nullgzip','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('Div/ny.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/obsolete-refs.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/oldrepo','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Div/q3hd-time.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/sinus','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('Div/spamd-graph/plt',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('Div/svk-test.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/svnprops/branches.xml','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/svnprops/hooks.xml','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/svnprops/import.xml','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/svnprops/log.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/svnprops/log.xml','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/svnprops/tags.xml','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/svnprops/trunk.xml','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/svnprops/utils-repo.smsum','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/svnprops/utils-repo.smsum.asc','',NULL,NULL);
INSERT INTO "synced" VALUES('Div/unfinished/svnbck','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('Div/unfinished/svnstat','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('Genlog','Lib/std/bash-no-getopt','602afb101b41e50c9ed7096c56839fe83ff799aa','2015-10-30 07:05:38');
INSERT INTO "synced" VALUES('Git/update','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/perllib/Makefile','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/perllib/Test/edc-test.pl','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/perllib/index.cgi',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('Lib/perllib/suncgi.pm',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('Lib/perllib/test.shtml',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('Lib/perllib/tricgi.pm',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('Lib/perllib/tripwd.pm',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/COPYING','http://www.gnu.org/licenses/gpl-2.0.txt',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/bash','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/bash-no-getopt','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('Lib/std/bisect','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/c/Makefile','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/c/compile','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/c/std.c','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/c/std.h','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/c/version.h','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/db-Makefile','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/db-article','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/db-book','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/db-catalog','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/db-manpage','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/db-slides','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/db5-article','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/db5-book','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/db5-manpage','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/erlang','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/gpx','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/html4','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/html5','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/latex-article','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/markdown','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/mdwn','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/musicxml','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/perl','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/perl-cgi','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/perl-tests','Lib/std/perl','6a98e153551866cee0f6eeb22d4eeee8f3dfb2fb','2015-10-30 00:30:36');
INSERT INTO "synced" VALUES('Lib/std/perl-tests-Makefile','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/perl-tests.tagdesc','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/python','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/svg','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/txt','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/xhtml','',NULL,NULL);
INSERT INTO "synced" VALUES('Lib/std/xml','',NULL,NULL);
INSERT INTO "synced" VALUES('Local/arch-vbox/pkg-to-pavi','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Local/dg-vbox/fixskjerm','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Local/linode/start-vncserver','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Local/n900/mountloop','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Local/n900/pods','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Local/n900/shake','',NULL,NULL);
INSERT INTO "synced" VALUES('Local/ubstud/slowdown','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Local/vbox-deb/firefox','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('Makefile','',NULL,NULL);
INSERT INTO "synced" VALUES('Patch/Div/20070209T191606Z.patch','',NULL,NULL);
INSERT INTO "synced" VALUES('Patch/Div/gptrans_conv.med_title.r1601.patch','',NULL,NULL);
INSERT INTO "synced" VALUES('Patch/Div/svnlog2tab.xmlsimple.r2896.patch','',NULL,NULL);
INSERT INTO "synced" VALUES('Patch/vim7/always_72_chars_per_line_if_undefined.patch','',NULL,NULL);
INSERT INTO "synced" VALUES('Patch/vim7/modified_by-define.patch','',NULL,NULL);
INSERT INTO "synced" VALUES('Patch/vim7/sunny256/0001-Show-percent-in-status-line-when-g-Ctrl-g-is-pressed.patch','',NULL,NULL);
INSERT INTO "synced" VALUES('README.md','',NULL,NULL);
INSERT INTO "synced" VALUES('Screen/latin1-mode','',NULL,NULL);
INSERT INTO "synced" VALUES('Screen/split','',NULL,NULL);
INSERT INTO "synced" VALUES('Screen/utf8-mode','',NULL,NULL);
INSERT INTO "synced" VALUES('TODO','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/UTF-8-demo.txt','http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/UTF-8-test.txt','http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt',NULL,'2015-10-15 17:50:54');
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/calstblx.dtd','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/catalog','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/catalog.xml','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/dbcentx.mod','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/dbgenent.mod','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/dbhierx.mod','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/dbnotnx.mod','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/dbpoolx.mod','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/docbookx.dtd','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOamsa.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOamsb.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOamsc.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOamsn.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOamso.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOamsr.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISObox.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOcyr1.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOcyr2.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOdia.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOgrk1.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOgrk2.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOgrk3.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOgrk4.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOlat1.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOlat2.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOnum.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOpub.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/ISOtech.ent','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/catalog','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/ent/catalog.xml','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/htmltblx.mod','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/docbook-4.4/soextblx.dtd','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/dtd/gpx/gpx-1.1.dtd','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/rng/docbook-5.0/docbook.rng','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/xsd/gpx/gpx-1.0.xsd','',NULL,NULL);
INSERT INTO "synced" VALUES('Tools/xsd/gpx/gpx-1.1.xsd','',NULL,NULL);
INSERT INTO "synced" VALUES('Utv/afv_move-selective_move','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('Utv/cvsssh-perl','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('Utv/mvdirnewest-filerename','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('access-myf','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('access_log-date','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('access_log-drops','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('access_log2epstat','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('access_log2tab','Lib/std/perl','9008255ba17dda8ac1fa5a2b98490b9e480d830e','2015-10-31 00:46:55');
INSERT INTO "synced" VALUES('access_log_ip','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('ack','http://beyondgrep.com/ack-2.12-single-file',NULL,NULL);
INSERT INTO "synced" VALUES('act','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('activesvn','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('afv','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('afv_move','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('afv_rename','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('afvctl','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('age','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('all-lpar','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('allrevs','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ampm','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('annex-cmd','Lib/std/bash-no-getopt','0bfb034882dd4b5853d9720ce6221dd12a58a1e7','2015-10-30 06:48:44');
INSERT INTO "synced" VALUES('ascii','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('au','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('avlytt','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('bell','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('bigsh','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('bom','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('bpakk','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('bs','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('build-git','Lib/std/bash','ff5be6c4d6eafd326992d7bd90b8c3047318d550','2015-11-07 14:12:03');
INSERT INTO "synced" VALUES('build-perl','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('build-postgis','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('build-postgres','Lib/std/bash','cd529b5348c09093e22baf232e0f80c2d3795a64','2015-11-06 14:40:38');
INSERT INTO "synced" VALUES('build-vim','Lib/std/bash','2abe18a697fc0ef450987885a306d07eaf5faa7e','2015-11-10 04:07:01');
INSERT INTO "synced" VALUES('ccc','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('cdiff','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('cdiffa','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('cdiffb','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('cdlabel','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('center','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('cfold','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('charconv','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('ciall','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('cl','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('cleansrc','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('cmds','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('colourtest','',NULL,NULL);
INSERT INTO "synced" VALUES('commify','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('commout','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('construct_call_graph.py','',NULL,NULL);
INSERT INTO "synced" VALUES('convkeyw','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('cp1252','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('cp865','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('create-annex-remotes','Lib/std/bash','1ef87e015dfa1643d20ad6c656deaf0eb76dccf2','2015-11-13 17:20:11');
INSERT INTO "synced" VALUES('create_cproject','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('create_imgindex','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('create_new','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('create_svn','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('cryptit','',NULL,NULL);
INSERT INTO "synced" VALUES('cunw','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('cutfold','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('cvs-rev','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('cvscat','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('cvse','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('cvsrootmd5','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('cvsvimdiff','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('dass','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('date2iso','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('datefn','Lib/std/perl','ed71ffab49c9b00eea480b55e79bcba3d8364633','2015-10-30 01:20:56');
INSERT INTO "synced" VALUES('dbk','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('dbllf','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('debugprompt','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('deep','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('degpg','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('denycurrent','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('detab','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('dir-elems','Lib/std/bash','94a9ac14a545242384e8dbc783b2a3c5ea7662cf','2015-11-05 13:40:24');
INSERT INTO "synced" VALUES('doc/Makefile','',NULL,NULL);
INSERT INTO "synced" VALUES('doc/build-git.md','',NULL,NULL);
INSERT INTO "synced" VALUES('doc/git-init.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('doc/index.html','',NULL,NULL);
INSERT INTO "synced" VALUES('doc/index.xml','',NULL,NULL);
INSERT INTO "synced" VALUES('doc/mergesvn.1','',NULL,NULL);
INSERT INTO "synced" VALUES('doc/sident.1','',NULL,NULL);
INSERT INTO "synced" VALUES('doc/svndiff.1','',NULL,NULL);
INSERT INTO "synced" VALUES('dostime','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('dprofpp.graphviz','http://cpansearch.perl.org/src/LBROCARD/GraphViz-2.04/examples/dprofpp.graphviz',NULL,'2009-06-24 02:15:51');
INSERT INTO "synced" VALUES('edit-sqlite3','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('efnhtml','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('emptydirs','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('enc-mp4','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('encap','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('encr','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ep','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('ep-pause','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('ep_day','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('eplog2date','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('epstat','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('export_kde_svn','',NULL,NULL);
INSERT INTO "synced" VALUES('extract_mail','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('ferdig','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('fibonacci','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('filenamelower','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('filesynced','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('filmer','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('filt','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('filter_ep','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('filtrer_access_log','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('find_8bit','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('find_inv_utf8','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('findbom','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('finddup','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('findhex','Lib/std/perl','caaf3a238ed84227a4905a13a9e80a85ea891d93','2015-10-30 02:24:18');
INSERT INTO "synced" VALUES('findrev','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('finn_triton','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('firefox','Lib/std/bash-no-getopt',NULL,NULL);
INSERT INTO "synced" VALUES('fix_filenames','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('fix_mailman','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('fixtext','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('fjern_here','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('flac_to_ogg','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('fold-stdout','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('fra_linode','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('fromdos','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('fromhex','Lib/std/perl','1a9830c37122a2c82178b9b6f75abf5e01d892fb','2015-10-30 02:40:53');
INSERT INTO "synced" VALUES('g','Lib/std/bash-no-getopt',NULL,NULL);
INSERT INTO "synced" VALUES('g0','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('g1','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ga','Lib/std/bash-no-getopt','0bfb034882dd4b5853d9720ce6221dd12a58a1e7','2015-10-30 06:48:44');
INSERT INTO "synced" VALUES('ga-au','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ga-findkey','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('ga-fixnew','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ga-fsck-size','Lib/std/perl','9008255ba17dda8ac1fa5a2b98490b9e480d830e','2015-10-31 00:46:55');
INSERT INTO "synced" VALUES('ga-getnew','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ga-key','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ga-other','Lib/std/bash','f3d617779ce2ef99a6b8c689a23ea28c830abd9e','2015-11-11 20:16:44');
INSERT INTO "synced" VALUES('ga-repofix','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ga-sjekk','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ga-sumsize','Lib/std/perl','8a8fb69e7712e7433fb9e88f823af7f772ce4048','2015-10-31 00:42:28');
INSERT INTO "synced" VALUES('ga-tree','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('gammelsvn','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('genpasswd','https://raw.githubusercontent.com/fuktommy/homebin/master/genpasswd',NULL,'2015-10-15 17:50:54');
INSERT INTO "synced" VALUES('geohashing','',NULL,NULL);
INSERT INTO "synced" VALUES('getapr','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('getpic','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('getsvnfiles','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('gfuck','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-add-missing-gpg-keys','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-all-blobs','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-all-repos','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-allbr','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('git-allfiles','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-authoract','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-bare','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-bs','Lib/std/bash-no-getopt',NULL,NULL);
INSERT INTO "synced" VALUES('git-context-diff','https://raw.githubusercontent.com/postgres/postgres/master/src/tools/git-external-diff',NULL,NULL);
INSERT INTO "synced" VALUES('git-dangling','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('git-dbr','Lib/std/perl','9008255ba17dda8ac1fa5a2b98490b9e480d830e','2015-10-31 00:46:55');
INSERT INTO "synced" VALUES('git-delete-banned','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-delrembr','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('git-dl','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-dobranch','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-eb','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-expand','Lib/std/python',NULL,NULL);
INSERT INTO "synced" VALUES('git-fuckit','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-ignore','Lib/std/bash','15449ee625475537d9973685b34cb58ca420e53c','2015-11-23 08:52:53');
INSERT INTO "synced" VALUES('git-imerge','https://raw.githubusercontent.com/mhagger/git-imerge/master/git-imerge',NULL,'2015-10-15 17:50:54');
INSERT INTO "synced" VALUES('git-inv-commits','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-lc','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-listbundle','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-logdiff','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-mnff','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-nocom','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('git-pa','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('git-plot','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-rcmd','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('git-realclean','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-remote-hg','https://raw.githubusercontent.com/felipec/git-remote-hg/master/git-remote-hg',NULL,NULL);
INSERT INTO "synced" VALUES('git-repos','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-restore-dirs','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-rpull','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-safe-rm-remote','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-savecommit','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-scanrefs','Lib/std/perl','a44f216ca0a8631cae08566d2a5d1cde5bf9c34c','2015-10-30 02:51:18');
INSERT INTO "synced" VALUES('git-seq-rebase','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-size','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-store-dirs','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-svn-myclone','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-trash','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-tree-size','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('git-update-dirs','Lib/std/perl','9008255ba17dda8ac1fa5a2b98490b9e480d830e','2015-10-31 00:46:55');
INSERT INTO "synced" VALUES('git-upstream','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('git-wait-until-clean','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('git-wip','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('git-wn','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('githubnetwork','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('goal','Lib/std/perl','56fc904a9fc4b79969caa805f92f125b31c042c5','2015-11-13 18:17:01');
INSERT INTO "synced" VALUES('gotexp','Lib/std/perl','5b25406a934b99d33e426c6c8649d3644ea8fc71','2015-10-30 02:56:15');
INSERT INTO "synced" VALUES('gpath','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('gpgpakk','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('gqfav','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('gqview','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('h0','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('h1','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('h2chin','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('h2t','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('h2u','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('hentfilm','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('hf','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('hfa','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('hhi','Lib/std/perl','e753ee1fd21258a29e3cc85f9d21195e63848306','2015-10-30 03:01:10');
INSERT INTO "synced" VALUES('hmsg','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('href','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('html2cgi','',NULL,NULL);
INSERT INTO "synced" VALUES('html2db','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('html2wiki','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('htmlfold','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('httplog','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('hub','http://defunkt.io/hub/standalone',NULL,NULL);
INSERT INTO "synced" VALUES('hvor','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('icat','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('icatf','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('impnet','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('inc_epstat','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('irc-conn','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('irssi','Lib/std/bash-no-getopt',NULL,NULL);
INSERT INTO "synced" VALUES('isoname','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('ivim','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('jsonfmt.py','Lib/std/python','223fc61da6e1b13849ced6d921058a50b53b4c9d','2014-10-02 22:26:26');
INSERT INTO "synced" VALUES('kar','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('kbd','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('keyw','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('klokke','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('klokkesig-conv','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('konvflac','Lib/std/bash','a71f661401a7e0b202884daf911d504b4e359e2b','2015-10-31 00:23:21');
INSERT INTO "synced" VALUES('kopier_bilder','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('l','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('l33t','http://users.tpg.com.au/adsln4yb/Specials/l33t',NULL,NULL);
INSERT INTO "synced" VALUES('lag3d','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('lag_gqv','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('lag_linker','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('line_exec.py','Lib/std/python','33e2a6f73732491d18e7f7f183c9ca7350fbb616','2013-07-24 12:10:46');
INSERT INTO "synced" VALUES('linux-counter-machine-update','http://counter.li.org/scripts/machine-update',NULL,NULL);
INSERT INTO "synced" VALUES('list-extensions','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('list-tables','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('list-youtube','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('livecd-exit','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('livecd-init','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ll','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('log_df','Lib/std/bash','7dc5461ab63f846ec8668f346cff186238a48625','2015-11-10 12:37:13');
INSERT INTO "synced" VALUES('log_df_pg','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('log_load','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('logg','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('logging','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('lpar','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('ls-broken','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('lsreadable','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('maileditor','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mailfix','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('mailview','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('make_svnlog','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('make_tags','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mangefiler','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('manyfiles','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('manypatch','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('markdown','',NULL,NULL);
INSERT INTO "synced" VALUES('mc','Lib/std/bash-no-getopt',NULL,NULL);
INSERT INTO "synced" VALUES('mergesvn','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('mime2txt','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('mincvs_vim','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mixline','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('mixword','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('mkFiles','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mkFiles_rec','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mk_local_links','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mkcvsbck','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mkd','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('mklist','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('mkrepo','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('mkt','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mobilstripp','Lib/std/bash','97e47e793bf1b2b8972203a3e1351f5e3ab047c8','2015-11-21 18:43:18');
INSERT INTO "synced" VALUES('mountusb','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mp3_to_ogg','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mtube','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('multiapt','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mvdirnewest','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('myf','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('mymkdir','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('n0','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('n1','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('n95film','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('netgraph','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('nettradio','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('nf','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('nfs0','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('nfs1','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ngttest','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('nogit','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('nosvn','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('oggname','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('old-git','build-git',NULL,NULL);
INSERT INTO "synced" VALUES('outl','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('p','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('pakk','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('pakk_logg','Lib/std/bash','7c7c8d93dce5af6e5fa986e645f259ab439aae9a','2015-11-23 10:37:42');
INSERT INTO "synced" VALUES('pakkdir','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('pakkings','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('pakkut','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('perldeboff','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('perldebon','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('perlfold','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('pget','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('pgsafe','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('pine','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('pingstat','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('pmsetdate','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('poiformat','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('pols','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('prearmor','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('pri','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('primitiv_prompt','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('purgewiki','',NULL,NULL);
INSERT INTO "synced" VALUES('push-annex-sunbase','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('pynt','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('q3r','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('r','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('radiolagring','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('random/random.bin','',NULL,NULL);
INSERT INTO "synced" VALUES('rc.firewall-2.2','',NULL,NULL);
INSERT INTO "synced" VALUES('rcs-extract','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('rdbl-garmin-gpi','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('rdbl-gpg','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('rdbl-gramps-backup','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('rdbl-odt','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('rdbl-sort_k5','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('rdbl-sqlite3','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('rdbl-unzip','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('remove_perltestnumbers','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('rensk','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('repo','https://dl-ssl.google.com/dl/googlesource/git-repo/repo',NULL,NULL);
INSERT INTO "synced" VALUES('repofix','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('reset','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('rm_backup','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('rmdup','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('rmheadtail','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('rmspc','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('rmspcall','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('rmspcbak','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('rmspcforan','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('rmxmlcomm','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('rot13','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('runtest','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('scrdump','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('scrplay','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('sea-repo','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('sget','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('shellshock','http://www.dhampir.no/stuff/bash/shellshock',NULL,NULL);
INSERT INTO "synced" VALUES('sident','Lib/std/perl','ea0c2eb42d04bfa30cbea92f77f985cc58434605','2015-10-30 03:20:13');
INSERT INTO "synced" VALUES('sj','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('sjekk_iso','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('sjekkhtmlindent','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('sjekkrand','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('sjekksommer','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('skipline','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('skiptoplines','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('skjermhoyde','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('slekt','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('slogg','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('snu_epstat','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('sommer','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('sort-sqlite','Lib/std/perl','9008255ba17dda8ac1fa5a2b98490b9e480d830e','2015-10-31 00:46:55');
INSERT INTO "synced" VALUES('sortcvs','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('sortxml','Lib/std/perl','5c2065185f2ff6a38b0e931e35d2ebf144bcbc38','2015-10-30 03:53:20');
INSERT INTO "synced" VALUES('split_access_log','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('split_ep-logg','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('split_log','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('split_md5','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('spreadsheet/exponential_growth.ods','',NULL,NULL);
INSERT INTO "synced" VALUES('src/check_utf8/.cvsignore','',NULL,NULL);
INSERT INTO "synced" VALUES('src/check_utf8/Makefile','',NULL,NULL);
INSERT INTO "synced" VALUES('src/check_utf8/check_utf8.c','',NULL,NULL);
INSERT INTO "synced" VALUES('src/check_utf8/utf8-locale','',NULL,NULL);
INSERT INTO "synced" VALUES('src/dbf2tab/dbf2tab.c','http://www.pgts.com.au/download/misc/dbf2tab.c',NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/FLDBdebug.pm',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/FLDBpg.pm',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/FLDBsum.pm',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/FLDButf.pm',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/TODO','',NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/doc/fundering.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/fldb','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/postgres/create_table.sql','',NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/tests/Makefile','',NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/tests/files/allfiles.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/tests/files/dir1.tar.gz','',NULL,NULL);
INSERT INTO "synced" VALUES('src/fldb/tests/fldb.t','Lib/std/perl-tests',NULL,NULL);
INSERT INTO "synced" VALUES('src/kbd.c','',NULL,NULL);
INSERT INTO "synced" VALUES('src/personnr/COPYING','http://www.gnu.org/licenses/gpl-2.0.txt',NULL,'2015-10-15 17:50:54');
INSERT INTO "synced" VALUES('src/personnr/Files.md5','',NULL,NULL);
INSERT INTO "synced" VALUES('src/personnr/Makefile','',NULL,NULL);
INSERT INTO "synced" VALUES('src/personnr/personnr.c',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('src/smsum/smsum','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('src/smsum/tests/Makefile','',NULL,NULL);
INSERT INTO "synced" VALUES('src/smsum/tests/files/dir1.tar.gz','',NULL,NULL);
INSERT INTO "synced" VALUES('src/smsum/tests/smsum.t','Lib/std/perl-tests',NULL,NULL);
INSERT INTO "synced" VALUES('ssht','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('sssh','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('statgits','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('statplot',NULL,NULL,NULL);
INSERT INTO "synced" VALUES('std','Lib/std/perl','9008255ba17dda8ac1fa5a2b98490b9e480d830e','2015-10-31 00:46:55');
INSERT INTO "synced" VALUES('still_klokka','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('storelog','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('stpl','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('stq','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('strip-conflict','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('strip-nonexisting','Lib/std/bash','91dc18f57939403560ac81c27e7c73fd350442eb','2015-11-12 16:18:22');
INSERT INTO "synced" VALUES('strip_msgstr','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('sub-mergesvn','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('sumdup','Lib/std/perl','820f105de40173eb9e59a63dedcb49e0aa7357db','2015-10-30 04:07:06');
INSERT INTO "synced" VALUES('sums','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('sunnyrights','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('suntodofold','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('svedit','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('svi','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('svn-po','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('svnclean','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('svncvsrevs','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('svndiff','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('svnfiledate','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('svnlog2tab','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('svnrevs','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('svnsize','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('svnstat','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('svup','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('synced.sql','',NULL,NULL);
INSERT INTO "synced" VALUES('t','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('t2h','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('ta_backup','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('tab','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('tail-errorlog','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('tarsize','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('telenorsms','http://dhampir.no/stuff/bash/telenorsms',NULL,NULL);
INSERT INTO "synced" VALUES('termtitle','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('testfail','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('tests/Makefile','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/datefn-files/file.tar.gz','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/datefn-files/repo.tar.gz','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/datefn.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/edit-sqlite3-files/sqlite-databases.tar.gz','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/edit-sqlite3.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/findhex.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/fromhex-files/decimal.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/fromhex-files/single.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/fromhex-files/standardpudding.bin','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/fromhex.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/ga-fsck-size-files/annex-backends.tar.gz','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/ga-fsck-size.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/ga-sumsize-files/1.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/ga-sumsize-files/ga-sumsize-repo.tar.gz','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/ga-sumsize.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/git-dangling-files/repo.bundle','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/git-dangling.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/git-dbr.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/git-scanrefs.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/git-update-dirs.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/git-wip.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/gotexp-files/output1.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/gotexp.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/hhi-files/file.html','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/hhi-files/name.html','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/hhi-files/nohhi.html','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/hhi.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/installed_progs.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/perlmodules.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/postgres.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/sident-files/filenames','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/sident-files/nothing_here','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/sident-files/random','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/sident-files/textfile','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/sident-files/unexpanded','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/sident.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/sort-sqlite-files/sqlite-dbs.tar.gz','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/sort-sqlite.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/sortxml-files/a.xml','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/sortxml-files/oneliners.xml','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/sortxml.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/std.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/sumdup-files/files.md5','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/sumdup-files/files.sha1','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/sumdup-files/files.sha256','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/sumdup.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/tohex-files/random256.bin','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/tohex-files/utf8.txt','',NULL,NULL);
INSERT INTO "synced" VALUES('tests/tohex.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/txt2uc.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/ustr.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('tests/zeropad.t','Lib/std/perl-tests','6ce54f2554ca0c70fed10f806f0f16ce8c7eb966','2015-11-14 23:19:59');
INSERT INTO "synced" VALUES('til-ov','Lib/std/bash','d9772bde0d3358a2837acbf6d04680fb33935dfb','2015-11-20 12:01:40');
INSERT INTO "synced" VALUES('tmux_local_install.sh','',NULL,NULL);
INSERT INTO "synced" VALUES('todos','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('tohex','Lib/std/perl','f224d8b74a086f30dbec4f7a319e91b62aa7c9f9','2015-10-30 04:25:36');
INSERT INTO "synced" VALUES('tojson','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('tolower','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('tosec','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('towav','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('txt2uc','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('txtfold','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('u','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('u2h','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('uh2dec','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('uj','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('unichar','Lib/std/bash','0d681ba6e42b913c610e97f668c44b43aaf9f7b2','2015-10-30 23:22:23');
INSERT INTO "synced" VALUES('unicode_htmlchart','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('unik_df','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('unz','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('uoversatt','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('upd','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('update_vim-clean','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('urlstrip','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('urm','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('usedchars','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('ustr','Lib/std/perl','3181637930819d0f6488568f751f33355fe5fab8','2015-10-30 04:43:43');
INSERT INTO "synced" VALUES('utc','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('vd','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('view_df','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('wav_to_flac','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('wav_to_mp3','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('wavto16','Lib/std/bash','e0cd53389c16b9071254c995200ac728c12a82c8','2015-11-23 10:22:50');
INSERT INTO "synced" VALUES('wdiff','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('wdisk','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('wikipedia-export','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('wlan-list','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('wlan0','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('wlan1','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('wn','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('xf','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('xml-to-lisp','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('xml2html','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('xmlformat','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('xmlstrip','Lib/std/perl',NULL,NULL);
INSERT INTO "synced" VALUES('xt','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('yd','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('ydd','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('youtube-dl','',NULL,NULL);
INSERT INTO "synced" VALUES('zero-to-lf','Lib/std/bash',NULL,NULL);
INSERT INTO "synced" VALUES('zeropad','Lib/std/perl','8a7f0fe717498077b9dea93268488bcb3aeea86c','2015-10-30 04:55:50');
INSERT INTO "synced" VALUES('zerosplit','Lib/std/perl',NULL,NULL);
CREATE TABLE todo (
  file TEXT
    CONSTRAINT todo_file_length
      CHECK(length(file) > 0)
    UNIQUE
    NOT NULL
  ,
  pri INTEGER
    CONSTRAINT todo_pri_range
      CHECK(pri BETWEEN 1 AND 5)
);
INSERT INTO "todo" VALUES('Div/fileid-test',5);
INSERT INTO "todo" VALUES('Div/guieditor',3);
INSERT INTO "todo" VALUES('Div/mergeloop',5);
INSERT INTO "todo" VALUES('Div/oldrepo',3);
INSERT INTO "todo" VALUES('Git/update',3);
INSERT INTO "todo" VALUES('Lib/std/c/compile',3);
INSERT INTO "todo" VALUES('Local/arch-vbox/pkg-to-pavi',5);
INSERT INTO "todo" VALUES('Local/dg-vbox/fixskjerm',5);
INSERT INTO "todo" VALUES('Local/linode/start-vncserver',1);
INSERT INTO "todo" VALUES('Local/n900/mountloop',5);
INSERT INTO "todo" VALUES('Local/n900/pods',5);
INSERT INTO "todo" VALUES('Local/ubstud/slowdown',3);
INSERT INTO "todo" VALUES('Local/vbox-deb/firefox',5);
INSERT INTO "todo" VALUES('access-myf',3);
INSERT INTO "todo" VALUES('act',1);
INSERT INTO "todo" VALUES('activesvn',3);
INSERT INTO "todo" VALUES('afvctl',1);
INSERT INTO "todo" VALUES('age',1);
INSERT INTO "todo" VALUES('all-lpar',1);
INSERT INTO "todo" VALUES('allrevs',3);
INSERT INTO "todo" VALUES('au',1);
INSERT INTO "todo" VALUES('avlytt',3);
INSERT INTO "todo" VALUES('bell',1);
INSERT INTO "todo" VALUES('bigsh',2);
INSERT INTO "todo" VALUES('bom',3);
INSERT INTO "todo" VALUES('bpakk',3);
INSERT INTO "todo" VALUES('bs',1);
INSERT INTO "todo" VALUES('build-perl',1);
INSERT INTO "todo" VALUES('build-postgis',1);
INSERT INTO "todo" VALUES('cdiff',1);
INSERT INTO "todo" VALUES('cdiffa',3);
INSERT INTO "todo" VALUES('cdiffb',3);
INSERT INTO "todo" VALUES('cdlabel',3);
INSERT INTO "todo" VALUES('ciall',1);
INSERT INTO "todo" VALUES('cl',1);
INSERT INTO "todo" VALUES('cleansrc',3);
INSERT INTO "todo" VALUES('cmds',1);
INSERT INTO "todo" VALUES('cp1252',3);
INSERT INTO "todo" VALUES('cp865',3);
INSERT INTO "todo" VALUES('create_cproject',3);
INSERT INTO "todo" VALUES('cunw',3);
INSERT INTO "todo" VALUES('cvs-rev',3);
INSERT INTO "todo" VALUES('cvscat',3);
INSERT INTO "todo" VALUES('cvsrootmd5',3);
INSERT INTO "todo" VALUES('cvsvimdiff',3);
INSERT INTO "todo" VALUES('dass',3);
INSERT INTO "todo" VALUES('debugprompt',3);
INSERT INTO "todo" VALUES('denycurrent',3);
INSERT INTO "todo" VALUES('efnhtml',3);
INSERT INTO "todo" VALUES('emptydirs',1);
INSERT INTO "todo" VALUES('encr',3);
INSERT INTO "todo" VALUES('epstat',1);
INSERT INTO "todo" VALUES('ferdig',3);
INSERT INTO "todo" VALUES('filenamelower',1);
INSERT INTO "todo" VALUES('filmer',1);
INSERT INTO "todo" VALUES('filt',1);
INSERT INTO "todo" VALUES('filtrer_access_log',3);
INSERT INTO "todo" VALUES('findbom',1);
INSERT INTO "todo" VALUES('finddup',3);
INSERT INTO "todo" VALUES('finn_triton',3);
INSERT INTO "todo" VALUES('fix_filenames',1);
INSERT INTO "todo" VALUES('fix_mailman',3);
INSERT INTO "todo" VALUES('flac_to_ogg',3);
INSERT INTO "todo" VALUES('fra_linode',1);
INSERT INTO "todo" VALUES('g0',1);
INSERT INTO "todo" VALUES('g1',1);
INSERT INTO "todo" VALUES('ga-au',1);
INSERT INTO "todo" VALUES('ga-fixnew',1);
INSERT INTO "todo" VALUES('ga-getnew',1);
INSERT INTO "todo" VALUES('ga-key',1);
INSERT INTO "todo" VALUES('ga-repofix',3);
INSERT INTO "todo" VALUES('ga-sjekk',1);
INSERT INTO "todo" VALUES('ga-tree',1);
INSERT INTO "todo" VALUES('gammelsvn',3);
INSERT INTO "todo" VALUES('getapr',3);
INSERT INTO "todo" VALUES('gfuck',1);
INSERT INTO "todo" VALUES('git-add-missing-gpg-keys',3);
INSERT INTO "todo" VALUES('git-all-blobs',3);
INSERT INTO "todo" VALUES('git-all-repos',1);
INSERT INTO "todo" VALUES('git-allfiles',1);
INSERT INTO "todo" VALUES('git-authoract',1);
INSERT INTO "todo" VALUES('git-bare',3);
INSERT INTO "todo" VALUES('git-delete-banned',3);
INSERT INTO "todo" VALUES('git-dl',3);
INSERT INTO "todo" VALUES('git-dobranch',1);
INSERT INTO "todo" VALUES('git-eb',3);
INSERT INTO "todo" VALUES('git-fuckit',3);
INSERT INTO "todo" VALUES('git-inv-commits',3);
INSERT INTO "todo" VALUES('git-lc',3);
INSERT INTO "todo" VALUES('git-listbundle',3);
INSERT INTO "todo" VALUES('git-logdiff',1);
INSERT INTO "todo" VALUES('git-mnff',1);
INSERT INTO "todo" VALUES('git-plot',3);
INSERT INTO "todo" VALUES('git-realclean',1);
INSERT INTO "todo" VALUES('git-repos',3);
INSERT INTO "todo" VALUES('git-restore-dirs',1);
INSERT INTO "todo" VALUES('git-rpull',1);
INSERT INTO "todo" VALUES('git-safe-rm-remote',3);
INSERT INTO "todo" VALUES('git-savecommit',1);
INSERT INTO "todo" VALUES('git-seq-rebase',3);
INSERT INTO "todo" VALUES('git-size',3);
INSERT INTO "todo" VALUES('git-store-dirs',1);
INSERT INTO "todo" VALUES('git-svn-myclone',1);
INSERT INTO "todo" VALUES('git-trash',3);
INSERT INTO "todo" VALUES('git-wait-until-clean',1);
INSERT INTO "todo" VALUES('gpgpakk',1);
INSERT INTO "todo" VALUES('gqfav',3);
INSERT INTO "todo" VALUES('gqview',1);
INSERT INTO "todo" VALUES('h0',3);
INSERT INTO "todo" VALUES('h1',3);
INSERT INTO "todo" VALUES('hentfilm',3);
INSERT INTO "todo" VALUES('hfa',3);
INSERT INTO "todo" VALUES('hmsg',3);
INSERT INTO "todo" VALUES('httplog',1);
INSERT INTO "todo" VALUES('hvor',1);
INSERT INTO "todo" VALUES('icat',3);
INSERT INTO "todo" VALUES('icatf',3);
INSERT INTO "todo" VALUES('impnet',3);
INSERT INTO "todo" VALUES('irssi',1);
INSERT INTO "todo" VALUES('ivim',3);
INSERT INTO "todo" VALUES('kar',3);
INSERT INTO "todo" VALUES('kbd',3);
INSERT INTO "todo" VALUES('keyw',3);
INSERT INTO "todo" VALUES('kopier_bilder',3);
INSERT INTO "todo" VALUES('l',1);
INSERT INTO "todo" VALUES('lag_gqv',1);
INSERT INTO "todo" VALUES('lag_linker',3);
INSERT INTO "todo" VALUES('list-extensions',1);
INSERT INTO "todo" VALUES('list-tables',1);
INSERT INTO "todo" VALUES('list-youtube',1);
INSERT INTO "todo" VALUES('livecd-exit',2);
INSERT INTO "todo" VALUES('livecd-init',2);
INSERT INTO "todo" VALUES('ll',1);
INSERT INTO "todo" VALUES('log_df_pg',3);
INSERT INTO "todo" VALUES('log_load',3);
INSERT INTO "todo" VALUES('logg',3);
INSERT INTO "todo" VALUES('logging',1);
INSERT INTO "todo" VALUES('ls-broken',3);
INSERT INTO "todo" VALUES('maileditor',3);
INSERT INTO "todo" VALUES('mailview',3);
INSERT INTO "todo" VALUES('make_svnlog',3);
INSERT INTO "todo" VALUES('make_tags',1);
INSERT INTO "todo" VALUES('manypatch',3);
INSERT INTO "todo" VALUES('mincvs_vim',3);
INSERT INTO "todo" VALUES('mkFiles',1);
INSERT INTO "todo" VALUES('mkFiles_rec',3);
INSERT INTO "todo" VALUES('mk_local_links',3);
INSERT INTO "todo" VALUES('mkcvsbck',3);
INSERT INTO "todo" VALUES('mkt',1);
INSERT INTO "todo" VALUES('mountusb',3);
INSERT INTO "todo" VALUES('mp3_to_ogg',3);
INSERT INTO "todo" VALUES('mtube',3);
INSERT INTO "todo" VALUES('multiapt',1);
INSERT INTO "todo" VALUES('myf',1);
INSERT INTO "todo" VALUES('mymkdir',1);
INSERT INTO "todo" VALUES('n0',3);
INSERT INTO "todo" VALUES('n1',3);
INSERT INTO "todo" VALUES('n95film',3);
INSERT INTO "todo" VALUES('nettradio',3);
INSERT INTO "todo" VALUES('nf',1);
INSERT INTO "todo" VALUES('nfs0',3);
INSERT INTO "todo" VALUES('nfs1',3);
INSERT INTO "todo" VALUES('ngttest',3);
INSERT INTO "todo" VALUES('nogit',1);
INSERT INTO "todo" VALUES('nosvn',3);
INSERT INTO "todo" VALUES('oggname',3);
INSERT INTO "todo" VALUES('old-git',1);
INSERT INTO "todo" VALUES('p',1);
INSERT INTO "todo" VALUES('pakk',3);
INSERT INTO "todo" VALUES('pakkdir',3);
INSERT INTO "todo" VALUES('pakkings',1);
INSERT INTO "todo" VALUES('pget',3);
INSERT INTO "todo" VALUES('pine',3);
INSERT INTO "todo" VALUES('poiformat',1);
INSERT INTO "todo" VALUES('pols',3);
INSERT INTO "todo" VALUES('pri',3);
INSERT INTO "todo" VALUES('primitiv_prompt',3);
INSERT INTO "todo" VALUES('push-annex-sunbase',3);
INSERT INTO "todo" VALUES('pynt',3);
INSERT INTO "todo" VALUES('r',3);
INSERT INTO "todo" VALUES('radiolagring',3);
INSERT INTO "todo" VALUES('rdbl-garmin-gpi',3);
INSERT INTO "todo" VALUES('rdbl-gpg',3);
INSERT INTO "todo" VALUES('rdbl-gramps-backup',3);
INSERT INTO "todo" VALUES('rdbl-odt',3);
INSERT INTO "todo" VALUES('rdbl-sort_k5',3);
INSERT INTO "todo" VALUES('rdbl-sqlite3',3);
INSERT INTO "todo" VALUES('rdbl-unzip',3);
INSERT INTO "todo" VALUES('rensk',1);
INSERT INTO "todo" VALUES('repofix',3);
INSERT INTO "todo" VALUES('reset',1);
INSERT INTO "todo" VALUES('rm_backup',3);
INSERT INTO "todo" VALUES('rmdup',3);
INSERT INTO "todo" VALUES('rmspc',3);
INSERT INTO "todo" VALUES('rmspcall',1);
INSERT INTO "todo" VALUES('rot13',1);
INSERT INTO "todo" VALUES('runtest',1);
INSERT INTO "todo" VALUES('scrdump',1);
INSERT INTO "todo" VALUES('sea-repo',1);
INSERT INTO "todo" VALUES('sget',1);
INSERT INTO "todo" VALUES('sjekkhtmlindent',3);
INSERT INTO "todo" VALUES('sjekkrand',1);
INSERT INTO "todo" VALUES('sjekksommer',3);
INSERT INTO "todo" VALUES('slekt',3);
INSERT INTO "todo" VALUES('slogg',3);
INSERT INTO "todo" VALUES('ssht',1);
INSERT INTO "todo" VALUES('sssh',1);
INSERT INTO "todo" VALUES('statgits',3);
INSERT INTO "todo" VALUES('still_klokka',3);
INSERT INTO "todo" VALUES('stq',3);
INSERT INTO "todo" VALUES('strip-conflict',2);
INSERT INTO "todo" VALUES('sub-mergesvn',3);
INSERT INTO "todo" VALUES('sunnyrights',1);
INSERT INTO "todo" VALUES('svedit',3);
INSERT INTO "todo" VALUES('svi',3);
INSERT INTO "todo" VALUES('svn-po',3);
INSERT INTO "todo" VALUES('svnclean',4);
INSERT INTO "todo" VALUES('svncvsrevs',4);
INSERT INTO "todo" VALUES('svnrevs',3);
INSERT INTO "todo" VALUES('svnsize',4);
INSERT INTO "todo" VALUES('svup',3);
INSERT INTO "todo" VALUES('t',3);
INSERT INTO "todo" VALUES('ta_backup',3);
INSERT INTO "todo" VALUES('tail-errorlog',3);
INSERT INTO "todo" VALUES('tarsize',3);
INSERT INTO "todo" VALUES('testfail',1);
INSERT INTO "todo" VALUES('tolower',3);
INSERT INTO "todo" VALUES('towav',3);
INSERT INTO "todo" VALUES('u',1);
INSERT INTO "todo" VALUES('unz',1);
INSERT INTO "todo" VALUES('uoversatt',3);
INSERT INTO "todo" VALUES('upd',1);
INSERT INTO "todo" VALUES('update_vim-clean',3);
INSERT INTO "todo" VALUES('urm',3);
INSERT INTO "todo" VALUES('utc',1);
INSERT INTO "todo" VALUES('vd',1);
INSERT INTO "todo" VALUES('view_df',3);
INSERT INTO "todo" VALUES('wav_to_mp3',1);
INSERT INTO "todo" VALUES('wdiff',3);
INSERT INTO "todo" VALUES('wdisk',3);
INSERT INTO "todo" VALUES('wikipedia-export',3);
INSERT INTO "todo" VALUES('wlan0',3);
INSERT INTO "todo" VALUES('wlan1',3);
INSERT INTO "todo" VALUES('xf',1);
INSERT INTO "todo" VALUES('xmlformat',3);
INSERT INTO "todo" VALUES('xt',1);
INSERT INTO "todo" VALUES('yd',1);
INSERT INTO "todo" VALUES('ydd',1);
INSERT INTO "todo" VALUES('zero-to-lf',3);
COMMIT;
