#!/usr/bin/perl

# tab
# File ID: 126a11d4-5d46-11df-950e-90e6ba3022ac

$Tabs = $ARGV[0] ? $ARGV[0] : 1;

while (<STDIN>) {
	for (1..$Tabs) {
		print "\t";
	}
	print "$_";
}

#### End of file tab ####
