#!/usr/bin/perl
# $Id: tab,v 1.1 1999/02/10 02:15:56 sunny Exp $

$Tabs = $ARGV[0] ? $ARGV[0] : 1;

while (<STDIN>) {
	for (1..$Tabs) {
		print "\t";
	}
	print "$_";
}

#### End of file $Id: tab,v 1.1 1999/02/10 02:15:56 sunny Exp $ ####
