#!/bin/sh

#==========================================================
# $Id: tail-errorlog,v 1.13 2002/03/08 01:28:48 sunny Exp $
# tail -f på error_log til httpd(8).
#==========================================================

if [ -e /sunba.mrk ]; then
	tail -f /var/log/apache/error.log $*
elif [ -e /grimme.mrk -o -e /recbb.mrk -o -e /toshbb.mrk ]; then
	tail -f /var/log/httpd/error_log $*
elif [ -e /ww.mrk ]; then
	if [ "$1" = "sunbase" ]; then
		shift
		tail -f /home/badata/wrt/sunbase/log/httpd/error_log $*
	else
		tail -f /mnt/logs/httpd/$1/error_log $*
		shift
	fi
else
	echo $0: Ukjent maskin, kan ikke skrive ut error_log >&2
	exit 1
fi
