#!/bin/sh

#==========================================================
# $Id: tail-errorlog,v 1.16 2002/11/08 22:58:16 sunny Exp $
# tail -f på error_log til httpd(8).
#==========================================================

if [ -e /sunba.mrk -o -e /carmbb.mrk -o -e /svdbb.mrk ]; then
	tail -f /var/log/apache/error.log $*
elif [ -e /grimme.mrk -o -e /recbb.mrk -o -e /toshbb.mrk -o -e /ba0614.mrk ]; then
	tail -f /var/log/httpd/error_log $*
elif [ -e /nett.mrk ]; then
	if [ "$1" = "sunbase" -o "$1" = "sunbase.org" ]; then
		shift
		tail -f /home/badata/wrt/sunbase/log/httpd/error_log $*
	else
		tail -f /mnt/logs/httpd/$1/error_log $*
		shift
	fi
else
	echo $0: Ukjent maskin, kan ikke skrive ut error_log >&2
	exit 1
fi
