#!/bin/sh

# $Id$
# Viser størrelsen på en tar-fil av en directory.

if [ $# -eq 0 ]; then
	DIR="."
else
	DIR=$1
fi

echo "Upakket: `tar cf - $DIR 2>/dev/null | wc -c`"
echo "Pakket : `tar czf - $DIR 2>/dev/null | wc -c`"
