#!/bin/sh

# tarsize
# File ID: 68aa6aee-5d46-11df-a094-90e6ba3022ac
# Viser størrelsen på en tar-fil av en directory.

if [ $# -eq 0 ]; then
	DIR="."
else
	DIR=$1
fi

echo "Upakket: `tar cf - $DIR 2>/dev/null | wc -c`"
echo "Pakket : `tar czf - $DIR 2>/dev/null | wc -c`"
