#!/bin/bash

#=======================================================================
# testfail
# File ID: 8ccc15ec-0049-11e1-b1a1-fefdb24f8e10
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

cd ~/build-git || exit 1
git clean -qfxd
git checkout -f
echo $(git bisect visualize --format=oneline | wc -l) commits left:
git lb --color | head -200
echo
make || { echo testfail: exit SKIP >&2; exit 125; }
