#!/bin/sh

#==============================================================================
# til-kron
# File ID: b4f0f5ce-4564-11ef-bb0e-83850402c3ce
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=til-kron
VERSION=0.0.0

opt_help=0
opt_quiet=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-h|--help) opt_help=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

GIT=git

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Move files downloaded by yt-dlp and youtube-dl to Kron/YYYY/MM/DD/.

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
	exit 0
fi

topdir="$($GIT rev-parse --show-toplevel)"
tmpfile=".$progname.tmp"
ls -1N *.json | sort >"$tmpfile"

cmd="SELECT printf("
cmd="$cmd'unset y m d;"
cmd="$cmd y=%s; m=%s; d=%s;"
cmd="$cmd if [ -n \"\$y\" -a -n \"\$m\" -a -n \"\$d\" ]; then"
cmd="$cmd mkdir -p \"$topdir/Kron/\$y/\$m/\$d\";"
cmd="$cmd $GIT mv -v"
cmd="$cmd *\"%s\"*"
cmd="$cmd \"$topdir/Kron/\$y/\$m/\$d/\";"
cmd="$cmd fi;',"
cmd="$cmd substr(upload_date, 1, 4),"
cmd="$cmd substr(upload_date, 6, 2),"
cmd="$cmd substr(upload_date, 9, 2),"
cmd="$cmd ytid"
cmd="$cmd)"
cmd="$cmd FROM yt;"

list-youtube -F "$tmpfile" -S "$cmd" | sh
rm -f "$tmpfile"

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
