#!/usr/bin/perl -w

# $Id$
# Converts gg°mm'ss.sss" to gg°mm.mmmmm'

use strict;

if ($#ARGV < 2) {
	die(<<END);

Syntax: $0 degrees minutes secons

Converts gg°mm'ss.sss" to gg°mm.mmmmm'
Decimal values can be used.

END
}

my ($Deg, $Min, $Sec) = @ARGV;
my $new_min = $Min+($Sec/60);

print("$Deg°$new_min'\n");

__END__
