#!/usr/bin/perl -w

# $Id: tosec,v 1.1 2001/04/02 20:03:40 sunny Exp $
# Mottar datoer på kommandolinja og konverterer dem til sekunder siden 1970.
# Format: ååååmmddTttmmss med valgfri Z på slutten for GMT

use strict;
use Time::Local;

foreach(@ARGV) {
	my ($Year, $Mon, $Day, $Hour, $Min, $Sec) = (0, 0, 0, 0, 0, 0);
	if (/((?:19|20)\d\d)([01]\d)([0-3]\d)T([0-2]\d)([0-5]\d)([0-6]\d)(Z?)/) {
		if ($7 eq "Z") {
			print(timelocal($6, $5, $4, $3, $2-1, $1));
		} else {
			print(timegm($6, $5, $4, $3, $2-1, $1));
		}
	}
	print("\n");
}
