#!/bin/bash

#=======================================================================
# tuxguitar
# File ID: 335cff5c-df3e-11e5-91a8-99c8fc62a08c
#
# Wrapper to start TuxGuitar.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=tuxguitar
VERSION=0.1.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

prgdir=/usr/local/prg/tuxguitar

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Start TuxGuitar from everywhere on the system. Expects tuxguitar.sh to 
be stored in $prgdir/ .

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

if test -e "$prgdir/tuxguitar.sh"; then
    cd "$prgdir" || {
        echo $progname: Cannot chdir to /usr/local/prg/tuxguitar/ >&2
        exit 1
    }
    ./tuxguitar.sh "$@"
else
    echo $progname: $prgdir/tuxguitar.sh not found >&2
    exit 1
fi
