#!/usr/bin/perl -w

# uh2dec
# File ID: e880bd0e-5d46-11df-aacd-90e6ba3022ac
# Konverterer fra hex-entities til desimal.
# Til ære for teite Netscape som ikke takler hex.

use strict;

while (<>) {
	s/&#x([0-9a-f]{1,4});/sprintf("&#%u;", hex($1))/gei;
	print;
}
