#!/usr/bin/perl -w

# unicode_htmlchart
# File ID: 29d61fce-5d47-11df-9c4e-90e6ba3022ac
# Skriv ut en dunge med Unicode-entities. For browsertest.

use strict;

for (0..65599) {
	$_ % 32 || printf("<br>\n%04X ", $_);
	print("&#$_;");
}
print("\n");
