#!/usr/bin/perl -w

# $Id: unicode_htmlchart,v 1.2 2003/10/08 15:08:10 sunny Exp $
# Skriv ut en dunge med Unicode-entities. For browsertest.

use strict;

for (0..65599) {
	$_ % 32 || printf("<br>\n%04X ", $_);
	print("&#$_;");
}
print("\n");
