#!/usr/bin/perl -w

#===============================================================
# $Id$
# Filtrerer bort duplikater i ~/log/df.log .
# Character set: UTF-8
# License: GNU General Public License
# ©opyleft 2003 Øyvind A. Holm <sunny@sunbase.org>
#===============================================================

use strict;

$| = 1;

my $last_val = 0;

while (<>) {
	chomp;
	if (/^(\S+) (\d+)/) {
		unless ($2 eq $last_val) {
			print("$1 $2\n");
		}
		$last_val = $2;
	}
}

__END__

# vim: set fileencoding=UTF-8 filetype=perl foldmethod=marker foldlevel=0 :
# End of file $Id$
