#!/usr/bin/env bash

#=======================================================================
# upd
# File ID: 27f00bc8-0903-11de-ac56-000475e441b9
#
# List all directories in the subtree, sorted by size
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=upd
VERSION=0.2.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

List all directories in the subtree, sorted by size

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

DUFILE=du.dat

echo \# $(
    suuid -m -t upd -w o --raw -c "<c_upd> <host>$(
        hostname)</host> <directory>$(/bin/pwd)</directory> </c_upd>"
) >$DUFILE
grep -q '^# ........-....-....-....-............$' $DUFILE || {
    echo upd: Error generating uuid, aborting. >&2
    exit 1
}
du --si -x |
    sort -h |
    perl -e '
    while (<>) {
        s/^(\d{3,})/commify($1)/ge;
        print;
    }
    sub commify {
        my $Str = reverse $_[0];
        $Str =~ s/(\d\d\d)(?=\d)(?!\d*\,)/$1\./g;
        return scalar reverse $Str;
    }' >>$DUFILE
echo -n "# smsum:" >>$DUFILE
echo $(smsum <$DUFILE) >>$DUFILE
chmod 600 $DUFILE
chown sunny.sunny $DUFILE
rm -f $DUFILE.gz
afv $DUFILE
tail -n 200 $DUFILE
