#!/bin/sh

# $Id: upd,v 1.5 2000/04/18 17:22:45 sunny Exp $
# Lister ut alle directoryene og sorterer dem etter størrelse

DUFILE=du.dat

du -kx | sort -n >$DUFILE
chmod 600 $DUFILE
chown sunny.sunny $DUFILE
rm -f $DUFILE.gz
tail -n 200 $DUFILE
