#!/bin/sh

# $Id$
# Lister ut alle directoryene og sorterer dem etter størrelse

DUFILE=du.dat

echo \# `suuid -t upd -c "~/bin/upd in $(hostname):$(/bin/pwd)"` >$DUFILE
du -kx | sort -n | perl -e 'while (<>) { s/^(\d{3,})/commify($1)/ge; print; } sub commify { my $Str = reverse $_[0]; $Str =~ s/(\d\d\d)(?=\d)(?!\d*\,)/$1\./g; return scalar reverse $Str; }' >>$DUFILE
chmod 600 $DUFILE
chown sunny.sunny $DUFILE
rm -f $DUFILE.gz
afv $DUFILE
tail -n 200 $DUFILE
