#!/usr/bin/perl -w

#==============================================================================
# urlstrip
# File ID: d58ab23a-5d47-11df-a6aa-90e6ba3022ac
# Plukker ut urler fra en fil til bruk for sjekking av linker med wget --spider
#==============================================================================

use strict;

while(<>) {
	chomp;
	if (/(http\S+?)"/i) {
		my $Curr = $1;
		$Curr =~ s/&amp;/&/g;
		print("$Curr\n");
	}
}
