#!/bin/bash

#=======================================================================
# urm
# File ID: e32b9fb2-5d47-11df-a745-90e6ba3022ac
# Ultraremove. En omvei for å fjerne kataloger i svn som har 
# svn:externals som kødder seg ved update.
#=======================================================================

[ -e "$@" ] || { echo $@: Finnes visst ikke. >&2; exit 1; }
svn pd svn:externals -R "$@"
svn rm --force "$@"
