#!/bin/bash

#=======================================================================
# $Id$
# Ultraremove. En omvei for å fjerne kataloger i svn som har 
# svn:externals som kødder seg ved update.
#=======================================================================

[ -e "$@" ] || { echo $@: Finnes visst ikke. >&2; exit 1; }
svn pd svn:externals -R "$@"
svn rm --force "$@"
