#!/usr/bin/perl -w

# usedchars
# File ID: 2b47bfdc-5d49-11df-83a7-90e6ba3022ac
# Lister ut tegn som er brukt i en fil. Bruker HTML-entities
# for enkelhets skyld. Kjør gjennom "h2u -l" eller recode(1).

use strict;

my $Char;
my %Hash; # Gjerne det

defined($ARGV[0]) || die("Syntax: $0 file [...]\n");

foreach (@ARGV) {
	if (open(FP, "<$_")) {
		while (sysread(FP, $Char, 1)) {
			$Hash{$Char}++;
		}
	} else {
		warn("$_: Unable to open file for read: $!");
	}
}

while (my ($a, $b) = each %Hash) {
	printf("&#x%02X; : %u\n", ord($a), $b);
}
