#!/bin/bash

#=======================================================================
# v_mergetool
# File ID: 91cda01a-85a3-11de-9d58-00248cd5cf1e
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

v -t c_mergetool -- -d "$@"
