#!/bin/sh

# $Id: view_df,v 1.1 2003/09/30 05:00:28 sunny Exp $

deep ~/log/df.log | grep $* | tr '\t' ' ' | tr -s ' ' | cut -d ' ' -f 1,5 | unik_df | ep >~/log/data
cd ~/log
statplot
# deep df.log | grep hda2 | tail -100 | tr '\t' ' ' | tr -s ' ' | cut -d ' ' -f 1,5 | ep >data ; statplot
