#!/bin/bash

# $Id$

gptrans_conv -o xgraph "$@" | rmspcall | uniq | xgraph -fmtx %.05f -fmty %.05f
# gptrans_conv -o clean "$@" >/tmp/v.dat
# cat <<END | gnuplot -persist
# set mouse
# plot "/tmp/v.dat" w l 3
# pause -1
# END
