#!/bin/bash

#=======================================================================
# wav_to_mp3
# File ID: ffabc804-0665-11e3-a941-a088b4ddef28
# Convert .wav files to .mp3
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=wav_to_mp3
VERSION=0.1.0

ARGS="$(getopt -o "\
h\
q\
v\
" -l "\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1" -o -z "$1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Usage: $progname [options] wav_file [...]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    if test -n "$1"; then
        exit 0
    else
        exit 1
    fi
fi

tmpuuid=$(suuid -m -t c_wav_to_mp3 -wa -c "Starting conversion")
test -z "$tmpuuid" && { echo "$progname: Broken suuid(1)" >&2; exit 1; }
for curr in "$@"; do
    echo
    echo ======== $(ls -l "$curr")
    noext=$(basename "$curr" .wav)
    wavfile="$noext.wav"
    mp3file="$noext.mp3"
    test -e "$mp3file" && { echo $mp3file: File already exists >&2; continue; }
    wavid=$(finduuid "$wavfile")
    wavid_str=
    test -n "$wavid" && wavid_str=" (File ID $wavid)"
    lame -h --tc $(suuid -m -t encode,c_wav_to_mp3 -wa -c "Converting $wavfile$wavid_str to mp3") "$wavfile" "$mp3file"
done
