#!/usr/bin/env bash

#=======================================================================
# wavto16
# File ID: e755fe92-820c-11e2-814c-0016d364066c
#
# Convert media files to 16 bit little endian .wav
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=wavto16
VERSION=0.2.0

ARGS="$(getopt -o "\
c:\
h\
q\
v\
" -l "\
channels:,\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_channels=''
opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        -c|--channels) opt_channels=$2; shift 2 ;;
        -h|--help) opt_help=1; shift ;;
        -q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        -v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        --version) echo $progname $VERSION; exit 0 ;;
        --) shift; break ;;
        *) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Convert media files to 16 bit little endian .wav . Works on all kinds of 
media files that Mplayer/Mplayer2 supports.

Usage: $progname [options] file [files [...]]

Options:

  -c NUM, --channels NUM
    Use NUM channels in the resulting .wav file.
  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

if test -z "$1"; then
    echo $progname: No files specified >&2
    exit 1
fi

if test -n "$opt_channels"; then
    echo "$opt_channels" | grep -qE '^[1-8]$' || {
        echo -n $progname: Argument to -c/--channels must be an integer >&2
        echo " between 1 and 8" >&2
        exit 1
    }
    chan_str=",channels=$opt_channels"
else
    chan_str=''
fi

for f in "$@"; do
    wavfile="$f"
    tmpfile="$f.tmp.wav"
    cp -p "$wavfile" "$wavfile.bck"
    mplayer -novideo -af format=s16le$chan_str \
      -ao "pcm:file=$tmpfile" "$wavfile"
    mv "$tmpfile" "$wavfile"
done
