#!/bin/bash

#=======================================================================
# wi
# File ID: afcf3af0-27a5-11e1-b643-4b2592583869
# [Description]
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=wi

msg() {
    echo $* >&2
}

unset test_simul
if test "$1" = "--test-simul"; then
    test_simul=1
    shift
fi

if test "$1" = "-h" -o "$1" = "--help"; then
    cat <<END

Search the suuids database and send results to stdout.

Syntax: $progname [options] [search expression]

Options:

    -h, --help
        Show this help.
    --test-simul
        If this is specified as first argument, don't actually do 
        anything. This will only send diagnostic messages to stderr. 
        Used by 'wi.t'.

END
    exit 0
fi

search_str=
stdin=

if test -z "$1"; then
    stdin="`finduuid -u`"
fi

unset or_str
for f in "$@" $stdin; do
    test -n "$test_simul" && msg f = \'$f\'
    search_str="$search_str ${or_str}s::varchar ILIKE '%$f%'"
    or_str="OR "
done

test -z "$search_str" && {
    echo $progname: No search strings found >&2
    exit 1
}

sql_str="COPY (SELECT s FROM uuids WHERE$search_str) TO STDOUT;"

if test -n "$test_simul"; then
    # --test-simul is specified as $1, only output what would've been 
    # done
    echo "$sql_str"
else
    echo "$sql_str" | psql suuids | sort -u | less
fi
