#!/bin/bash

#=======================================================================
# wi
# File ID: afcf3af0-27a5-11e1-b643-4b2592583869
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

search_str=
stdin=
if test -z "$1"; then
    stdin="`finduuid -u`"
fi
for f in "$@" $stdin; do
    search_str="$search_str -e $f"
done
grep -hi $search_str ~/src/git/uuids/*.xml ~/uuids/*.xml |
    sort -u |
    sortuuid |
    less
