#!/bin/bash

#=======================================================================
# wlan0
# File ID: b77ff690-5d49-11df-a33e-90e6ba3022ac
# Kjører opp wlan-kortet på carmbb og denslags.
#=======================================================================

[ "`whoami`" = "root" ] || { echo Det gjør seg å være root. >&2; exit 1; }

ifconfig ath0 down
