#!/usr/bin/perl -w

# xmlstrip
# File ID: 06bf7352-5d4a-11df-b044-90e6ba3022ac
# Remove everything inside and outside XML elements, in other words, 
# clean up the bastard.

my $Data = join("", <>);
$Data =~ s/>[^<>]+?</></gs;
$Data =~ s/\s*\n\s*[^\S\$]/ /gs;
print($Data);
