#!/usr/bin/env bash

#=======================================================================
# yd
# File ID: d01bb3d8-c764-11e1-8e09-00c0a8deee11
# [Description]
# License: GNU General Public License version 2 or later.
#=======================================================================

youtube-dl -o "%(title)s-%(id)s.%(ext)s" \
  --write-description --write-info-json \
  --write-sub --write-thumbnail --sub-lang en,en-US,no,nb \
  "$@"
