#!/bin/sh

#==============================================================================
# ydc
# File ID: cc9e58bc-9e74-11e8-ae29-db5caa6d21d3
#
# Wrapper around the yd* youtube-dl scripts, checks that the video hasn't been 
# downloaded before.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=ydc
VERSION=0.2.2

# FIXME: Hardcoding
dellog=/tmp/musikk-del.log
delloglock="$dellog.lock"
repo=/home/annex/musikk

if test "$1" = "--version"; then
	echo $progname $VERSION
	exit 0
fi

if test "$1" = "-h" -o "$1" = "--help"; then
	cat <<END

Wrapper around the yd* youtube-dl scripts, checks that the video hasn't 
been downloaded before. Works with links understood by the ydid(1) 
script.

Usage: $progname [options] YDPROG

Options:

  -h, --help
    Show this help.
  --version
    Print version information.

END
	exit 0
fi

ydprog=$1
if [ -z "$ydprog" ]; then
	echo $progname: Missing ydprog argument >&2
	exit 1
fi

until mkdir "$delloglock" 2>/dev/null; do
	echo $progname: $delloglock: Waiting for lockdir >&2
	sleep 1
done
(
	cd "$repo" && (
		git log --name-status --format= | grep ^D >"$dellog" || true
	)
)
rmdir "$delloglock" || exit 1

while :; do
	read -p "URL: " orig_gr
	test -z "$orig_gr" && continue
	gr=$(ydid "$orig_gr")
	test -z "$gr" && continue
	echo grep -- $gr
	(cd "$repo" && (find *; cat "$dellog")) | grep -- $gr ||
		($ydprog -- $(ydid -c "$orig_gr") &)
	if ls | grep -q -- -$gr\\.temp\\.; then
		rm -v *-$gr*.temp.*
	fi
done

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
