#!/usr/bin/env bash

#=======================================================================
# ydd
# File ID: 7989fb04-1193-11e3-9433-a088b4ddef28
# Download YouTube videoes with preferred quality and format
# License: GNU General Public License version 2 or later.
#=======================================================================

echo make -s lock\; yd -f \
136+250/\
136+249/\
136+251/\
136+140/\
136+bestaudio/\
247+250/\
247+249/\
247+251/\
247+140/\
247+bestaudio/\
22/\
18\
 "$@"\; make -s unlock\; randsleep -v 20 20 >>hent.sh
