#!/bin/sh

# $Id: afvctl,v 1.4.2.1 2003/05/29 13:02:26 sunny Exp $
# Starter/stopper/viser status for alle afv’er

afvdir=$AFVROOT$(/bin/pwd)
currstop=$afvdir/stop
dontstop=$afvdir/protected

case "$1" in
	start)
		echo -n Starter afv …
		rm -f $currstop
		retval=$?
	;;
	stop)
		echo -n Stopper afv …
		touch $currstop
		sleep 5
		rm $currstop
		retval=$?
	;;
	startall)
		echo -n Starter alle afv’er …
		rm -f $AFVROOT/stop
		retval=$?
	;;
	stopall)
		echo -n Stopper alle afv’er …
		touch $AFVROOT/stop
		sleep 5
		rm $AFVROOT/stop
		retval=$?
	;;
	stat*)
		ps auxw | grep afv | grep -v -e 'afvctl stat' -e 'grep afv' -e 'grep -v -e '
		retval=$?
		exit $retval;
	;;
	protect*)
		touch $dontstop
		echo Katalogen `/bin/pwd` er nå beskyttet mot «afvctl stop*».
	;;
	*)
		echo
		echo Syntax: $0 start\|stop\|stat
		echo
		exit 1
	;;
esac

if [ $retval = 0 ]; then
	echo OK
else
	echo FEIL \($retval\)
fi

exit $retval
