#!/bin/sh

# $Id: cdlabel,v 1.1.2.1 2002/03/08 00:43:05 sunny Exp $
# Skriver ut volume label på CDROM'en som står i.

# Først tar vi en fake read for å unngå error
until head -c 1 /dev/cdrom >/dev/null; do
	:
done

head -c 32840 /dev/cdrom | tail -c 32
