#!/usr/bin/perl

# $Id$
# Konverterer PGP/GPG-armor fra stdin. Kan ta mange om gangen.

$pwd_str = shift;
$gpg_header = "-----BEGIN PGP MESSAGE-----";
$gpg_footer = "-----END PGP MESSAGE-----";

$| = 1;

while (<>) {
	if (/^$gpg_header$/) {
		open(gpgFP, "|gpg --passphrase-fd 0") || die("Kan ikke åpne gpg-pipe: $!");
		print(gpgFP "$pwd_str\n$gpg_header\n");
		while (<>) { # Satser på at GPG kun tar meldingen og at den ikke spiser opp hele stdin.
			print(gpgFP "$_");
			/^$gpg_footer$/ && (close(gpgFP), last);
		}
	} else {
		print;
	}
}
