#!/usr/bin/perl

# $Id$
# Fjerner x antall TAB'er i begynnelsen av her linje.

$Tabs = $ARGV[0] ? $ARGV[0] : 1;

while (<STDIN>) {
	my $Linje = $_;
	for (1..$Tabs) {
		$Linje =~ s/^\t(.*)/$1/;
	}
	print "$Linje";
}

#### End of file $Id$ ####
