#!/usr/bin/perl -w

# $Id: gpsfold,v 1.1.2.2 2003/07/11 12:44:43 sunny Exp $
# Inserts fold marks in GPS data files before and after stdin.
# Select text in visual line mode and filter the block through this script.

use strict;

$| = 1;

my ($Indent, $Title) = ("", "");
my @Data = ();

defined($ARGV[0]) && ($Title = join(" ", @ARGV));
my $colon_str = (length($Title) ? ": " : "");

my $Line = <STDIN>;
$Line =~ /^(\s+)/ && ($Indent = $1);
my ($start_date, $end_date) = ("", "");
# push(@Data, $Line);

while (<STDIN>) {
	push(@Data, $_);
	unless (length($start_date)) {
		if ($Line =~ /(\d\d\d\d)-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d)(Z?)/) {
			$start_date = "$1$2${3}T$4$5$6$7";
		} elsif ($Line =~ /(\d\d\d\d\d\d\d\dT\d\d\d\d\d\dZ?)/) {
			$start_date = $1;
		} elsif ($Line =~ m#^1 (\S+) (\S+) (\S+) (\S+) (\d\d)/(\d\d)/(\d\d\d\d) (\d\d):(\d\d):(\d\d)#) {
			$start_date = "$7$5${6}T$8$9$10";
		}
	}
	if (/(\d\d\d\d)-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d)(Z?)/) {
		$end_date = "$1$2${3}T$4$5$6$7";
	} elsif (/(\d\d\d\d\d\d\d\dT\d\d\d\d\d\dZ?)/) {
		$end_date = $1;
	} elsif (m#^1 (\S+) (\S+) (\S+) (\S+) (\d\d)/(\d\d)/(\d\d\d\d) (\d\d):(\d\d):(\d\d)#) {
		$end_date = "$7$5${6}T$8$9$10";
	}
}

push(@Data, "$Indent# $start_date-$end_date$colon_str$Title \x7D\x7D\x7D\n");
unshift(@Data, "$Indent# $start_date-$end_date$colon_str$Title \x7B\x7B\x7B\n$Line");

for (@Data) {
	print $_;
}

# End of file $Id: gpsfold,v 1.1.2.2 2003/07/11 12:44:43 sunny Exp $
