#!/bin/sh

# Fyrer i gang httpd(8)
# $Id: h1,v 1.8 2002/02/19 10:26:24 sunny Exp $

if [ -e /ww.mrk ]; then
	/etc/rc.d/init.d/apache start
elif [ -e /toshbb.mrk ]; then
	apachectl start
elif [ -e /sunba.mrk ]; then
	/etc/init.d/apache start
elif [ -e /recbb.mrk ]; then
	/var/lib/apache/sbin/apachectl start
else
	echo Ukjent server, prøver standardløsning...
	if [ -x /etc/rc.d/init.d/httpd ]; then
		/etc/rc.d/init.d/httpd start
	elif [ -x /etc/init.d/apache ]; then
		/etc/init.d/apache start
	fi
fi
