#!/usr/bin/perl -w

#========================================================================
# $Id: hf,v 1.10.2.7 2004/01/07 02:51:27 sunny Exp $
# Formatterer HTML-source med TAB’er
#
# Laget av Øyvind A. Holm <sunny@sunbase.org>
# Lisens: GNU GPL
#
# FIXME: Hvis start+end-elementer står på samme linje, blir ikke
# innrykket rett. En eller annen rekursiv sjekk på linjene må kanskje
# gjøres. Foreløpig får man sette dem på hver sin linje.
#========================================================================

use strict;
use Getopt::Std;

our ($opt_a, $opt_h, $opt_i, $opt_H, $opt_s) = (0, 0, 0, 0);
getopts('ahHi:s');

my $is_pre = 0;
my $prog_name = $0;
$prog_name =~ s#.*/(.+?)$#$1#;

print_help() if ($main::opt_h);

$| = 1;

my $Tabs = "";
my $tab_indent = $main::opt_i;
my $orig_line = "";
my @Elements = (
	"applet", "blockquote", "body", "caption", "center", "colgroup",
	"div", "dl", "form", "frameset", "head", "html", "ol", "map",
	"noframes", "noscript", "select", "style", "table", "td",
	"th", "tr", "ul"
);

$tab_indent = 0 if ($tab_indent <= 0);

for (; $tab_indent; $tab_indent--) {
	$Tabs .= "\t";
}

my $line_exp = $main::opt_a ? '^\s+(.*)' : '^\t+(.*)';
my $header_indent = "";

LINE: while (<>) {
	# {{{
	my $Line = $_;
	my $Element = "";
	my $f = "";
	my $out_line;

	$main::opt_s && ($Line =~ /^%/) && (print($Line), next LINE); # Ignorer linjer som begynner med % hvis -s er spesifisert
	unless ($is_pre) {
		# $Line =~ $main::opt_s ? s/^\s+(.*?)\s+$/$1/ : s/^\t+(.*)/$1/;
		$Line =~ s/$line_exp/$1/;
		if ($main::opt_H && $Line =~ /<h([1-6]).*?>/i) {
			$header_indent = "\t" x ($1-1);
		}
		($Line =~ m!</body>!i) && ($header_indent = "");
		for $f (@Elements) {
			if ($Line =~ m!</($f)([ >])!i) {
				# Slutt-tag ble funnet {{{
				$Element = $1;
				$tab_indent--;
				$Tabs =~ s/\t$//;
				# $Line =~ s/($Element)/sprintf("\n%s%s", $Tabs, $1)/gei;
				# }}}
			}
		}
		$out_line = "$header_indent$Tabs$Line";
		$out_line =~ s/\s+$//g; # Fjern alle whitespace på slutten
		print "$out_line\n";
		for $f (@Elements) {
			if ($Line =~ m!<($f)([ >])!i) {
				# Start-tag ble funnet {{{
				$Element = $1;
				$tab_indent++;
				$Tabs .= "\t";
				# $Line =~ s/($Element)/sprintf("\n%s%s", $Tabs, $1)/gei;
				# }}}
			}
		}
	} else {
		print;
	}
	$is_pre = 1 if ($Line =~ /<(pre|script)\b.*>/i);
	$is_pre = 0 if ($Line =~ m!</(pre|script)>!i);
	# }}}
}

sub print_help {
	# {{{
	print <<END;

HTML formatter
Syntax: $0 [valg] [filer [...]]

Options:
  -a    Fjern space i begynnelsen av linja også før indenting.
  -h    Vis denne hjelpen
  -H    Legg til en TAB for hver <h1>, <h2>, <h3> osv for å lettere se
        strukturen i dokumentet.
  -i n  Start med n TAB’er som indent
  -s    Dropp linjer som her en % i starten. Det er datafilene på
        www.sunbase.org som er sånn.

END
	exit(0);
	# }}}
}

# End of file $Id: hf,v 1.10.2.7 2004/01/07 02:51:27 sunny Exp $
