#!/usr/bin/perl -w

#===============================================
# $Id: hhi,v 1.1.2.5 2002/10/01 15:31:01 sunny Exp $
# Html Header Indexer
# Made by Oyvind A. Holm <sunny@sunbase.org>
#===============================================

use strict;

my $last_level = 0;
my @header_num = qw{0};

while (<>) {
	chomp();
	if (!m#<!-- nohhi --># && m#^(.*)<(h)(\d+)(.*?)>(.*)#i) {
		my ($Pref, $H, $header_level, $Elem, $Rest) = ($1, $2, $3, $4, $5);
		if ($header_level > 1) {
			splice(@header_num, $header_level-1) if ($header_level < $last_level);
			$header_num[$header_level-2]++;
			my $tall_str = join(".", @header_num);
			$Rest =~ s/^([\d\s\.]+)(.*)/$2/;
			($tall_str .= ".") if ($header_level == 2);
			$_ = "${Pref}<${H}${header_level}${Elem}>$tall_str $Rest";
			$last_level = $header_level;
		}
	}
	print("$_\n");
}
