#!/bin/sh

# $Id$

# FIXME: Den locken virker ikke, det allokeres en ny tty.

lockname=$HOME/lock/`tty`
echo lockname = "$lockname"

until mkdir -p $lockname 2>/dev/null; do
	echo $0: $lockname: Venter på lock... >&2
	sleep 5
done

script -f $HOME/.scriptlogger/`u`.$$.scrlog
date -Iseconds
stty -a
