#!/usr/bin/perl -w

#========================================================
# $Id: lsreadable,v 1.4 2001/06/05 05:16:32 sunny Exp $
# Leser filnavn fra stdin eller en fil og skriver ut alle
# som er lesbar.
#========================================================

while (<>) {
	chomp;
	-r $_ && print("$_\n");
}
