#!/bin/bash

# $Id: mp3_to_ogg,v 1.2 2002/12/02 09:36:54 sunny Exp $
# Konverterer alle *.mp3-filene til ogg i en egen katalog.

CHARSET=UTF-8
remove_files=0

[ "$1" = "-r" ] && { remove_files=1; shift; }
[ "$1" = "" ] && { echo "Syntax: $0 [-r] kvalitet" >&2; exit 1; }
KVAL=$1
[ -d "ogg" ] || mkdir ogg || { echo "Klarte ikke mkdir ogg" >&2; exit 1; }
for f in *.mp3; do
	if [ -e "$f" ]; then
		echo $f;
		mpg321 --wav - "$f" | oggenc -q$KVAL -c "encoding=`oggenc --version 2>&1` -q$KVAL" -o $(echo ogg/$f|perl -pe "s/\\.mp3\$//" |tr ' ' _).q$KVAL.ogg -
		[ "$remove_files" = "1" ] && rm -v "$f"
	else
		echo $f finnes ikke. Driter i den.
	fi
done
