#!/bin/sh

# $Id: nets,v 1.2.2.1 2002/04/18 16:06:42 sunny Exp $
# Hælvetes føkkings Netscrape kødder seg bestandig, så her gjør vi kort
# prosess og myrder driten.

if [ -e /sunba.mrk ]; then
	killall -9 communicator-smotif.real
else
	killall -9 netscape-navigator netscape-communicator
fi
