#!/usr/bin/perl

# $Id: pakkut,v 1.2 2000/03/01 15:43:11 sunny Exp $

open(PipeFP, "| uudecode | gzip -d") or die("$0: Can't open pipe: $!\n");
while (<>) {
	s/[#%]//g;
	s/^\s+(.*)/$1/;
	print PipeFP $_;
}
