#!/bin/bash

# $Id: pine,v 1.2 2002/04/10 12:15:24 sunny Exp $
# Locking for pine

lockdir=/home/sunny/lock
[ -d $lockdir ] || mkdir $lockdir || { echo "$lockdir: Klarte ikke mkdir" >&2; exit 1; }
lockname=$lockdir/pine
until mkdir $lockname 2>/dev/null; do
	echo "$0: $lockname: Venter på at \"`cat $lockname/info`\" skal slippe locken..." >&2
	sleep 2
done
echo "$(tty) $(date +"%Y-%m-%d %H:%M:%S")" >$lockname/info

/usr/local/bin/pine $*

rm $lockname/info
rmdir $lockname
