#!/bin/sh

#=================================================
# $Id$
# Fjerner rot med tekstattributter i tillegg.
# Pluss at den setter tastaturhastigheta hvis det
# er nødvendig.
#=================================================

[ -x /usr/bin/reset ] || { echo $0: reset\(1\) ligger ikke under /usr/bin. Kvifor not? >&2; exit 1; }

/usr/bin/reset
printf "\x1b[0m"
[ -x ~/bin/kbd ] && ~/bin/kbd
