#!/usr/bin/perl -w

# $Id$
# Sjekker at en CD er brent riktig. Leser en fil på dette formatet:
# MD5 størrelse navn

while(<>) {
	if (/^([0-9a-f]{16}\s+(\d+)\s+(.*)$/) {
		print("\n");
		my ($Md5, $Size, $Name) = ($1, $2, $3);
		my $Result = `head -c $Size </dev/cdrom | md5sum`;
		print("MD5 av $Name:  $Result\n");
		print("Skulle være : $Md5\n");
		print((substr($Result, 0, 16) == substr($Md5, 0, 16)) ? "$Name:  $Name: Feil i md5sum);
	} else {
		warn("$0: Linje $.: Feil format.\n");
	}
}
