#!/bin/sh

# $Id: slogg,v 1.1 2001/08/29 13:20:09 sunny Exp $
# Setter en entry med klokkeslett inn i dbk. Leser fra stdin.
# Funker på samme måte som logg, men legger inn PATH.
# Kan kjøres av root.

PATH=/home/badata/Stable/bin:$PATH
HOME=/home/sunny

dbk -t -b -i - $*
