#!/usr/bin/perl -w

# $Id: snu_epstat,v 1.1.2.1 2002/04/18 16:06:43 sunny Exp $
# Snur outputen fra epstat,v 1.3 og tidlligere og plasserer datoen først.

use strict;

while (<>) {
	if (/^\s+(\d+)\s+(.*)$/) {
		# s/ /\t/;
		print("$2\t$1\n");
	} else {
		print;
	}
}
