#!/bin/sh

#==========================================================
# $Id: tail-errorlog,v 1.12 2001/10/11 11:46:51 sunny Exp $
# tail -f på error_log til httpd(8).
#==========================================================

if [ -e /sunba.mrk ]; then
	tail -f /var/log/apache/error.log $*
elif [ -e /grimme.mrk -o -e /recbb.mrk -o -e /toshbb.mrk ]; then
	tail -f /var/log/httpd/error_log $*
elif [ -e /ww.mrk ]; then
	tail -f /home/httpd/logs/error_log $*
else
	echo $0: Ukjent maskin, kan ikke skrive ut error_log >&2
	exit 1
fi
