#!/bin/sh

# $Id: tarsize,v 1.1 1999/04/21 13:06:44 sunny Exp $
# Viser størrelsen på en tar-fil av en directory.

if [ $# -eq 0 ]; then
	DIR="."
else
	DIR=$1
fi

echo "Upakket: `tar cf - $DIR 2>/dev/null | wc -c`"
echo "Pakket : `tar czf - $DIR 2>/dev/null | wc -c`"
