#!/usr/bin/perl -w

# $Id: uh2dec,v 1.1 2001/02/07 03:27:43 sunny Exp $
# Konverterer fra hex-entities til desimal.
# Til ære for teite Netscape som ikke takler hex.

use strict;

while (<>) {
	s/&#x([0-9a-f]{1,4});/sprintf("&#%u;", hex($1))/gei;
	print;
}
