#!/bin/bash

#=======================================================================
# $Id$
# File ID: 948f70c2-f989-11dd-be4a-000475e441b9
# [Description]
# License: GNU General Public License version 2 or later.
#=======================================================================

[ -z "$1" ] && { echo Syntax: $0 testname >&2; exit 1; }

name=$1
std perl-tests $name.t -t progname=$name -t exec=../$name -t testcmd=$name.t
mergesvn -s ../Lib/std/perl-tests $name.t
