#!/bin/bash

#=======================================================================
# $Id$
# [Description]
# License: GNU General Public License version 2 or later.
#=======================================================================

[ -z "$1" ] && { echo Syntax: $0 testname >&2; exit 1; }

name=$1
std perl-tests $name.t -t progname=$name -t exec=../$name -t testcmd=$name.t
