#!/bin/bash

#=======================================================================
# Genlog
# File ID: 20281518-f989-11dd-98ac-000475e441b9
# Update files in log/
# License: GNU General Public License version 3 or later.
#=======================================================================

[ -z "$1" ] && { echo "Syntax: $0 testname [testname [...]]" >&2; exit 1; }

mkdir -p log
maxlen=0
retval=0

for gf in "$@"; do
    currlen=`echo -n $gf | perl -pe 's/\.t$//' | wc -c`
    [ $currlen -gt $maxlen ] && maxlen=$currlen
done

for gf in "$@"; do
    testname=$gf
    testname=`echo -n $testname | perl -pe 's/\.t$//'`
    printf "%${maxlen}s.t: " $testname
    ./$testname.t --all 2>&1 | remove_perltestnumbers >log/$testname.log
    not_ok_count=$(grep "^not ok -" log/$testname.log | wc -l | tr -d ' ')
    if [ $not_ok_count -gt 0 ]; then
        not_ok_str=", $not_ok_count not ok"
        retval=1
    else
        unset not_ok_str
    fi
    printf "%2u ok%s\\n" $(grep "^ok -" log/$testname.log | wc -l) "$not_ok_str"
done

exit $retval
