#!/bin/sh

#==============================================================================
# mob
# File ID: cb5687fe-9c5a-11eb-915d-45c42403b986
#
# Keep an eye on mobile data usage
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=mob
VERSION=0.1.1

opt_help=0
opt_quiet=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-h|--help) opt_help=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Usage: $progname [options] [bytes_used]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
	exit 0
fi

t_bold=$(tput bold)
t_green=$(tput setaf 2)
t_red=$(tput setaf 1)
t_reset=$(tput sgr0)

bytes=$(echo -n "$1" | tr a-z A-Z)

if test -z "$bytes"; then
	if spar mobil -s | tail -1 | grep -q ^-; then
		echo -n "$t_bold$t_green"
	else
		echo -n "$t_bold$t_red"
	fi
	spar mobil -sg | numfmt --to=si --format=%7.2f --invalid=ignore \
	                        --round=nearest
	echo -n "$t_reset"
else
	spar mobil -sgc $(numfmt --from si --round=nearest $bytes) >/dev/null
	$0
fi

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
