#!/bin/sh

#==============================================================================
# mob
# File ID: cb5687fe-9c5a-11eb-915d-45c42403b986
#
# Keep an eye on mobile data usage
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=mob
VERSION=0.3.1

opt_help=0
opt_month=0
opt_quiet=0
opt_verbose=0
opt_wifi=0
while test -n "$1"; do
	case "$1" in
	-h|--help) opt_help=1; shift ;;
	-m|--month) opt_month=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	-w|--wifi) opt_wifi=1; shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Usage: $progname [options] [bytes_used]
       $progname [options] undo
       $progname [options] -m|--month YEAR MONTH QUOTA

Options:

  -h, --help
    Show this help.
  -m YEAR MONTH QUOTA, --month YEAR MONTH QUOTA
    Initialize statistics for a new month. SI or binary units can be 
    used for quota, for example "100G" or "100Gi".
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  -w. --wifi
    Use database "wifi.spar" instead of "mobil.spar".
  --version
    Print version information.

The "undo" command deletes the newest entry in the database. It also 
prints an INSERT statement to stdout in case you regret the deletion.

END
	exit 0
fi

[ "$opt_wifi" = "1" ] && dbname=wifi || dbname=mobil
db=~/spar/$dbname.spar
t_bold=$(tput bold)
t_green=$(tput setaf 2)
t_red=$(tput setaf 1)
t_reset=$(tput sgr0)

test -e "$db" || { echo $progname: $db: Database not found >&2; exit 1; }

if test "$opt_month" = "1"; then
	test -z "$3" && { echo $progname: Missing arguments >&2; exit 1; }
	year=$1
	month=$2
	quota=$(echo "$3" | tr a-hj-z A-HJ-Z \
	        | numfmt --from=auto --round=nearest)
	test -z "$quota" \
	&& { echo $progname: Invalid quota value >&2; exit 1; }
	start="$(sqlite3 :memory: \
	         "select(datetime(printf('%u-%02u-01', $year, $month), \
	                 'utc'))")"
	end="$(sqlite3 :memory: \
	       "select(datetime(printf('%u-%02u-01', $year, $month), \
	               '+1 month', 'utc'))")"
	test -z "$start" -o -z "$end" \
	&& { echo $progname: Invalid date >&2; exit 1; }

	sqlite3 "$db" "SELECT * FROM account WHERE date = '$start'" \
	| grep -q . \
	&& { echo $progname: Month already registered >&2; exit 1; }

	if [ "$opt_wifi" = "1" ]; then
		c_str=$quota
		bv_str=$quota
		ev_str=0
	else
		c_str=0
		bv_str=0
		ev_str=$quota
	fi
	spar $dbname --now "$start" --bt "$start" --et "$end" \
	             --bv $bv_str --ev $ev_str -c $c_str -sgv
	exit 0
fi

if [ "$1" = "undo" ]; then
	edate=$(sqlite3 $db "SELECT max(date) FROM account;")
	ecurr=$(sqlite3 $db "SELECT current FROM account
	                       WHERE date = '$edate';")
	if [ -z "$edate" ]; then
		echo $progname: $db: No entries found in account table >&2
		exit
	fi
	echo $progname: Deleting entry \"$edate\" >&2
	cat <<END | sqlite3 $db
SELECT printf('INSERT INTO account VALUES(''%s'', %u);', '$edate', $ecurr);
DELETE FROM account WHERE date = '$edate';
END
	exit
fi

bytes=$(echo -n "$1" | tr a-z A-Z)

if test -z "$bytes"; then
	if spar $dbname -s | tail -1 | grep -q ^-; then
		echo -n "$t_bold$t_green"
	else
		echo -n "$t_bold$t_red"
	fi
	spar $dbname -sg | numfmt --to=si --format=%7.4f --invalid=ignore \
	                          --round=nearest
	spar $dbname -W et | numfmt --to=si --format=%7.4f --invalid=ignore \
	                            --round=nearest
	echo -n "$t_reset"
else
	spar $dbname -sgc $(numfmt --from si --round=nearest $bytes) >/dev/null
	$0 $([ "$opt_wifi" = "1" ] && echo -w)
fi

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
