#!/bin/sh

#=======================================================================
# $URL$
# $Id$
# Filtrerer bort hits som jeg og søkemotorer har laget på sunbase.org .
# Og andre steder for den saks skyld.
#=======================================================================

egrep -v \
-e '^194\.248\.216\.(3|19|20) ' \
-e '^18\.29\.1\.50 ' \
-e '^194\.63\.248\.10 ' \
-e '^80\.203\.225\.187 - - ' \
-e 'GET /favicon\.ico HTTP' \
-e '(http://help.yahoo.com/help/us/ysearch/slurp|Ask Jeeves/Teoma|BravoBrian|NPBot|Scooter/3\.2|Googlebot|Mediapartners-Google|ia_archiver|WISEnutbot|search.msn.com/msnbot.htm|Netcraft Web Server Survey|slurp@inktomi\.com|girafabot|TurnitinBot|SurveyBot)' \
$*
