#!/bin/sh

# $Id$

[ -e /carmbb.mrk ] || exit 0;

logdir=$HOME/log

[ -r $logdir/.disks ] || { echo "$logdir/.disks finnes ikke, avbryter." >&2; exit 1; }

df -P `cat $logdir/.disks` | grep / | perl -pe 's/^/now() /;' | tr -s ' ' | tr -d '%' | psql df -c "copy df from stdin delimiter ' '"
