#!/bin/bash

#=======================================================================
# $Id$
# Kjører opp nettverket på carmbb.
#=======================================================================

if [ -e /carmbb.mrk ]; then
    killall ssh
    /etc/init.d/networking start
else
    echo "$0: Må være på carmbb" >&2
    exit 1
fi
