#!/bin/bash

#=======================================================================
# $Id$
# Kjører opp wlan-kortet på carmbb og denslags.
#=======================================================================

[ "`whoami`" = "root" ] || { echo Det gjør seg å være root. >&2; exit 1; }

ifconfig ath0 down
