#!/usr/bin/perl

# $Id$
# Setter GPG-armor i <p><pre></pre>.

while (<>) {
	s/^-----BEGIN PGP MESSAGE-----$/<p><pre>\n-----BEGIN PGP MESSAGE-----/;
	s/^-----END PGP MESSAGE-----$/-----END PGP MESSAGE-----\n<\/pre>/;
	print;
}
