#!/bin/bash

#=======================================================================
# $Id$
# Skjermdump i X.
# File ID: 64a02bf2-3e32-11de-b61f-000475e441b9
#=======================================================================

scrdumpdir=$HOME/screendumps

[ -d $scrdumpdir/. ] || mkdir $scrdumpdir || { echo "$0: $scrdumpdir: Cannot create directory" >&2; exit 1; }

sleep 5
# import-programmet hører med til ImageMagick.
import -w root $scrdumpdir/$(date -u +"%Y%m%dT%H%M%SZ").$(hostname)-screendump.png
