#!/bin/bash

#=======================================================================
# $Id$
# File ID: b97a9c12-85a3-11de-bf51-00248cd5cf1e
# [Description]
# License: GNU General Public License version 2 or later.
#=======================================================================

v -t c_difftool -- -d "$@"
