#!/bin/bash

#=======================================================================
# $Id$
# File ID: a78bdf36-fafa-11dd-a4a9-000475e441b9
# For synkronisering av POI og waypoints fra uniten.
# License: GNU General Public License version 2 or later.
#=======================================================================

gpst -o pgwtab ~/gps/unit/wpdata.gpx ~/gps/poi/trans/*.gpx | \
    psql gps -a -c "TRUNCATE tmpwayp; COPY tmpwayp (coor, name, ele, type, time, cmt, descr, src, sym) FROM STDIN;"
psql gps -a -c "UPDATE tmpwayp SET coor = point(round(coor[0]::numeric, 6), round(coor[1]::numeric, 6));"
psql gps -a -c "COPY (SELECT coor, name FROM tmpwayp WHERE type IS NULL ORDER BY coor[0] desc, coor[1]) TO '/tmp/un';"
psql gps -a -c "COPY (SELECT coor, name FROM tmpwayp WHERE type IS NOT NULL ORDER BY coor[0] desc, coor[1]) TO '/tmp/p';"

if [ "$1" = "-d" ]; then
    diff -u /tmp/un /tmp/p
else
    vimdiff /tmp/un /tmp/p
fi
