#!/bin/bash
#=======================================================================
# $Id$
# For synkronisering av POI og waypoints fra uniten.
#=======================================================================

gpst -o pgwtab ../unit/wpdata.gpx ../poi/trans/*.gpx | psql gps -a -c "TRUNCATE tmpwayp; COPY tmpwayp FROM STDIN;"
psql gps -a -c "UPDATE tmpwayp SET coor = point(round(coor[0]::numeric, 5), round(coor[1]::numeric, 5));"
psql gps -a -c "COPY (SELECT coor, name FROM tmpwayp WHERE type IS NULL ORDER BY coor[0] desc, coor[1]) TO '/tmp/un';"
psql gps -a -c "COPY (SELECT coor, name FROM tmpwayp WHERE type IS NOT NULL ORDER BY coor[0] desc, coor[1]) TO '/tmp/p';"

if [ "$1" = "-d" ]; then
    diff -u /tmp/un /tmp/p
else
    vimdiff /tmp/un /tmp/p
fi
