#!/bin/bash

#=======================================================================
# $Id$
# En liten sak som jeg fikk hos Mike Menk.
#=======================================================================

gpsbabel -i gpx -f $1 -x discard,hdop=2 -o gpx -F $(basename $1 .gpx ).del_hdup2.gpx
