#!/bin/bash

# $Id$

# Må gjøre det på den krøkkete måten her pga at vimdiff ikke klarer å
# lese fifo’en i enkelte situasjoner av en eller annen grunn.
[ -d ~/tmp ] || mkdir ~/tmp || { echo "Klarte ikke mkdir ~/tmp" >&2; exit 1; }
tmp1=~/tmp/cvsvimdiff.$$.$RANDOM.1.tmp
tmp2=~/tmp/cvsvimdiff.$$.$RANDOM.2.tmp
cvscat $1 $2 >$tmp1
cvscat $1 $3 >$tmp2
vimdiff $tmp1 $tmp2
rm $tmp1 $tmp2
