#!/bin/bash

#=======================================================================
# $Id$
# Lager symlinker i current dir til alle filer som ligger nedenfor i 
# treet.
#=======================================================================

for f in `find -type f | ns`; do
    ln -sv $f `echo $f|tr / _|cut -c 3-`
done
