#!/usr/bin/perl -w

#==============================================================================
# $Id$
# Plukker ut urler fra en fil til bruk for sjekking av linker med wget --spider
#==============================================================================

use strict;

while(<>) {
	chomp;
	if (/(http\S+?)"/i) {
		my $Curr = $1;
		$Curr =~ s/&amp;/&/g;
		print("$1\n");
	}
}
