#!/bin/bash

#=======================================================================
# start-vncserver
# File ID: f2c80c9c-602f-11e2-9661-fefdb24f8e10
# Start vncserver
# License: GNU General Public License version 3 or later.
#=======================================================================

sess -- vncserver -depth 16 -geometry 1260x720 :1
