#!/bin/sh

#==============================================================================
# fra-tel
# File ID: e2b4cbf2-baff-11e8-97b6-c75b54f489f8
#
# Send files from $url to $dest with rsync, retry until it's done.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=fra-tel
VERSION=0.1.0

rcfile=~/.fra-telrc

opt_help=0
opt_quiet=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-h|--help) opt_help=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

Create the rcfile and define url (ssh address of source directory) and dest 
(local directory). For example:

url=user@fromhost:/home/user/tel/
dest=/sdcard/tel/

END
	exit 0
fi

cmd_rsync="rsync -rmvLPzz --inplace --timeout=30"

unset url dest
test -e "$rcfile" && . "$rcfile"

if test -z "$url" -o -z "$dest"; then
	echo $progname: url or dest not defined in $rcfile >&2
	exit 1
fi

ps | grep -v "grep $cmd_rsync" | grep "$cmd_rsync" && exit 1
until $cmd_rsync $url $dest; do
  date;
  sleep 2;
done

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
