#!/bin/bash

# Creates a .tar.gz file of current directory
# $Id$
# (C)opyleft 1999-2001 sunny256@mail.com
# License: GNU GPL

# FIXME: Finn ut av -r kombinert med -n

if [ "x$1" = "x--help" -o "x$1" = "x-h" ]; then
	cat <<END

Usage: $0 [options] name_without_the_tar_gz_extension

Creates a .tar.gz file of current directory tree and places it in
parent directory. If nothing is specified, current dir is used.

Options:

-g, --gpg     Use gpg instead of gzip
-h, --help    Print this help message
-n, --nocomp  No compression, leave as .tar
-r, --remove  Remove directory after packing

Options has to be specified in alphabethical order at the moment.

END
	exit 1
fi

if [ "x$1" = "x--gpg" -o "x$1" = "x-g" ]; then
	_packcmd="gpg -e"
	_packext=".gpg"
	shift
else
	_packcmd="gzip -vN"
	_packext=".gz"
fi

if [ "x$1" = "x--nocomp" -o "x$1" = "x-n" ]; then
	_no_compress=1
	shift
else
	_no_compress=0
fi

if [ "x$1" = "x--remove" -o "x$1" = "x-r" ]; then
	_can_erase=1
	shift
else
	_can_erase=0
fi

if [ $# -eq 0 ]; then
	_pwd=`pwd`
	_prefix=`basename $_pwd`
else
	_prefix=`basename $1`
fi

if [ -e ../$_prefix.tar -o -e ../$_prefix.tar$_packext ]; then
	echo $0: ../$_prefix.tar or ../$_prefix.tar$_packext already exists >&2
	exit 1
fi

if [ -e ../$_prefix -a ! ../$_prefix -ef . ]; then
	echo $0: ../$_prefix and current dir are not the same >&2
	exit 1
fi

if [ -e ../$_prefix -a ! -d ../$_prefix ]; then
	echo $0: ../$_prefix: Not a directory >&2
	exit 1
fi

if [ ! -e ../$_prefix ]; then
	cp -a . ../$_prefix || { echo "$0: Error running \"cp -a . ../$_prefix\"" >&2; exit 1; }
fi

if [ ! -d ../$_prefix ]; then
	echo $0: Unable to create directory ../$_prefix >&2
	exit 1
fi

cd .. || { echo "$0: Cannot \"cd ..\"" >&2; exit 1; }
tar cf $_prefix.tar $_prefix || { echo "$0: Error running \"tar cf $_prefix.tar $_prefix\" in parent dir" >&2; exit 1; }

if [ "$_no_compress" -eq "1" ]; then
	exit 1;
fi

$_packcmd $_prefix.tar || { echo "$0: Error running \"$_packcmd $_prefix.tar\" in parent dir" >&2; exit 1; }

if [ "$_packext" = ".gpg" ]; then
	gitwipe $_prefix.tar
	sync
	rm -f $_prefix.tar
fi

if [ "$_can_erase" -eq "1" ]; then
	rm -rf $_prefix || { echo "$0: $_prefix: Can't remove directory" >&2; exit 1; }
fi

#### End of file $Id$ ####
