#!/bin/bash

#===================================================
# $Id$
# diff beregnet for tekst som wrapper i hytt og pine
#===================================================

if [ "x$3" = "x" ]; then
	diff -u <(fmt -1 $1 | rmspcall) <(fmt -1 $2 | rmspcall)
else
	diff -U$3 <(fmt -1 $1 | rmspcall) <(fmt -1 $2 | rmspcall)
fi
