#!/bin/bash

#=======================================================================
# $Id: bash 2298 2008-07-08 22:53:17Z sunny $
# File ID: 3623557a-fa66-11dd-83e3-000475e441b9
# Latskap.
#=======================================================================

uuid=`suuid -t c_m -w eo -c "m $*"`
mplayer -fs -framedrop "$@"
suuid -t c_m -c "Session $uuid ferdig."
