#!/bin/sh

#=======================================================
# $Id: epstat,v 1.5 2002/01/08 16:49:28 sunny Exp $
# Lager enkel statistikk over hits osv i en loggfil.
# Forventer antall sekunder siden 1970 etterfulgt av TAB
# i begynnelsen av hver linje.
#=======================================================

tmp_file=/tmp/epstat.$RANDOM.tmp

cut -c 1-10 $* | sort -n | ep -l >$tmp_file

echo
echo Totalt $(wc -l $tmp_file | rmspcall | cut -d ' ' -f 1) hits.

echo Antall hits pr. døgn:
echo
uniq -cw 10 $tmp_file | tr T ' ' | cut -c 1-18 | perl -pe 's/^\s+(\d+)\s+(.*)$/$2\t$1/'
echo

echo Antall hits pr. time:
echo
uniq -cw 13 $tmp_file | tr [T:] ' ' | cut -c 1-21 | perl -pe 's/^\s+(\d+)\s+(.*)$/$2\t$1/'

rm $tmp_file
