#!/bin/sh

# $Id: access-myf,v 1.1 2001/09/19 11:58:44 sunny Exp $
# Versjon av myf(1) som lister ut tidspunktet sist aksessert istedenfor modifisert.

find $* -printf "%AY-%Am-%Ad %AH:%AM:%AS\t%6s\t%U.%G\t%p\n"
