#!/bin/sh

# $Id: batlf,v 1.1 2002/10/20 12:50:54 sunny Exp $
# Leiter i telefonlista til BA.

if [ "$1" = "" ]; then
	lynx http://intern.ba.no/telefonliste/Telefonliste.htm
else
	lynx -dump http://intern.ba.no/telefonliste/Telefonliste.htm | grep -i "$*"
fi
