#!/bin/bash

# $Id: mp3_to_ogg,v 1.1 2002/11/27 00:10:04 sunny Exp $
# Konverterer alle *.mp3-filene til ogg i en egen katalog.

CHARSET=UTF-8
KVAL=$1

[ "$1" = "" ] && { echo "Syntax: $0 kvalitet" >&2; exit 1; }
[ -d "ogg" ] || mkdir ogg || { echo "Klarte ikke mkdir ogg" >&2; exit 1; }
for f in *.mp3; do
	if [ -e "$f" ]; then
		echo $f;
		mpg321 --wav - "$f" | oggenc -q$KVAL -c "encoding=`oggenc --version 2>&1` -q$KVAL" -o $(echo ogg/$f|perl -pe "s/\\.mp3\$//" |tr ' ' _).q$KVAL.ogg -
	else
		echo $f finnes ikke. Driter i den.
	fi
done
