#!/bin/bash

#=======================================================================
# $Id$
# File ID: 4e48417c-f743-11dd-93fd-000475e441b9
# Kopierer bilder til maskinen.
# License: GNU General Public License version 2 or later. Fordi dette er 
# stor og viktig software som alle klør etter å få tak i.
#=======================================================================

if [ -d /media/NIKON\ D300/DCIM/. ]; then
    nf /media/NIKON\ D300/DCIM | tail -2
    rsync -av /media/NIKON\ D300/ /media/alt/bilder/in/Nikon_D300/
fi

if [ -d /media/2\ GB/Videos/. ]; then
    nf /media/2\ GB/Videos | grep -v _PAlbTN | tail -1
    nf /media/2\ GB/Images | grep -v _PAlbTN | tail -1
    rsync -av --exclude "00 My Videos" /media/2\ GB/ /media/alt/bilder/in/Nokia_N95/
fi
