#!/bin/bash

#=======================================================================
# $Id$
# Lists broken links. Hacky and has to be tuned for other environments.
#=======================================================================

ls -la --color "$@" | grep ^l | grep '01;05;37;41m'
