#!/usr/bin/perl -w

#===============================================================
# $Id$
# Skips the first N lines from stdin or specified file(s).
#
# Character set: UTF-8
# License: GNU General Public License version 2 or later
# ©opyleft 2003 Øyvind A. Holm <sunny@sunbase.org>
#===============================================================

use strict;

$| = 1;

use Getopt::Std;

our ($opt_l) = (0);
getopts('l:');

unless ($opt_l) {
	usage(1);
}

for (my $Count = $opt_l; $Count; $Count--) {
	<>;
}

while (<>) {
	print;
}

sub usage {
	my $Retval = shift;
	print <<END;

Syntax: $0 -l lines

END
	exit($Retval);
}

__END__

=pod

=head1 LICENCE

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2 of the License, or (at your 
option) any later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

=cut

# vim: set fileencoding=UTF-8 filetype=perl foldmethod=marker foldlevel=0 :
# End of file $Id$
