#!/usr/bin/env bash

#=======================================================================
# test-ly-files
# File ID: 57712470-0790-11e6-9cac-fefdb24f8e10
#
# Test build of LilyPond template files
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=test-ly-files
VERSION=0.3.0

ARGS="$(getopt -o "\
a\
h\
q\
v\
" -l "\
all,\
help,\
quiet,\
verbose,\
version,\
" -n "$progname" -- "$@")"
test "$?" = "0" || exit 1
eval set -- "$ARGS"

opt_all=0
opt_help=0
opt_quiet=0
opt_verbose=0
while :; do
    case "$1" in
        (-a|--all) opt_all=1; shift ;;
        (-h|--help) opt_help=1; shift ;;
        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
        (--version) echo $progname $VERSION; exit 0 ;;
        (--) shift; break ;;
        (*) echo $progname: Internal error >&2; exit 1 ;;
    esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
    cat <<END

Test build of LilyPond template files

Usage: $progname [options]

Options:

  -a, --all
    Also run "tm" to check the MIDI and "evince" to check the PDF.
  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
    exit 0
fi

rm -fv STDprojnameDTS.{ly,midi,pdf,wav}

for f in *.ly; do
    echo
    echo === $f
    ln -fnsv $f STDprojnameDTS.ly
    make touch
    make || exit 1
    make STDprojnameDTS.wav
    test -f STDprojnameDTS.wav || {
        echo $progname: STDprojnameDTS.wav does not exist >&2
        exit 1
    }
    if test "$opt_all" = "1"; then
        tm STDprojnameDTS.midi
        evince STDprojnameDTS.pdf
    fi
done
