# Makefile
# File ID: fc16fb22-4af1-11e6-b2e1-02010e0a6634
# Author: Øyvind A. Holm <sunny@sunbase.org>

.PHONY: default
default:

.PHONY: clean
clean:
	cd tests && $(MAKE) clean

.PHONY: test
test:
	cd tests && $(MAKE) test

.PHONY: testport
testport:
	cd tests && $(MAKE) testport
