#!/bin/bash

#=======================================================================
# $Id$
# File ID: 9cf16956-fafa-11dd-9073-000475e441b9
# Read GPS data from stdin or file names at the command line and send a 
# PostgreSQL table to stdout. Needs a database called "tmpgps" with the 
# usual tables.
# License: GNU General Public License version 2 or later.
#=======================================================================

cat "$@" | gpst -o pgtab | \
    psql -c "TRUNCATE logg; COPY logg (date, coor, ele, name, dist, description) FROM stdin;" tmpgps
cd ~/bin/src/gpstools/postgres
psql -f "$HOME/bin/src/gpstools/postgres/allupdate.sql" tmpgps >/dev/null 2>&1
psql -f "$HOME/bin/src/gpstools/postgres/distupdate.sql" tmpgps >/dev/null 2>&1
psql -c "SELECT date as date, coor, name, dist FROM logg ORDER BY date;" tmpgps
