#!/bin/bash

# $Id: cvscat,v 1.2 2002/07/15 13:21:51 sunny Exp $

if [ $# -le 1 ]; then
	cat <<END

Syntax: cvscat file revision

END
	exit 1
fi

cvs -d $(cat CVS/Root) co -p -r $2 $(cat CVS/Repository)/$1
