#!/usr/bin/perl -w

# $Id: fixtext,v 1.1 2002/09/29 05:43:01 sunny Exp $
# Enkel konvertering av tekst til entities og denslags.

use strict;

$_ = join("", <>);
s/'/&#x2019;/g;
s/"(.*?)"/&#x201C;$1&#x201D;/gs;
s/ -- / &#x2014; /g;
print;
