#!/usr/bin/perl -w

# $Id: skipline,v 1.1 2002/05/26 17:29:03 sunny Exp $
# Only prints every n'th line from stdin

defined($ARGV[0]) || die("\nSyntax: $0 number_of_lines_to_skip [file [...]]\n\n");

my $Skip = $ARGV[0];
shift;

($Skip =~ /[^0-9]/) && die("$Skip: Invalid character in number");
$Skip || die("Number has to be greater than zero");

my $Count = 0;

while(<>) {
	($Count++ % $Skip) || print;
}
