#!/bin/sh

# $Id: still_klokka,v 1.2 2003/03/28 01:11:27 sunny Exp $

if [ -e /carmbb.mrk ]; then
	# [ "`whoami`" = "root" ] || { echo $0: Må være root. >&2; exit 1; }
	su root -c "/etc/init.d/hwclockfirst.sh start"
	# getdate -set 3 300 ntp.lth.se
	# setclock
else
	echo $0: Er beregnet for carmbb. >&2
	exit 1
fi
