#!/bin/bash

# $Id: ww-backup,v 1.1 2001/02/26 19:42:12 sunny Exp $
# Tar backup av greier fra ww-maskinen. Lager fil i current dir.

[ -e /sunba.mrk ] || { echo $0: Skal kjøres på sunba. >&2; exit 1; }

[ -z $1 ] && { echo Syntax: $0 cvsroot\|sunny\|badata >&2; exit 1; }

if [ "$1" = "cvsroot" ]; then
	ssh root@ww '(cd /home/sunny; tar cvzf - cvsroot)' >cvsroot.`u`.ww.tar.gz
else
	ssh root@ww "tar cvzf - \`cat /home/$1/Backupliste\`" >$1.`u`.tar.gz
fi
