/*
 * strings.c
 * File ID: STDuuidDTS
 *
 * (C)opyleft STDyearDTS- Øyvind A. Holm <sunny@sunbase.org>
 *
 * This program is free software; you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free 
 * Software Foundation; either version 2 of the License, or (at your option) 
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with 
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "STDexecDTS.h"

/*
 * mystrdup() - Custom implementation of `strdup()`, which isn't available in 
 * C99. Returns a pointer to an allocated duplicate of `s`. If `malloc()` fails 
 * or `s` is NULL, it returns NULL.
 */

char *mystrdup(const char *s)
{
	size_t size;
	char *p;

	if (!s)
		return NULL;
	size = strlen(s);
	p = malloc(size + 1);
	if (!p)
		return NULL; /* gncov */
	memcpy(p, s, size);
	p[size] = '\0';

	return p;
}

/*
 * allocstr_va() - Returns pointer to allocated string generated by providing 
 * printf()-like format and va_list. Returns NULL on error.
 */

char *allocstr_va(const char *format, va_list ap)
{
	char *p;
	int needed;
	va_list ap_copy;
	size_t size;

	assert(format);
	if (!format)
		return NULL; /* gncov */

	va_copy(ap_copy, ap);
	needed = vsnprintf(NULL, 0, format, ap_copy);
	va_end(ap_copy);

	if (needed < 0)
		return NULL; /* gncov */

	size = (size_t)needed + 1;
	p = malloc(size);
	if (!p)
		return NULL; /* gncov */

	needed = vsnprintf(p, size, format, ap);
	if (needed < 0) {
		free(p); /* gncov */
		return NULL; /* gncov */
	}

	return p;
}

/*
 * allocstr() - Returns pointer to an allocated string generated by providing 
 * printf()-like arguments. Returns NULL on error.
 */

char *allocstr(const char *format, ...)
{
	va_list ap;
	char *retval;

	assert(format);
	if (!format)
		return NULL; /* gncov */

	va_start(ap, format);
	retval = allocstr_va(format, ap);
	va_end(ap);

	return retval;
}

/*
 * count_substr() - Returns the number of non-overlapping occurrences of 
 * substring `substr` in string `s`.
 */

size_t count_substr(const char *s, const char *substr)
{
	size_t count = 0, len_ss;
	const char *p = s;

	if (!s || !substr || !*s || !*substr)
		return 0;

	len_ss = strlen(substr);
	while ((p = strstr(p, substr)) != NULL) {
		count++;
		p += len_ss;
	}

	return count;
}

/*
 * str_replace() - Returns an allocated string where all substrings `s1` are 
 * replaced with the string `s2` in the string `s`.
 *
 * Returns NULL if any errors occur or if `s`, `s1` or `s2` are NULL.
 *
 * If `s1` is empty, an allocated copy of `s` is returned.
 */

char *str_replace(const char *s, const char *s1, const char *s2)
{
	size_t len_s1, len_s2, count, new_len;
	const char *tmp, *src;
	char *buf, *dest;

	if (!s || !s1 || !s2)
		return NULL;

	len_s1 = strlen(s1);
	len_s2 = strlen(s2);
	count = count_substr(s, s1);

	if (!*s || !*s1 || !count)
		return allocstr("%s", s);

	new_len = strlen(s) + count * (len_s2 - len_s1);
	buf = malloc(new_len + 1);
	if (!buf)
		return NULL; /* gncov */

	dest = buf;
	src = s;
	while ((tmp = strstr(src, s1)) != NULL) {
		size_t len_before = (size_t)(tmp - src);

		memcpy(dest, src, len_before);
		dest += len_before;

		memcpy(dest, s2, len_s2);
		dest += len_s2;

		src = tmp + len_s1;
	}
	strcpy(dest, src);

	return buf;
}

/* vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 : */
