/*
 * strings.c
 * File ID: STDuuidDTS
 *
 * (C)opyleft STDyearDTS- Øyvind A. Holm <sunny@sunbase.org>
 *
 * This program is free software; you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free 
 * Software Foundation; either version 2 of the License, or (at your option) 
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with 
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "STDexecDTS.h"

/*
 * allocstr() - Returns pointer to allocated string generated by providing 
 * printf()-like arguments. Returns NULL on error.
 */

char *allocstr(const char *format, ...)
{
	va_list ap;
	char *p;
	size_t size = BUFSIZ;
	int needed;

	assert(format);
	if (!format) {
		myerror("%s(): format is NULL", __func__); /* gncov */
		return NULL; /* gncov */
	}

	p = malloc(size);
	if (!p) {
		myerror("%s():%d: Cannot allocate %zu bytes", /* gncov */
		        __func__, __LINE__, size);
		return NULL; /* gncov */
	}

	va_start(ap, format);
	needed = vsnprintf(p, size, format, ap);
	if (needed < 0) {
		myerror("%s():%d: vsnprintf() failed", /* gncov */
		        __func__, __LINE__);
		free(p); /* gncov */
		va_end(ap); /* gncov */
		return NULL; /* gncov */
	}
	if ((size_t)needed >= size) {
		free(p);
		size = (size_t)needed + 1;
		p = malloc(size);
		if (!p) {
			myerror("%s():%d: Cannot allocate %zu" /* gncov */
			        " bytes", __func__, __LINE__, size);
			va_end(ap); /* gncov */
			return NULL; /* gncov */
		}
		va_end(ap);
		va_start(ap, format);
		needed = vsnprintf(p, size, format, ap);
		if (needed < 0) {
			myerror("%s():%d: vsnprintf() failed", /* gncov */
			        __func__, __LINE__);
			free(p); /* gncov */
			va_end(ap); /* gncov */
			return NULL; /* gncov */
		}
	}
	va_end(ap);

	return p;
}

/* vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 : */
