#!/bin/bash

#=======================================================================
# compile
# File ID: f3c9e59e-8605-11e0-9e54-fefdb24f8e10
#
# Check that the files compile
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#=======================================================================

progname=compile
VERSION=0.3.0

set -e

if test "$1" = "--version"; then
    echo $progname $VERSION
    exit 0
fi

if test "$1" = "-h" -o "$1" = "--help"; then
    cat <<END

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  --version
    Print version information.

END
    exit 0
fi

fname=STDexecDTS
test -e $fname.h || ln -s std.h $fname.h
test -e $fname.c || ln -s std.c $fname.c
make
test -d t || mkdir t
cd t
test -f $fname.t || std --dbname none perl-tests $fname.t -t progname=$fname
./$fname.t
cd ..

tmpdir=./compile.tmp
rm -rf $tmpdir
mkdir $tmpdir
cd $tmpdir || { echo $0: $tmpdir: cannot chdir >&2; exit 1; }
SUUID_LOGDIR=$(pwd)/uuids
mkdir $SUUID_LOGDIR
echo ==== std ====
std -d ./synced.sqlite -t exec=jada c/std.c jada.c
std -d ./synced.sqlite -t exec=jada c/std.h jada.h
std -d ./synced.sqlite -t exec=jada c/version.h version.h
std -d ./synced.sqlite -t exec=jada c/Makefile Makefile
echo ==== make clean ====
make clean
echo ==== make ====
make
mkdir t
cd t
std --dbname none perl-tests jada.t -t progname=jada
./jada.t
