# Makefile.std-test
# File ID: 0817d7ec-b768-11e6-a01b-279c2a0468a3

.PHONY: all
all:
	cd src && $(MAKE) -f Makefile.std-test

.PHONY: clean
clean:
	rm -f README.md.tmp
	$(MAKE) -f Makefile clean
	cd src && $(MAKE) -f Makefile.std-test clean

.PHONY: test
test:
	cmark -t commonmark README.md >README.md.tmp
	test -z "$$(diff -q README.md README.md.tmp)"
	rm -f README.md.tmp
	cd src && $(MAKE) -f Makefile.std-test test
