# Makefile.std-test
# File ID: 0817d7ec-b768-11e6-a01b-279c2a0468a3

TMP=compile.tmp

.PHONY: default
default:

.PHONY: clean
clean:
	rm -f STDexecDTS STDexecDTS.o STDexecDTS.c STDexecDTS.h
	rm -f *.gcda *.gcno *.gcov
	rm -f version.h
	rm -rf $(TMP)

.PHONY: test
test:
	rm -f STDexecDTS.c STDexecDTS.h
	ln -sf std.h STDexecDTS.h
	ln -sf std.c STDexecDTS.c
	$(MAKE) clean
	$(MAKE)
	./STDexecDTS
	rm -rf $(TMP)
	git init $(TMP)
	test -d $(TMP)/.git
	cd $(TMP) && git commit --allow-empty -m "Empty start commit"
	mkdir -p $(TMP)/src $(TMP)/uuids
	cd $(TMP)/src && \
	    SUUID_LOGDIR=$$(pwd)/../uuids ../../../../../create_cproject jada
	cd $(TMP)/src && git add .
	cd $(TMP)/src && git commit -m "create_cproject jada"
	cd $(TMP) && test -z "$(git ls-files --exclude-standard -o)"
	cd $(TMP)/src && $(MAKE)
	cd $(TMP)/src && $(MAKE) test
	cd $(TMP) && test -z "$(git ls-files --exclude-standard -o)"
	cd $(TMP)/src && $(MAKE) clean
	cd $(TMP)/src && $(MAKE) valgrind
	cd $(TMP) && test -z "$(git ls-files -m)"
