#!/bin/bash

#=======================================================================
# $Id$
# File ID: STDuuidDTS
# [Description]
# License: GNU General Public License version 2 or later.
#=======================================================================


