#!/bin/bash

#==============================================================================
# STDfilenameDTS
# File ID: STDuuidDTS
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=STDfilenameDTS
VERSION=0.0.0

if test "$1" = "--version"; then
	echo $progname $VERSION
	exit 0
fi

if test "$1" = "-h" -o "$1" = "--help"; then
	cat <<END

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  --version
    Print version information.

END
	exit 0
fi

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
