#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""STDfilenameDTS - STDdescDTS

File ID: STDuuidDTS
License: GNU General Public License version 2 or later.
Author: Øyvind A. Holm <sunny@sunbase.org>

"""

import argparse
import os

progname = os.path.basename(__file__)

parser = argparse.ArgumentParser(
    description='',
    )
args = parser.parse_args()

def main():
    retval = 0
    return retval

if __name__ == "__main__":
    main()
