#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""STDfilenameDTS - STDdescDTS

File ID: STDuuidDTS

[Description]

License: GNU General Public License version 2 or later.
Author: Øyvind A. Holm <sunny@sunbase.org>

"""

import argparse
import os
import sys

progname = os.path.basename(__file__)

parser = argparse.ArgumentParser(
    description='',
    )
parser.add_argument('-v', '--verbose', action='count',
                    default=0, help='verbose level, can be repeated')
args = parser.parse_args()

def main():
    retval = 0
    return retval

if __name__ == "__main__":
    main_result = main()
    sys.exit(main_result)
