#!/usr/bin/env python
# -*- coding: utf-8 -*-

#=======================================================================
# STDfilenameDTS
# File ID: STDuuidDTS
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

