#!/usr/bin/perl

# $Id: mvdirnewest,v 1.4.4.1 2002/04/18 14:42:03 sunny Exp $
#
# Syntax: $0 directory
# Forandrer navnet på directoryen til den nyeste fila i trestrukturen under.
# Brukes til å lage orden i gamle versjoner av ting som ligger slengende rundt.
#
# (C)opyleft 1999-2000 Øyvind A. Holm <sunny256@mail.com>

my $RetVal;
$prog_name = $0;
$prog_name =~ s!.*/(.+?)$!$1!;

if ($#ARGV == -1) {
	print <<END;

Syntax: $prog_name directory [directory [...]]

The program scans the underlying tree structure and renames the directory
to the date of the newest file.
END
	exit 1;
}

die("$prog_name: Unknown version of find(1) or program not found\n") unless (`find --version` =~ /GNU find/);

foreach (@ARGV) {
	$RetVal ||= &process_dir($_);
}

exit $RetVal;

sub process_dir {
	my $dir_name = shift;
	unless (-e $dir_name) {
		warn("$prog_name: $dir_name: Directory not found\n");
		return;
	}
	unless (-d $dir_name) {
		warn("$prog_name: $dir_name: Not a directory\n");
		return;
	}
	my $newest_date = 99999999999;
	my $newest_file = "";

	# FIXME: Dette med find er midlertidig (og kommer sikkert til å forbli her :)
	my @Files = `find $dir_name -type f`;
	unless (scalar @Files) {
		warn("$prog_name: $dir_name: No files found in directory\n");
		return;
	}
	foreach (@Files) {
		chomp;
		my $file_name = $_;
		my @stat_array;
		unless (@stat_array = stat($file_name)) {
			warn("$prog_name: $file_name: Can't stat file: $!\n");
			return;
		}
		my $file_date = $stat_array[9];
		if ($file_date < $newest_date) {
			$newest_date = $file_date;
			$newest_file = $file_name;
		}
		# printf("$file_name: %s\n", &date2str($file_date));
		my $new_name = &date2str($file_date);
	}
	$new_name = sprintf("%s.%s", &date2str($newest_date), $dir_name);
	if (-e $new_name) {
		warn("$prog_name: $new_name: Directory entry already exists, skipping directory $dir_name\n");
		return;
	} else {
		# printf("Skulle til å rename(%s, %s)\n", $dir_name, $new_name);
		rename($dir_name, $new_name) || warn("$dir_name: Can't rename directory to $new_name: $!\n");
		print("$prog_name: $dir_name --> $new_name\n");
	}
	return 0;
} # process_dir()

sub date2str {
	my $Retval = shift;
	return $Retval;
	@TA = gmtime(shift);
	return(sprintf("%04u%02u%02uT%02u%02u%02uZ", $TA[5]+1900, $TA[4]+1, $TA[3], $TA[2], $TA[1], $TA[0]));
} # date2str()

#### End of file $Id: mvdirnewest,v 1.4.4.1 2002/04/18 14:42:03 sunny Exp $ ####
